### ISSUE TITLE
[distributed_index] crash SG on startup

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#1095]
config file https://gist.github.com/tleyden/7d2698af1c17c255ead4#file-gistfile1-txt-L27-L31
example from https://github.com/couchbase/sync_gateway/issues/1079 

sg commit 87b4cdcac9a1d5

on my local CB instance I have 2 buckets: bucket-1:password and hannel_index

```
../sync_gateway/bin/sync_gateway /Users/andrei/couchbase_src/sync-gateway-tests/config/admin_party_cb.json
2015-08-27T23:43:07.552+03:00 Enabling logging: [*]
2015-08-27T23:43:07.553+03:00 ==== Couchbase Sync Gateway/feature/distributed_index(87b4cdc) ====
2015-08-27T23:43:07.553+03:00 Configured Go to use all 8 CPUs; setenv GOMAXPROCS to override this
2015-08-27T23:43:07.553+03:00 Configured process to allow 5000 open file descriptors
2015-08-27T23:43:07.553+03:00 Opening db /db as bucket "bucket-1", pool "default", server <http://localhost:8091>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40828bc]

goroutine 1 [running]:
github.com/couchbase/sync_gateway/rest.(*ServerContext).initCBGTManager(0xc208134ac0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/server_context.go:149 +0xb1c
github.com/couchbase/sync_gateway/rest.(*ServerContext).getOrAddDatabaseFromConfig(0xc208134ac0, 0xc2080da480, 0xc208139e00, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/server_context.go:299 +0x86c
github.com/couchbase/sync_gateway/rest.(*ServerContext).AddDatabaseFromConfig(0xc208134ac0, 0xc2080da480, 0xc208139ea8, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/server_context.go:500 +0x49
github.com/couchbase/sync_gateway/rest.RunServer(0xc208070dc0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:552 +0x335
github.com/couchbase/sync_gateway/rest.ServerMain()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:583 +0x34
main.main()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:33 +0x195

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [chan receive]:
main.func·001()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:27 +0x5c
created by main.main
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:31 +0x18e
```

**Comment by tleyden** [comment]
@andreibaranouski we just merged a PR https://github.com/couchbase/sync_gateway/pull/1094

Can you retest with the latest?

**Comment by andreibaranouski** [comment]
new stack trace

```
 ../sync_gateway/bin/sync_gateway /Users/andrei/couchbase_src/sync-gateway-tests/config/admin_party_cb.json
2015-08-28T14:01:06.324+03:00 Enabling logging: [*]
2015-08-28T14:01:06.325+03:00 ==== Couchbase Sync Gateway/feature/distributed_index(11dbe12) ====
2015-08-28T14:01:06.325+03:00 Configured Go to use all 8 CPUs; setenv GOMAXPROCS to override this
2015-08-28T14:01:06.325+03:00 Configured process to allow 5000 open file descriptors
2015/08/28 14:01:06 ServerContext.registerCbgtPindexType()
2015/08/28 14:01:06 /ServerContext.registerCbgtPindexType()
2015-08-28T14:01:06.325+03:00 Opening db /db as bucket "bucket-1", pool "default", server <http://localhost:8091>
2015-08-28T14:01:06.326+03:00 Opening Couchbase database bucket-1 on <http://localhost:8091> as user "bucket-1"
2015/08/28 14:01:06  Trying with selected node 0
2015/08/28 14:01:06  Trying with selected node 0
2015-08-28T14:01:06.529+03:00 Opening index bucket "channel_index", pool "default", server <http://localhost:8091>
2015-08-28T14:01:06.530+03:00 Opening Couchbase database channel_index on <http://localhost:8091> as user "channel_index"
2015-08-28T14:01:06.558+03:00 WARNING: Stable sequence not found in index - treating as 0 -- db.(*kvChangeIndex).loadStableClock() at kv_change_index.go:136
2015-08-28T14:01:06.558+03:00 Feed: loadStableClock:[cas:0]
2015-08-28T14:01:06.558+03:00 Shadow: Watching doc changes...
2015-08-28T14:01:06.561+03:00 Using default sync function 'channel(doc.channels)' for database "db"
2015-08-28T14:01:06.565+03:00 Auth: Saved _sync:user:: {"admin_channels":{"*":1},"all_channels":null,"sequence":1,"disabled":true,"rolesSince":null}
2015-08-28T14:01:06.565+03:00     Reset guest user to config
2015-08-28T14:01:06.565+03:00 WARNING: The GUEST user is the only user defined in the 'db' database, but is either disabled or has no access to any channels.  This means that you will not be able to get useful data out of the sync gateway over the standard port.  FIX: enable and/or grant access to the GUEST user to channels via the admin_channels parameter. -- rest.emitAccessRelatedWarnings() at server_context.go:885
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x406f665]

goroutine 1 [running]:
github.com/couchbase/sync_gateway/rest.RunServer(0xc208070dc0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:564 +0x475
github.com/couchbase/sync_gateway/rest.ServerMain()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:596 +0x34
main.main()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:33 +0x195

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [chan receive]:
main.func·001()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:27 +0x5c
created by main.main
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:31 +0x18e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 18 [IO wait]:
net.(*pollDesc).Wait(0xc2080d6060, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080d6060, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080d6000, 0xc208132000, 0x1000, 0x1000, 0x0, 0x4f82df0, 0xc20811b560)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208046068, 0xc208132000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x4f87f18, 0xc208046068, 0xc2080861b8, 0xc208132000, 0x1000, 0x1000, 0x4656cc0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20813e100, 0xc208132000, 0x1000, 0x1000, 0xc208140000, 0x0, 0x0)
    <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208064480)
    /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208064480, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208086160)
    /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 19 [select]:
net/http.(*persistConn).writeLoop(0xc208086160)
    /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 22 [chan receive]:
github.com/couchbase/sync_gateway/db.(*kvChangeIndex).readFromPending(0xc20816a630, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:296 +0xc8
github.com/couchbase/sync_gateway/db.(*kvChangeIndex).indexPending(0xc20816a630)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:322 +0x69
created by github.com/couchbase/sync_gateway/db.(*kvChangeIndex).Init
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:96 +0x274

goroutine 23 [chan receive]:
github.com/couchbase/sync_gateway/db.func·010()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_listener.go:51 +0x10b
created by github.com/couchbase/sync_gateway/db.(*changeListener).Start
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_listener.go:68 +0x42e

goroutine 24 [chan receive]:
github.com/couchbase/sync_gateway/db.(*DatabaseContext).watchDocChanges(0xc208175860)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/assimilator.go:16 +0xd6
created by github.com/couchbase/sync_gateway/db.NewDatabaseContext
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/database.go:146 +0x7bf
Andreis-MacBook-Pro:sync_gateway andrei$ git log
commit 11dbe120908c5008ee4deebcd7611a1e2b85081c
Merge: 87b4cdc fd299bc
Author: Adam Fraser <adamf@couchbase.com>
Date:   Thu Aug 27 14:47:55 2015 -0700

    Merge pull request #1094 from couchbase/feature/distributed_index_single_manager


Andreis-MacBook-Pro:sync_gateway andrei$ cat /Users/andrei/couchbase_src/sync-gateway-tests/config/admin_party_cb.json
{
  "interface":":4984",
  "adminInterface":":4985",
  "log":[
    "*"
  ],
  "verbose":"true",
  "databases":{
    "db":{
      "feed_type":"DCPSHARD",
      "feed_params":{
        "max_partitions_per_pindex":512,
        "num_replicas":0,
        "data_dir":"/tmp"
      },
      "server":"http://bucket-1:password@localhost:8091",
      "revs_limit":3,
      "users":{
        "GUEST":{
          "disabled":true,
          "admin_channels":[
            "*"
          ]
        }
      },
      "bucket":"bucket-1",
      "channel_index":{
        "server":"http://channel_index@localhost:8091",
        "bucket":"channel_index",
        "writer":true
      }
    }
  }
}
```

**Comment by tleyden** [comment]
Thanks @andreibaranouski.  The config changed and I forgot to send you the new version.

However before I do that, I will make the code do some validation and handle this case better.

**Comment by tleyden** [comment]
I pushed a new commit that will fix the null pointer panic and do more config validation.

Please use this updated config:

https://gist.github.com/tleyden/7d2698af1c17c255ead4
