### ISSUE TITLE
[distributed_index] crash in index_changes

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#1103]
parent ticket https://github.com/couchbase/sync_gateway/issues/1079

SG commit bea2452207

crash in cbl-replication-api.js

```
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xb code=0x1 addr=0x78 pc=0x42d8a0f]

goroutine 265 [running]:
[signal 0xb code=0x1 addr=0x78 pc=0x42d8a0f]

goroutine 265 [running]:

github.com/couchbase/sync_gateway/db.func·032()
    github.com/couchbase/sync_gateway/db.func·032()

/Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/index_changes.go:169 +0x157f
created by github.com/couchbase/sync_gateway/db.(*Database).VectorMultiChangesFeed
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/index_changes.go:229 +0x56d

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc2080e1640, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080e1640, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080e15e0, 0x0, 0x4f83ed0, 0xc208089168)
    /usr/local/go/src/net/fd_unix.go:/Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/index_changes.go:169 +0x157f
created by github.com/couchbase/sync_gateway/db.(*Database).VectorMultiChangesFeed
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/index_changes.go:229 +0x56d

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc2080e1640, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080e1640, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080e15e0, 0x0, 0x4f83ed0, 0xc208089168)
    /usr/local/go/src/net/fd_unix.go:
419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20820c958, 0xc20811aa80, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20820c958, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc2080677a0, 0x4f9cac0, 0xc20820c958, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/couchbase/sync_gateway/base.ListenAndServeHTTP(0x7fff5fbffaad, 0x5, 0x0, 0x0, 0x0, 0x4f842d0, 0xc2081b7380, 0x0, 0x0, 0x0, ...)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/http_listener.go:52419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20820c958, 0xc20811aa80, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20820c958, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc2080677a0, 0x4f9cac0, 0xc20820c958, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/couchbase/sync_gateway/base.ListenAndServeHTTP(0x7fff5fbffaad, 0x5, 0x0, 0x0, 0x0, 0x4f842d0, 0xc2081b7380, 0x0, 0x0, 0x0, ...)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/http_listener.go:52
 +0x5ab
github.com/couchbase/sync_gateway/rest.(*ServerConfig).serve(0xc2080f2640, 0x7fff5fbffaad, 0x5, 0x4f842d0, 0xc2081b7380)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:564 +0xa6
github.com/couchbase/sync_gateway/rest.RunServer(0xc2080f2640)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:611 +0x990
github.com/couchbase/sync_gateway/rest.ServerMain()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:626 +0x34
main.main()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:33 +0x195
```

full stack trace with test output https://friendpaste.com/2BayCv2bZVFNu4XO2qsluZ

**Comment by tleyden** [comment]
What are the instructions to reproduce?  Can it be done via jenkins job?

**Comment by andreibaranouski** [comment]
well, will create jenkins job to run separate branches/tests to reproduce specific issues.
steps for now:

steps :

presetup:
 initialize CB locally with 2 buckets: channel_index and db

1)git clone https://github.com/couchbaselabs/sync-gateway-tests.git
cd sync-gateway-tests
npm install

2)set the following variables matching your path
export SYNCGATE_PATH=~/couchbase_src/sync_gateway/bin/sync_gateway
export LITESERV_PATH=/Users/andrei/couchbase_src/couchbase-lite-ios/build/Products/Debug/LiteServ
export CONF_FILE=local_cb

3)replace config/admin_party_cb.json with https://gist.github.com/andreibaranouski/1f658f93e6212eb0028f

4) run the test:
node tests/cbl-replication-api.js 

node bucket_shadowing/sb_restart_cb_revs_limit.js

**Comment by tleyden** [comment]
@andreibaranouski can you add some docs to cbl-replication-api.js which explains what the test does and then link to that from this github issue?

**Comment by adamcfraser** [comment]
Fixed with https://github.com/couchbase/sync_gateway/commit/e61406eb88966287122cdcabe86d732d0e7818f3

**Comment by tleyden** [comment]
@andreibaranouski any update on this?

**Comment by andreibaranouski** [comment]
there is no crash anymore
