### ISSUE TITLE
[distributed_index] startup SG crash in sequence_clock 

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#1111]
https://github.com/couchbase/sync_gateway/issues/1079
SG commit d74b1f1da6e10
config file https://gist.github.com/andreibaranouski/75e8aa6acb6f464fe661
test tests/cbl-replication.js

crash and test output https://friendpaste.com/6BmTS8UIxET1HQ44vHb3tk

```
2015/09/03 18:05:10 Processing entry with docID:cbl-replication2_20, vbno: 35, sequence:2

panic: Update attempted to set clock to earlier sequence.  Vb: 35, currentSequence: 3, newSequence: 2

panic: Update attempted to set clock to earlier sequence.  Vb: 35, currentSequence: 3, newSequence: 2


goroutine 180 [running]:
github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).UpdateWithClock(0xc208304c00, 0x4fa4330, 0xc2083b7320)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:283 +0x2b0
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).writeClockCas(0xc2082245b0, 0x4fa4330, 0xc2083b7320, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:274 +0x6c
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).AddSet(0xc2082245b0, 0xc2084f4000, 0x1, 0x1f4, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:91 +0x252
github.com/couchbase/sync_gateway/db.(*kvChangeIndex).addSetToChannelIndex(0xc208032bd0, 0x47c0920, 0x1, 0xc2084f4000, 0x1, 0x1f4)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:536 +0x68
github.com/couchbase/sync_gateway/db.func·036(0x47c0920, 0x1, 0x11, 0xc2084f4000, 0x1, 0x1f4)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:396 +0x7e
created by github.com/couchbase/sync_gateway/db.(*kvChangeIndex).indexPending
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:398 +0xa44

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc20819d090, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20819d090, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20819d030, 0x0, 0x4f8ddf0, 0xc20825fb68)
    /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208212570, 0xc20806f880, 0x0, goroutine 180 [running]:
github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).UpdateWithClock(0xc208304c00, 0x4fa4330, 0xc2083b7320)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:283 +0x2b0
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).writeClockCas(0xc2082245b0, 0x4fa4330, 0xc2083b7320, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:274 +0x6c
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).AddSet(0xc2082245b0, 0xc2084f4000, 0x1, 0x1f4, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:91 +0x252
github.com/couchbase/sync_gateway/db.(*kvChangeIndex).addSetToChannelIndex(0xc208032bd0, 0x47c0920, 0x1, 0xc2084f4000, 0x1, 0x1f4)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:536 +0x68
github.com/couchbase/sync_gateway/db.func·036(0x47c0920, 0x1, 0x11, 0xc2084f4000, 0x1, 0x1f4)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:396 +0x7e
created by github.com/couchbase/sync_gateway/db.(*kvChangeIndex).indexPending
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:398 +0xa44
```

**Comment by andreibaranouski** [comment]
workaround that I applied "rm -rf /tmp/sync_gateway.uuid"

**Comment by tleyden** [comment]
> workaround that I applied "rm -rf /tmp/sync_gateway.uuid"

@andreibaranouski can you explain what you mean here?  Are you saying that worked around this issue??

**Comment by andreibaranouski** [comment]
hi @tleyden , yes I deleted this file and SG started successfully. Seems like SG has been crashed or it stopped somehow crookedly. as a result, this file was left over from the previous run. is it possible?

**Comment by tleyden** [comment]
I wasn't able to reproduce with https://github.com/couchbase/sync_gateway/commit/44e17463727d8d530af6f0d55ef66461e97ba679

Here are the logs:

https://gist.github.com/tleyden/c1dd945a2c5798bbd0c8

Note: there was [one failure](https://gist.github.com/tleyden/c1dd945a2c5798bbd0c8#file-gistfile1-txt-L863) but I never saw SG crash after repeated runs of  tests/cbl-replication.js

@andreibaranouski if you retest and reproduce an issue, please re-open.
