### ISSUE TITLE
Need Update and UpdateRaw to support gocb get handling

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1237]
Currently updates to principal docs by index writers is broken when trying to retrieve existing docs.

**Comment by adamcfraser** [comment]
Error details:

```
2015/10/23 15:39:18 planner: awakes, reason: cfg changed, key: indexDefs
panic: interface conversion: interface is map[string]interface {}, not []uint8

goroutine 86 [running]:
github.com/couchbase/sync_gateway/base.CouchbaseBucketGoCB.Update(0xc82034efc0, 0xc8201cfbf0, 0x29, 0xd29d40, 0x7, 0xc8201db0f0, 0x8, 0x0, 0
x0, 0x0, ...)
        /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/base/bucket_gocb.go:226 +0x199
github.com/couchbase/sync_gateway/base.(*CouchbaseBucketGoCB).Update(0xc82020e880, 0xd3dbb0, 0xa, 0x0, 0xc820730d20, 0x0, 0x0)
        <autogenerated>:270 +0xf9
github.com/couchbase/sync_gateway/db.(*kvChangeIndex).processPrincipalDoc(0xc820278780, 0xc82077b100, 0xb, 0xc82077910a, 0x64, 0x64, 0x2c017
01, 0x2)
        /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:418 +0x5c6
github.com/couchbase/sync_gateway/db.(*kvChangeIndex).DocChanged(0xc820278780, 0xc82077b100, 0xb, 0xc82077910a, 0x64, 0x64, 0x2, 0xc8207702c
0)
        /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:309 +0x147
github.com/couchbase/sync_gateway/db.(ChangeIndex).DocChanged-fm(0xc82077b100, 0xb, 0xc82077910a, 0x64, 0x64, 0x2, 0x4002c0)
        /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/db/database.go:140 +0x7f
```

**Comment by adamcfraser** [comment]
Issue is that gocb Get returns {}interface and not []byte, and there's no way in gocb to get raw []bytes for a document flagged as json.  Can workaround this in our update wrapper to work with the json doc directly, instead of marshalling/unmarshalling.

**Comment by tleyden** [comment]
@adamcfraser do you know if we've already fixed this?

**Comment by adamcfraser** [comment]
@tleyden I don't recall fixing this one myself

**Comment by tleyden** [comment]
So is the reason we're not seeing the errors because we have this workaround in place?

> Can workaround this in our update wrapper to work with the json doc directly, instead of marshalling/unmarshalling.

**Comment by adamcfraser** [comment]
I'm not sure we're doing principal updates in the gateload test - I don't know why

**Comment by adamcfraser** [comment]
Needs functional or unit test to confirm fix or repro.
