### ISSUE TITLE
[Distributed Index] Panic when shutting down sg_accel while it is indexing

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1471]
Steps to reproduce. 
- checkout test cluster dual-binary-provisioning

```
python/install_sync_gateway.py --version 1.2.0-47
```

```
python run_tests.py -t "functional_tests/test_dcp_reshard.py"
```

Error

```
opaqueValue: {"seqStart":8,"seqEnd":18446744073709551615,"snapStart":8,"snapEnd":8,"failOverLog":[[24463683105915,0]]}, lastSeq: 8
2016-01-15T13:46:38.410-08:00 WARNING: DCP Rollback request SyncGatewayPIndex - rolling back DCP feed for: vbucketId: 40, rollbackSeq: 6 -- base.(*SyncGatewayPIndex).Rollback() at sgw_pindex.go:338
2016/01/15 13:46:38 planner: awakes, op: kick, msg: cfg changed, key: nodeDefs-wanted
2016/01/15 13:46:38 planner: once, reason: cfg changed, key: nodeDefs-wanted
2016/01/15 13:46:38 feed_dcp: rollback, name: data-bucket265da89183815105ac263955f79b55f8_b6422efe5c4ed738: vbucketId: 335, rollbackSeq: 2, partition: 335, opaqueValue: {"seqStart":3,"seqEnd":18446744073709551615,"snapStart":3,"snapEnd":3,"failOverLog":[[51567330473379,0]]}, lastSeq: 3
2016-01-15T13:46:38.445-08:00 WARNING: DCP Rollback request SyncGatewayPIndex - rolling back DCP feed for: vbucketId: 335, rollbackSeq: 2 -- base.(*SyncGatewayPIndex).Rollback() at sgw_pindex.go:338
panic: Update attempted to set clock to earlier sequence.  Vb: 269, currentSequence: 2, newSequence: 1

goroutine 16165 [running]:
github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).UpdateWithClock(0xc8202fc510, 0x7f96facbbca0, 0xc8214b2b10)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:277 +0x2e0
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).writeClockCas(0xc820384e40, 0x7f96facbbca0, 0xc8214b2b10, 0x0, 0x0)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:339 +0x66
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).AddSet(0xc820384e40, 0xc821806000, 0x4f, 0x7d0, 0x0, 0x0)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:84 +0x268
```

Full logs - https://s3.amazonaws.com/sync-gateway-logs/functional_tests-test_dcp_reshard.py-test_dcp_reshard_sync_gateway_goes_down%5BDI-1%5D-2016-01-15-13-46-47-sglogs.zip

**Comment by adamcfraser** [comment]
This looks like a permutation of https://github.com/couchbase/sync_gateway/issues/1371 - when trying to pick up the 32 additional pindexes, it's starting the DCP feed at a point that's triggering rollbacks.

**Comment by tleyden** [comment]
@adamcfraser can we close as a duplicate?

**Comment by adamcfraser** [comment]
@tleyden I think so - I'll make a comment on #1371 that the fix should be verified against the test described here.
