### ISSUE TITLE
Sync_gateway crashes when connecting to a bucket on couchbase

### ISSUE THREAD

**Issue by brion25** [couchbase/sync_gateway#1473]
Hi guys, I'm trying to connect to to a local Couchbase instance using PouchDB, but when I run my `sync-gateway-config.json` the process Fail. Please see below my `sync-gateway-config.json` and the output I get:

**`sync-gateway-config.json`**

```
{
  "log": ["*"],
  "databases": {
    "db": {
      "server": "walrus:",
      "users": { "GUEST": { "disabled": true, "admin_channels": ["*"] } },
      "allow_empty_password": true,
      "shadow": {
        "server": "http://localhost:8091",
        "bucket": "todos"
      }
    }
  },
  "CORS": {
        "Origin": ["http://localhost:3000"],
        "LoginOrigin": ["http://localhost:3000"],
        "Headers": ["Content-Type"],
        "MaxAge": 17280000
    }
}
```

**Console Output**

```
2016/01/15 16:22:53  Trying with http://127.0.0.1:8091/pools/default/bucketsStreaming/todos
panic: runtime error: slice bounds out of range

goroutine 37 [running]:
github.com/couchbase/gomemcached.(*MCRequest).Receive(0xc820174300, 0x5c61110, 0xc82016e048, 0xc820170560, 0x18, 0x18, 0x4724920, 0x0, 0x0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/gomemcached/mc_req.go:181 +0xbcc
github.com/couchbase/gomemcached/client.(*Client).runFeed(0xc820168720, 0xc82026c5a0, 0xc820170540)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/gomemcached/client/tap_feed.go:270 +0x146
created by github.com/couchbase/gomemcached/client.(*Client).StartTapFeed
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/gomemcached/client/tap_feed.go:251 +0x422

goroutine 1 [runnable]:
regexp.mergeRuneSets.func2(0xc8203c1b40, 0xc820327648, 0xc800000003, 0xc820340e20)
    /usr/local/go/src/regexp/onepass.go:176
regexp.mergeRuneSets(0xc820327678, 0xc820327648, 0x300000005, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/regexp/onepass.go:192 +0x308
regexp.makeOnePass.func2(0x400000004, 0xc8203ad170, 0x1)
    /usr/local/go/src/regexp/onepass.go:362 +0x2f5
regexp.makeOnePass.func2(0x2, 0xc8203ad170, 0xc800000001)
    /usr/local/go/src/regexp/onepass.go:388 +0xe6e
regexp.makeOnePass.func2(0x1, 0xc8203ad170, 0xc8203ad101)
    /usr/local/go/src/regexp/onepass.go:377 +0x95c
regexp.makeOnePass(0xc8203ad140, 0xc8203ad140)
    /usr/local/go/src/regexp/onepass.go:469 +0x523
regexp.compileOnePass(0xc8203ad0e0, 0xc8203ad0e0)
    /usr/local/go/src/regexp/onepass.go:575 +0x1c7
regexp.compile(0xc8203c1a90, 0xc, 0xd4, 0xc82006d930, 0x0, 0x0)
    /usr/local/go/src/regexp/regexp.go:168 +0x15a
regexp.Compile(0xc8203c1a90, 0xc, 0xc820341878, 0x0, 0x0)
    /usr/local/go/src/regexp/regexp.go:118 +0x43
github.com/gorilla/mux.newRouteRegexp(0xc8203abae0, 0x16, 0x1000000, 0x49965b0, 0x0, 0x0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/gorilla/mux/regexp.go:83 +0xbcc
github.com/gorilla/mux.(*Route).addRegexpMatcher(0xc8203c3b20, 0xc8203abae0, 0x17, 0x4000000, 0x0, 0x0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/gorilla/mux/route.go:154 +0x1d1
github.com/gorilla/mux.(*Route).Path(0xc8203c3b20, 0x49965b0, 0x7, 0xc8203aba80)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/gorilla/mux/route.go:316 +0x48
github.com/gorilla/mux.(*Router).Handle(0xc82015a5f0, 0x49965b0, 0x7, 0x595a7c8, 0xc8203abaa0, 0xc8203c3110)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/gorilla/mux/mux.go:181 +0x12a
github.com/couchbase/sync_gateway/rest.CreateAdminHandler(0xc8201825a0, 0x0, 0x0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:152 +0xcaa
github.com/couchbase/sync_gateway/rest.RunServer(0xc8201b6780)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:648 +0x7aa
github.com/couchbase/sync_gateway/rest.ServerMain(0xc800000000)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:689 +0x3a
main.main()
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:34 +0x133

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [select, locked to thread]:
runtime.gopark(0x4bb3ac8, 0xc820026728, 0x49a12b0, 0x6, 0x18, 0x2)
    /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820026728, 0x0, 0x18)
    /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820026728)
    /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
    /usr/local/go/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 20 [chan receive]:
main.main.func1(0xc8201944e0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:28 +0x51
created by main.main
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:32 +0x12a

goroutine 21 [sleep]:
time.Sleep(0x9502f900)
    /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/couchbase/sync_gateway/db.(*changeCache).Init.func1(0xc8201ba780)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:116 +0x3c
created by github.com/couchbase/sync_gateway/db.(*changeCache).Init
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:120 +0x3a5

goroutine 22 [sleep]:
time.Sleep(0x1a3185c5000)
    /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/couchbase/sync_gateway/db.(*changeCache).Init.func2(0xc8201ba780)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:124 +0x3c
created by github.com/couchbase/sync_gateway/db.(*changeCache).Init
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:128 +0x3ca

goroutine 23 [semacquire]:
sync.runtime_Syncsemacquire(0xc820189f50)
    /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc820189f40)
    /usr/local/go/src/sync/cond.go:62 +0x9b
github.com/couchbaselabs/walrus.(*queue).pull(0xc820225500, 0x0, 0x0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbaselabs/walrus/queue.go:38 +0xcd
github.com/couchbaselabs/walrus.(*tapFeedImpl).run(0xc820201560)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbaselabs/walrus/tap.go:69 +0x54
created by github.com/couchbaselabs/walrus.(*lolrus).StartTapFeed
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbaselabs/walrus/tap.go:38 +0x40b

goroutine 24 [chan receive]:
github.com/couchbase/sync_gateway/db.(*changeListener).Start.func1(0xc8201f09b8, 0x599abd8, 0xc820201560, 0xc820201501)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_listener.go:57 +0xc0
created by github.com/couchbase/sync_gateway/db.(*changeListener).Start
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_listener.go:74 +0x360

goroutine 25 [chan receive]:
github.com/couchbase/sync_gateway/db.(*DatabaseContext).watchDocChanges(0xc8201f0900)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/assimilator.go:16 +0xca
created by github.com/couchbase/sync_gateway/db.NewDatabaseContext
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/database.go:172 +0x922

goroutine 35 [IO wait]:
net.runtime_pollWait(0x5c60fd8, 0x72, 0xc820010140)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82026e530, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82026e530, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82026e4d0, 0xc820292000, 0x1000, 0x1000, 0x0, 0x5956050, 0xc820010140)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82016e040, 0xc820292000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x5c61110, 0xc82016e040, 0xc820288058, 0xc820292000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820170400, 0xc820292000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82026c3c0)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82026c3c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820288000)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 36 [select]:
net/http.(*persistConn).writeLoop(0xc820288000)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 8 [IO wait]:
net.runtime_pollWait(0x5c60f18, 0x72, 0xc820010140)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82022cfb0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82022cfb0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82022cf50, 0xc820283000, 0x1000, 0x1000, 0x0, 0x5956050, 0xc820010140)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82018c288, 0xc820283000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x5c61110, 0xc82018c288, 0xc82022e9f8, 0xc820283000, 0x1000, 0x1000, 0xc820302020, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82023e7c0, 0xc820283000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820195e00)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820195e00, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:328 +0x21a
net/http/internal.readLine(0xc820195e00, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/internal/chunked.go:110 +0x4b
net/http/internal.(*chunkedReader).beginChunk(0xc8202a2c90)
    /usr/local/go/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc8202a2c90, 0xc8202b2400, 0x200, 0x200, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc8202aa6c0, 0xc8202b2400, 0x200, 0x200, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0xc8202aa6c0, 0xc8202b2400, 0x200, 0x200, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transfer.go:624 +0x110
net/http.(*bodyEOFSignal).Read(0xc8202aa700, 0xc8202b2400, 0x200, 0x200, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1296 +0x26a
encoding/json.(*Decoder).refill(0xc8202b16c0, 0x0, 0x0)
    /usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc8202b16c0, 0x1, 0x0, 0x0)
    /usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc8202b16c0, 0x46d7ae0, 0xc8202b6030, 0x0, 0x0)
    /usr/local/go/src/encoding/json/stream.go:57 +0x159
github.com/couchbase/go-couchbase.(*Bucket).UpdateBucket(0xc8202b11e0, 0x0, 0x0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/go-couchbase/streaming.go:140 +0xd36
github.com/couchbase/go-couchbase.(*Bucket).RunBucketUpdater.func1(0xc8202b11e0, 0xc8202f26c0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/go-couchbase/streaming.go:62 +0x25
created by github.com/couchbase/go-couchbase.(*Bucket).RunBucketUpdater
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/go-couchbase/streaming.go:69 +0x3f

goroutine 9 [select]:
github.com/couchbase/go-couchbase.(*TapFeed).run(0xc82012f380)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:58 +0x45d
created by github.com/couchbase/go-couchbase.(*Bucket).StartTapFeed
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:42 +0x201

goroutine 10 [chan receive]:
github.com/couchbase/sync_gateway/base.CouchbaseBucket.StartCouchbaseTapFeed.func1(0xc82012f380, 0xc8201114a0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/base/bucket.go:258 +0x66
created by github.com/couchbase/sync_gateway/base.CouchbaseBucket.StartCouchbaseTapFeed
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/base/bucket.go:269 +0x1c5

goroutine 11 [chan receive]:
github.com/couchbase/sync_gateway/db.(*Shadower).readTapFeed(0xc82012f3c0)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/shadower.go:62 +0xb5
created by github.com/couchbase/sync_gateway/db.NewShadower
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/sync_gateway/db/shadower.go:38 +0x249

goroutine 28 [select]:
net/http.(*persistConn).readLoop(0xc82022e9a0)
    /usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 29 [select]:
net/http.(*persistConn).writeLoop(0xc82022e9a0)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 38 [runnable]:
github.com/couchbase/go-couchbase.(*TapFeed).forwardTapEvents(0xc82012f380, 0xc820170540, 0xc8202a4480, 0xc82013dba0, 0xf)
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:104 +0x35d
created by github.com/couchbase/go-couchbase.(*TapFeed).connectToNodes
    /Users/brionator/Documents/Other/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:96 +0x38f
```

**Comment by adamcfraser** [comment]
What build of Sync Gateway are you using?

**Comment by brion25** [comment]
I'm using the latest one

**Comment by johnzeng** [comment]
same issue so I wanna mark a +1 here.
 Using macbook pro, go version output:
`go version go1.5.3 darwin/amd64`
and sync_gateway is checkouted by `go get https://github.com/couchbase/sync_gateway...` ( 29th May)
Couchbase version 4.0.0-4051.

**Comment by adamcfraser** [comment]
@Misfit-John It looks like there's an issue when building from source without dependency pinning - I'd recommend building with pinning (see https://github.com/couchbase/sync_gateway/blob/master/README.md)

**Comment by adamcfraser** [comment]
Tracking this issue w/ https://github.com/couchbase/sync_gateway/issues/1585
