### ISSUE TITLE
sg panic when start it with not clean index bucket(remain from a previous run)

### ISSUE THREAD

**Issue by andrei-baranouski** [couchbase/sync_gateway#1496]
I run https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-replication.js twice

```
andreis-mbp:sync-gateway-tests andrei$ cat /Users/andrei/couchbase_src/sync-gateway-tests/config/admin_party_cb.json
{
    "log": ["CRUD", "REST+", "CHANGES"],
  "skip_runmode_validation":true,
  "cluster_config":{
    "server":"http://localhost:8091",
    "data_dir":".",
    "bucket":"db"
  },
    "databases": {
        "db": {
            "feed_type":"DCPSHARD",
            "server": "http://localhost:8091",
            "bucket":"db",
            "channel_index":{
            "server":"http://localhost:8091",
            "bucket":"index-bucket",
            "writer":true
          },
            "sync": `
function(doc){
    channel(doc.channels);
}`,
            "users": {
                "GUEST": {"disabled": false, "admin_channels": ["*"] }
            }
        }
    }
}
```

after the first run 1 doc(_sync:heartbeat:..) remains in db bucket and 165 docs in index-bucket

then I restart the test and see sg panic

```
 2016-01-21T01:55:30.651+03:00 CRUD: Stored doc "cbl-replication2_1" / "1-7e9a636fe4a0a83bb3dcb90189011eb9"

panic: Update attempted to set clock to earlier sequence.  Vb: 49, currentSequence: 3, newSequence: 1

goroutine 467 [running]:
panic: Update attempted to set clock to earlier sequence.  Vb: 49, currentSequence: 3, newSequence: 1

goroutine 467 [running]:

github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).UpdateWithClock(0xc820fee0c0, 0x5d49018, github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).UpdateWithClock(0xc820fee0c0, 0x5d49018, 
0xc82071a5d0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:277 +0x2e0
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).writeClockCas(0xc820132000, 0x5d49018, 0xc82071a5d0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:341 +0x66
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).AddSet(0xc820132000, 0xc8200e6000, 0x1, 0x7d0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:86 +0x3f6
github.com/couchbase/sync_gateway/db.(*kvChangeIndexWriter).addSetToChannelIndex(0xc82017fa80, 0x49792080xc82071a5d0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:277 +0x2e0
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).writeClockCas(0xc820132000, 0x5d49018, 0xc82071a5d0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:341 +0x66
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).AddSet(0xc820132000, 0xc8200e6000, 0x1, 0x7d0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:86 +0x3f6
github.com/couchbase/sync_gateway/db.(*kvChangeIndexWriter).addSetToChannelIndex(0xc82017fa80, 0x4979208
, 0x1, 0xc8200e6000, 0x1, 0x7d0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index_writer.go:372 +0xf7
github.com/couchbase/sync_gateway/db.(*kvChangeIndexWriter).indexEntries.func2(0xc820fc2000, 0xc82017fa80, 0x4979208, 0x1, 0xc8200e6000, 0x1, 0x7d0, 0x3765343700000000)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index_writer.go:344 +0xce
created by github.com/couchbase/sync_gateway/db.(*kvChangeIndexWriter).indexEntries
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index_writer.go:351 +0x465

goroutine 1 [IO wait]:
net.runtime_pollWait(0x5d05268, , 0x1, 0xc8200e6000, 0x1, 0x7d0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index_writer.go:372 +0xf7
github.com/couchbase/sync_gateway/db.(*kvChangeIndexWriter).indexEntries.func2(0xc820fc2000, 0xc82017fa80, 0x4979208, 0x1, 0xc8200e6000, 0x1, 0x7d0, 0x3765343700000000)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index_writer.go:344 +0xce
created by github.com/couchbase/sync_gateway/db.(*kvChangeIndexWriter).indexEntries
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index_writer.go:351 +0x465

goroutine 1 [IO wait]:
net.runtime_pollWait(0x5d05268, 
0x72, 0xc82006c080)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203a6f40, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203a6f40, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8203a6ee0, 0x0, 0x5d4a7c0, 0xc8200e0cc0)
    /usr/local/go/src/net/fd_unix.go:0x72, 0xc82006c080)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203a6f40, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203a6f40, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8203a6ee0, 0x0, 0x5d4a7c0, 0xc8200e0cc0)
    /usr/local/go/src/net/fd_unix.go:
408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8202ec7e8, 0xc8203e7988, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8202ec7e8, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc82014cea0, 0x5d4a788, 0xc8202ec7e8, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/couchbase/sync_gateway/base.ListenAndServeHTTP(0x7fff5fbff9cd, 0x5, 0x0, 0x0, 0x0, 0x5d046b8, 0xc8202600c0, 0x0, 0x0, 408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8202ec7e8, 0xc8203e7988, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8202ec7e8, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc82014cea0, 0x5d4a788, 0xc8202ec7e8, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/couchbase/sync_gateway/base.ListenAndServeHTTP(0x7fff5fbff9cd, 0x5, 0x0, 0x0, 0x0, 0x5d046b8, 0xc8202600c0, 0x0, 0x0, 
0x0, ...)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/http_listener.go:52 +0x549
github.com/couchbase/sync_gateway/rest.(*ServerConfig).serve(0xc8201a4780, 0x7fff5fbff9cd, 0x5, 0x5d046b8, 0xc8202600c0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:580 +0xa3
github.com/couchbase/sync_gateway/rest.RunServer(0xc8201a4780)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:657 +0x949
github.com/couchbase/sync_gateway/rest.ServerMain(0xc800000000)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:696 +0x3a
main.main()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:0x0, ...)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/http_listener.go:52 +0x549
github.com/couchbase/sync_gateway/rest.(*ServerConfig).serve(0xc8201a4780, 0x7fff5fbff9cd, 0x5, 0x5d046b8, 0xc8202600c0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:580 +0xa3
github.com/couchbase/sync_gateway/rest.RunServer(0xc8201a4780)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:657 +0x949
github.com/couchbase/sync_gateway/rest.ServerMain(0xc800000000)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:696 +0x3a
main.main()
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:
34 +0x133
```

test output & full stack: https://friendpaste.com/5ayPdnaQVAgFdN2Bfszqrl

**Comment by adamcfraser** [comment]
@andrei-baranouski  Are you flushing the db bucket between test runs?

**Comment by andrei-baranouski** [comment]
@adamcfraser I only flush 'db' bucket and don't touch index bucket between test runs

**Comment by adamcfraser** [comment]
We'd expect errors in this case - flushing the db bucket without flushing the index bucket isn't a supported scenario.

**Comment by tleyden** [comment]
@adamcfraser I wonder if there's anything we can add to detect this on startup and fail with a more explicit error message?

```
if databucket empty and indexbucket not empty:
   panic
```

?

**Comment by adamcfraser** [comment]
@tleyden I agree with that - I'll file a ticket for that as part of the 1.3 work.
