### ISSUE TITLE
Crash in sg_accel when taking down another sg_accel in the same cluster

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1502]
Using 1.2.0-59

After running a long perf run (6 hours) with 4IR / 2IW, I ssh'ed into the one of the writters and killed the sg_accel process. Moments later, the second writer crashed with the following panic

```
016/01/22 01:25:00 feed_dcp: rollback, name: data-bucket2805a8354831f9f70ecdf93429094f3b_60cc3e214d86e3fb: vbucketId: 727, rollbackSeq: 0, partition: 727, opaqueValue: , lastSeq: 24538
2016-01-22T01:25:00.707Z WARNING: DCP Rollback request SyncGatewayPIndex - rolling back DCP feed for: vbucketId: 727, rollbackSeq: 0 -- base.(*SyncGatewayPIndex).Rollback() at sgw_pindex.go:338
2016/01/22 01:25:00 feed_dcp: rollback, name: data-bucket2805a8354831f9f70ecdf93429094f3b_60cc3e214d86e3fb: vbucketId: 952, rollbackSeq: 0, partition: 952, opaqueValue: , lastSeq: 24596
2016-01-22T01:25:00.724Z WARNING: DCP Rollback request SyncGatewayPIndex - rolling back DCP feed for: vbucketId: 952, rollbackSeq: 0 -- base.(*SyncGatewayPIndex).Rollback() at sgw_pindex.go:338
2016/01/22 01:25:00 feed_dcp: rollback, name: data-bucket2805a8354831f9f70ecdf93429094f3b_60cc3e214d86e3fb: vbucketId: 722, rollbackSeq: 0, partition: 722, opaqueValue: , lastSeq: 24398
2016-01-22T01:25:00.743Z WARNING: DCP Rollback request SyncGatewayPIndex - rolling back DCP feed for: vbucketId: 722, rollbackSeq: 0 -- base.(*SyncGatewayPIndex).Rollback() at sgw_pindex.go:338
2016-01-22T01:25:01.331Z HTTP:  #4825: GET /_expvar  (ADMIN)
2016-01-22T01:25:01.331Z HTTP: Recording snapshot of current debug variables.
panic: Update attempted to set clock to earlier sequence.  Vb: 496, currentSequence: 24234, newSequence: 20

goroutine 15137828 [running]:
github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).UpdateWithClock(0xc8205e71a0, 0x7f1e28679000, 0xc8286816e0)
        /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:277 +0x2e0
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).writeClockCas(0xc8202fdec0, 0x7f1e28679000, 0xc8286816e0, 0x0, 0x0)
        /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:341 +0x66
github.com/couchbase/sync_gateway/db.(*kvC
```

**Comment by adamcfraser** [comment]
This looks to me like the same issue as #1371 - the non-filler writer is trying to pick up the feeds from the dropped nodes, and is running into #1371 when it does.

**Comment by zgramana** [comment]
Acknowledged this is a duplicate, but keeping open to ensure we get a functional test for this.
