### ISSUE TITLE
What happens in android app when sync-gateway is closed or connection lost

### ISSUE THREAD

**Issue by miltgrin** [couchbase/sync_gateway#1667]
I am testing the connection between an android app and the sync-gateway. If I turnoff the sync gateway after the app has connected (continuous pull and push). I see the following error in the log which seems to be caught in the couchbase lite code and is not reflected back to the "changed" method of the ChangeListener. Is there any way to catch this error in my code to reflect that the sync-gateway is now offline. The status of the replication object doesn't ever seem to get set to OFFLINE. I am running sync-gateway 1.2 along with android couchbase lite 1.2

W/ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@7f107c6: Exception in change tracker
org.apache.http.conn.HttpHostConnectException: Connection to http://192.168.1.89:4984 refused
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:193)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:327)
at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.ConnectException: failed to connect to /192.168.1.89 (port 4984) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:234)
at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
at libcore.io.IoBridge.connect(IoBridge.java:122)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
at java.net.Socket.connect(Socket.java:884)
at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169) 
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124) 
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366) 
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560) 
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492) 
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470) 
at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:327) 
at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228) 
at java.lang.Thread.run(Thread.java:818) 
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:223)
at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
at libcore.io.IoBridge.connect(IoBridge.java:122) 
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
at java.net.Socket.connect(Socket.java:884) 
at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124) 
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149) 
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169) 
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124) 
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366) 
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560) 
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492) 
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470) 
at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:327) 
at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228) 
at java.lang.Thread.run(Thread.java:818)

**Comment by hideki** [comment]
Hi @miltgrin,

In general, the replicator with continuous mode keeps retrying to replicate after 60 sec paused time if replicator encounters the transient error such as network error. If error is a permanent error, the replicator stop immediately.

To catch this type of error, please set `ChangeListener` to observe an event from Replicator. When `changed(ChangeEvent)` method is called, please obtain last error by `ChangeEvent .getError()`.
https://github.com/couchbase/couchbase-lite-java-core/blob/f343e31fd609cb4370801a57626d30506da83c7e/src/main/java/com/couchbase/lite/replicator/Replication.java#L378
https://github.com/couchbase/couchbase-lite-java-core/blob/f343e31fd609cb4370801a57626d30506da83c7e/src/main/java/com/couchbase/lite/replicator/Replication.java#L537
https://github.com/couchbase/couchbase-lite-java-core/blob/f343e31fd609cb4370801a57626d30506da83c7e/src/main/java/com/couchbase/lite/replicator/Replication.java#L529

`OFFLINE` is never set this scenario. `OFFLINE` will be set when Android device is OFFLINE state. For example, Wifi disconnected, etc.

Thanks,
Hideki

**Comment by miltgrin** [comment]
All of that was done in my code.  The error that is appearing in the log is repeated what looks like around every 10 seconds and then every 20 seconds and every 30 seconds .  But is never passing the error out to my ChangeListener. If I do a save operation in couchbase I get the following error multiple time and then eventually the ChangeListener is fired.

03-24 09:25:04.320 13581-14382/com.GRAMedical.PillScheduler2 E/RemoteRequest: io exception.  url: http://192.168.1.89:4984/gramedical/_revs_diff
org.apache.http.conn.HttpHostConnectException: Connection to http://192.168.1.89:4984 refused
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:193)
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
    at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182)
    at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.net.ConnectException: failed to connect to /192.168.1.89 (port 4984) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
    at libcore.io.IoBridge.isConnected(IoBridge.java:234)
    at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
    at libcore.io.IoBridge.connect(IoBridge.java:122)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
    at java.net.Socket.connect(Socket.java:884)
    at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169) 
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124) 
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470) 
    at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182) 
    at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102) 
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 
 Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
    at libcore.io.IoBridge.isConnected(IoBridge.java:223)
    at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
    at libcore.io.IoBridge.connect(IoBridge.java:122) 
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
    at java.net.Socket.connect(Socket.java:884) 
    at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124) 
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149) 
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169) 
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124) 
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492) 
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470) 
    at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182) 
    at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102) 
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818)

**Comment by miltgrin** [comment]
All of that was done in my code. The error that is appearing in the log is
repeated what looks like around every 10 seconds and then every 20 seconds
and every 30 seconds and etc (increasing as time goes on upto every 5 min).
But it is never passing the error out to my ChangeListener. If I do a save
operation in couchbase I get the following error multiple time and then
eventually the ChangeListener is fired.

03-24 09:25:04.320 13581-14382/com.GRAMedical.PillScheduler2
E/RemoteRequest: io exception. url:
http://192.168.1.89:4984/gramedical/_revs_diff
org.apache.http.conn.HttpHostConnectException: Connection to
http://192.168.1.89:4984 refused
at
org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:193)
at
org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
at
org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
at
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
at
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
at
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
at
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
at
com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182)
at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.ConnectException: failed to connect to /192.168.1.89
(port 4984) after 60000ms: isConnected failed: ECONNREFUSED (Connection
refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:234)
at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
at libcore.io.IoBridge.connect(IoBridge.java:122)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
at java.net.Socket.connect(Socket.java:884)
at
org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
at
org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
at
org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
at
org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
at
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
at
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
at
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
at
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
at
com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182)
at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED
(Connection refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:223)
at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
at libcore.io.IoBridge.connect(IoBridge.java:122)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
at java.net.Socket.connect(Socket.java:884)
at
org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
at
org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
at
org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
at
org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
at
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
at
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
at
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
at
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
at
com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182)
at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

**Comment by adamcfraser** [comment]
Closing as this isn't a Sync Gateway issue.  @hideki - if there's actually an underlying SG fix required, reopen with those details.
