### ISSUE TITLE
Test fail on Mac

### ISSUE THREAD

**Issue by johnzeng** [couchbase/sync_gateway#1806]
The first fail is 
`FAIL   github.com/couchbase/sync_gateway/db [build failed]`
and the last one is
`FAIL   github.com/couchbase/sync_gateway/rest`

Also get a panic:

``` go
--- FAIL: TestUserViewQuery (0.18s)
panic: interface conversion: interface is []string, not []interface {} [recovered]
    panic: interface conversion: interface is []string, not []interface {}

goroutine 5487 [running]:
testing.tRunner.func1(0xc821a1f9e0)
    /usr/local/go/src/testing/testing.go:450 +0x171
github.com/couchbase/sync_gateway/db.filterViewResult(0x2, 0xc8211cf470, 0x2, 0x2, 0x502fe68, 0x0, 0x0, 0x0, 0x5665b40, 0xc8202ed800, ...)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/db/design_doc.go:174 +0x2da
github.com/couchbase/sync_gateway/db.(*Database).QueryDesignDoc(0xc820835cc0, 0x4a9e40c, 0x3, 0x4a9e416, 0x3, 0xc820d4ea50, 0x3, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/db/design_doc.go:151 +0x764
github.com/couchbase/sync_gateway/rest.(*handler).handleView(0xc8206d0990, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/view_api.go:104 +0xb2f
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc8206d0990, 0x4bd5e40, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/handler.go:200 +0x7b4
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x566a070, 0xc820d01890, 0xc823975880)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x77
net/http.HandlerFunc.ServeHTTP(0xc821c4d880, 0x566a070, 0xc820d01890, 0xc823975880)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820422e60, 0x566a070, 0xc820d01890, 0xc823975880)
    /Users/john/GoHome/src/github.com/gorilla/mux/mux.go:107 +0x285
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x566a070, 0xc820d01890, 0xc823975880)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/routing.go:273 +0x32d
net/http.HandlerFunc.ServeHTTP(0xc8208354c0, 0x566a070, 0xc820d01890, 0xc823975880)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/couchbase/sync_gateway/rest.(*restTester).send(0xc821f00440, 0xc823975880, 0x5)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/api_test.go:180 +0x1c7
github.com/couchbase/sync_gateway/rest.TestUserViewQuery(0xc821a1f9e0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/view_api_test.go:228 +0x514
testing.tRunner(0xc821a1f9e0, 0x50040d0)
    /usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
    /usr/local/go/src/testing/testing.go:561 +0x86d

```

I tried to connect the sync-gateway to database, but fail with the following stack:

```
2016-05-30T18:56:19.380+08:00 Enabling logging: [CRUD+ REST+ Changes+ Attach+]
2016-05-30T18:56:19.380+08:00 ==== Couchbase Sync Gateway/() ====
2016-05-30T18:56:19.380+08:00 Configured process to allow 5000 open file descriptors
2016-05-30T18:56:19.380+08:00 Opening db /sync_gateway as bucket "sync_gateway", pool "default", server <http://127.0.0.1:8091>
2016-05-30T18:56:19.380+08:00 Opening Couchbase database sync_gateway on <http://127.0.0.1:8091>
_time=2016-05-30T18:56:19.387+08:00 _level=INFO _msg= Trying with selected node 0 
_time=2016-05-30T18:56:19.387+08:00 _level=INFO _msg= Trying with http://127.0.0.1:8091/pools/default/bucketsStreaming/sync_gateway 
_time=2016-05-30T18:56:19.389+08:00 _level=INFO _msg=Got new configuration for bucket sync_gateway 
_time=2016-05-30T18:56:19.426+08:00 _level=INFO _msg= Trying with selected node 0 
panic: runtime error: slice bounds out of range

goroutine 11 [running]:
github.com/couchbase/gomemcached.(*MCRequest).Receive(0xc8202b0080, 0x6501a20, 0xc820206048, 0xc8202982c0, 0x18, 0x18, 0x0, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/gomemcached/mc_req.go:181 +0xbcc
github.com/couchbase/gomemcached/client.(*Client).runFeed(0xc8201f2e10, 0xc82001aae0, 0xc82024d860)
    /Users/john/GoHome/src/github.com/couchbase/gomemcached/client/tap_feed.go:270 +0x149
created by github.com/couchbase/gomemcached/client.(*Client).StartTapFeed
    /Users/john/GoHome/src/github.com/couchbase/gomemcached/client/tap_feed.go:251 +0x422

goroutine 1 [select]:
net/http.(*persistConn).roundTrip(0xc82021a4d0, 0xc820241d20, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1164 +0xb0d
net/http.(*Transport).RoundTrip(0x4f53700, 0xc820218540, 0xaf, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:235 +0x530
net/http.send(0xc820218540, 0x63b4680, 0x4f53700, 0xc8201f4ea0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0x4f5f520, 0xc820218540, 0x5b, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0x4f5f520, 0xc820218540, 0x4b412e0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Do(0x4f5f520, 0xc820218540, 0xc820242e00, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:175 +0x9c
github.com/couchbase/go-couchbase.doHTTPRequest(0xc820218540, 0x63b89a0, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/go-couchbase/pools.go:504 +0x23e
github.com/couchbase/go-couchbase.(*Bucket).ViewCustom(0xc820244540, 0x494d7a0, 0xc, 0x4929fc8, 0x6, 0xc8201f3440, 0x469d940, 0xc820242d60, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/go-couchbase/views.go:169 +0x467
github.com/couchbase/sync_gateway/db.(*DatabaseContext).ComputeSequenceChannelsForPrincipal(0xc8202b4200, 0x65405c0, 0xc820210180, 0x5000104, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/db/crud.go:923 +0x321
github.com/couchbase/sync_gateway/db.(*DatabaseContext).ComputeChannelsForPrincipal(0xc8202b4200, 0x65405c0, 0xc820210180, 0x16, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/db/crud.go:902 +0x57
github.com/couchbase/sync_gateway/auth.(*Authenticator).rebuildChannels(0xc820242ba0, 0x65405c0, 0xc820210180, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/auth/auth.go:152 +0x116
github.com/couchbase/sync_gateway/auth.(*Authenticator).getPrincipal.func1(0xc8201f4de4, 0x4d, 0x4d, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/auth/auth.go:108 +0x245
github.com/couchbase/go-couchbase.(*Bucket).update(0xc820244540, 0x493f6b0, 0xb, 0x0, 0xc820242bc0, 0x0, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/go-couchbase/client.go:940 +0xca
github.com/couchbase/go-couchbase.(*Bucket).Update(0xc820244540, 0x493f6b0, 0xb, 0x0, 0xc820242bc0, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/go-couchbase/client.go:931 +0x55
github.com/couchbase/sync_gateway/base.CouchbaseBucket.Update(0xc820244540, 0xc8201be4e0, 0x15, 0x492b518, 0x7, 0xc8201b55f0, 0xc, 0x0, 0x0, 0x0, ...)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/base/bucket.go:105 +0x67
github.com/couchbase/sync_gateway/base.(*CouchbaseBucket).Update(0xc82005c4d0, 0x493f6b0, 0xb, 0x0, 0xc820242bc0, 0x0, 0x0)
    <autogenerated>:98 +0xf3
github.com/couchbase/sync_gateway/auth.(*Authenticator).getPrincipal(0xc820242ba0, 0x493f6b0, 0xb, 0x4b40060, 0x0, 0x0, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/auth/auth.go:95 +0x127
github.com/couchbase/sync_gateway/auth.(*Authenticator).GetUser(0xc820242ba0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/auth/auth.go:70 +0xe0
github.com/couchbase/sync_gateway/db.(*DatabaseContext).UpdatePrincipal(0xc8202b4200, 0xc820241770, 0xc8201d4240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/db/users.go:91 +0x170
github.com/couchbase/sync_gateway/rest.(*ServerContext).installPrincipals(0xc820187500, 0xc8202b4200, 0xc8201d4150, 0x4930f10, 0x4, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/server_context.go:704 +0x23f
github.com/couchbase/sync_gateway/rest.(*ServerContext)._getOrAddDatabaseFromConfig(0xc820187500, 0xc82010ec30, 0xc820187500, 0x4003dc5, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/server_context.go:493 +0x17ea
github.com/couchbase/sync_gateway/rest.(*ServerContext).getOrAddDatabaseFromConfig(0xc820187500, 0xc82010ec30, 0x4007f00, 0x0, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/server_context.go:254 +0xa4
github.com/couchbase/sync_gateway/rest.(*ServerContext).AddDatabaseFromConfig(0xc820187500, 0xc82010ec30, 0xc8201b1e40, 0x0, 0x0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/server_context.go:595 +0x3c
github.com/couchbase/sync_gateway/rest.RunServer(0xc8201539e0)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/config.go:651 +0x328
github.com/couchbase/sync_gateway/rest.ServerMain(0xc800000000)
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/rest/config.go:710 +0x3a
main.main()
    /Users/john/GoHome/src/github.com/couchbase/sync_gateway/main.go:34 +0x133

```

Let me know what's wrong with my setting, your sync_gateway is really awosome

**Comment by adamcfraser** [comment]
@Misfit-John This looks like one of the known issues when building without dependency pinning - I'd recommend building with dependency pinning as described on the readme:
https://github.com/couchbase/sync_gateway/blob/master/README.md

We really want to get the non-pinned build working, but haven't been able to chase down all the issues in a few of our dependencies yet.

**Comment by johnzeng** [comment]
Great thanks, actually I tried to build it by dependency pinning, but didn't realize that the built one is output to godeps and didn't copied to my GOPATH. It's working now. I also have a question about the synced data, how can I manage them as  a server side database? I can see you just push the sync logs to the sync_gateway data bucket and I can see the values in the document's "description", does it means that I need to add some scripts to sync them to my server side database?

**Comment by johnzeng** [comment]
Forgive me, I make all things clear now. Your product match my requirement very well. Thank you so much.
