### ISSUE TITLE
Sgcollect - Reference to non-existent variable causes sgcollect to crash

### ISSUE THREAD

**Issue by mattcarabine** [couchbase/sync_gateway#1952]
```
Traceback (most recent call last):
  File "<string>", line 500, in <module>
  File "<string>", line 469, in main
AttributeError: Values instance has no attribute 'sync_gateway_executable_path
```

This is because it is using `sync_gateway_executable_path` instead of `sync_gateway_executable`.

sgcollect will crash unless this is fixed.

**Comment by mattcarabine** [comment]
Closed via #1953
