### ISSUE TITLE
sgcollect_info pprof panics on Windows

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2009]
This is not a direct sgcollect_info issue but impacts testing Windows.

I installed golang 1.6.3 on Windows8

When running sgcollect_info the pprof command fail with a panic:

sample pprof commnad:

```
go tool pprof -text -seconds=5 C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://127.0.0.1:4985/_debug/pprof/goroutine
```

output:

```
Fetching profile from http://127.0.0.1:4985/_debug/pprof/goroutine
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x4be866]

goroutine 5 [running]:
panic(0x8d8140, 0xc082006100)
    c:/go/src/runtime/panic.go:481 +0x3f4
cmd/pprof/internal/driver.adjustURL(0xc0820062f0, 0xa, 0x5, 0x2a46d8, 0xc08201c0b8, 0x0, 0x0, 0x0, 0x0, 0x0)
    c:/go/src/cmd/pprof/internal/driver/driver.go:142 +0xbd6
cmd/pprof/internal/driver.grabProfile(0xc0820062f0, 0xa, 0x0, 0x0, 0x0, 0x0, 0xa71980, 0xa71fb0, 0x2a4720, 0xc082007e10, ...)
    c:/go/src/cmd/pprof/internal/driver/driver.go:335 +0x8b
cmd/pprof/internal/driver.PProf.func1(0xc08210a290, 0xc082012900, 0xa71980, 0xa71fb0, 0x2a4720, 0xc082007e10, 0x2a46d8, 0xc08201c0b8, 0xc08210a280, 0xc08210a288, ...)
    c:/go/src/cmd/pprof/internal/driver/driver.go:70 +0x108
created by cmd/pprof/internal/driver.PProf
    c:/go/src/cmd/pprof/internal/driver/driver.go:78 +0x582
```

Reproduced running pprof command manually.

**Comment by ajres** [comment]
Issue was resolved by downgrading to golang 1.5.4

**Comment by tleyden** [comment]
I think that means there is either a bug in the way we are using `go tool`, or a bug in `go tool` itself (in which case we should file a github issue to the go team)

**Comment by adamcfraser** [comment]
@ajres Is it a mismatch between the go version used to build SG, and the version on the machine?

**Comment by ajres** [comment]
Possibly, but I thought we now build with 1.6?

**Comment by tleyden** [comment]
@ajres Looks like we are still building with go 1.5.3.  I think chalking it up to a mismatch is fair enough.
