### ISSUE TITLE
unexpected fault address 0x5fc6438912ff with large-revisions-compact-test

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#2201]
found when investigated regression run against CB 4.6.0-3567 

http://uberjenkins.sc.couchbase.com:8080/job/centos7-mobile-integration-tests-cbserver-sync-gateway-cblitios-liteserv/508/consoleFull (version=1.3.1-6  sg=1.3.1-16, cbs=4.6.0-3567, storage=SQLite)

### Sync Gateway version
1.3.1-16

### Operating system
centos/mac

### Test
https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-large-revisions-compact.js

### Log output
```
2016-12-18T01:49:42.328-08:00 HTTP:  #1266: GET /db/_all_docs
unexpected fault address 0x5fc6438912ff
fatal error: fault
[signal 0xb code=0x1 addr=0x5fc6438912ff pc=0x41187b5]

goroutine 1655 [running]:
runtime.throw(0x49c2af0, 0x5)
	/usr/local/go/1.6.3/go/src/runtime/panic.go:547 +0x90 fp=0xc820b6ae50 sp=0xc820b6ae38
runtime.sigpanic()
	/usr/local/go/1.6.3/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc820b6aea0 sp=0xc820b6ae50
sync/atomic.LoadPointer(0x5fc6438912ff, 0xc820b6aef8)
	/usr/local/go/1.6.3/go/src/sync/atomic/asm_amd64.s:111 +0x5 fp=0xc820b6aea8 sp=0xc820b6aea0
github.com/couchbase/go-couchbase/platform.LoadPointer(0x5fc6438912ff, 0xc820b6aef8)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/go-couchbase/platform/sync.go:113 +0x21 fp=0xc820b6aec0 sp=0xc820b6aea8
github.com/couchbase/go-couchbase.(*Bucket).VBServerMap(0x5fc64389118f, 0xc820b6aef8)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/go-couchbase/pools.go:240 +0x30 fp=0xc820b6aed8 sp=0xc820b6aec0
github.com/couchbase/go-couchbase.(*Bucket).VBHash(0x5fc64389118f, 0x49d6e60, 0xb, 0x1ad71efb)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/go-couchbase/vbmap.go:75 +0x86 fp=0xc820b6aef8 sp=0xc820b6aed8
github.com/couchbase/go-couchbase.(*Bucket).Do(0x5fc64389118f, 0x49d6e60, 0xb, 0xc820b6b1d0, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/go-couchbase/client.go:100 +0x1e8 fp=0xc820b6b160 sp=0xc820b6aef8
github.com/couchbase/go-couchbase.(*Bucket).casNext(0x5fc64389118f, 0x49d6e60, 0xb, 0x0, 0xc820b6b258, 0x49bd600)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/go-couchbase/client.go:968 +0x154 fp=0xc820b6b208 sp=0xc820b6b160
github.com/couchbase/go-couchbase.(*Bucket).update(0x5fc64389118f, 0x49d6e60, 0xb, 0x0, 0xc820b806a0, 0x4012307, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/go-couchbase/client.go:997 +0x86 fp=0xc820b6b2a8 sp=0xc820b6b208
github.com/couchbase/go-couchbase.(*Bucket).Update(0x5fc64389118f, 0x49d6e60, 0xb, 0x0, 0xc820b806a0, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/go-couchbase/client.go:990 +0x55 fp=0xc820b6b2f0 sp=0xc820b6b2a8
github.com/couchbase/sync_gateway/base.CouchbaseBucket.Update(0x5fc64389118f, 0xc820194330, 0x28, 0x49c2028, 0x7, 0xc82016565e, 0x2, 0x0, 0x0, 0x0, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/base/bucket.go:105 +0x67 fp=0xc820b6b330 sp=0xc820b6b2f0
github.com/couchbase/sync_gateway/base.(*CouchbaseBucket).Update(0xc8201e8620, 0x49d6e60, 0xb, 0x0, 0xc820b806a0, 0x0, 0x0)
	<autogenerated>:98 +0xf3 fp=0xc820b6b3d8 sp=0xc820b6b330
github.com/couchbase/sync_gateway/auth.(*Authenticator).getPrincipal(0xc820b80680, 0x49d6e60, 0xb, 0x4c17be8, 0x0, 0x0, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/auth/auth.go:97 +0x127 fp=0xc820b6b450 sp=0xc820b6b3d8
github.com/couchbase/sync_gateway/auth.(*Authenticator).GetUser(0xc820b80680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/auth/auth.go:72 +0xe0 fp=0xc820b6b508 sp=0xc820b6b450
github.com/couchbase/sync_gateway/rest.(*handler).checkAuth(0xc8205c4090, 0xc820200480, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:329 +0xe1b fp=0xc820b6b788 sp=0xc820b6b508
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc8205c4090, 0x4c17fb8, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:184 +0x60d fp=0xc820b6b8d8 sp=0xc820b6b788
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x58c78b0, 0xc8200229c0, 0xc8205f60e0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x77 fp=0xc820b6b938 sp=0xc820b6b8d8
net/http.HandlerFunc.ServeHTTP(0xc82036e520, 0x58c78b0, 0xc8200229c0, 0xc8205f60e0)
	/usr/local/go/1.6.3/go/src/net/http/server.go:1618 +0x3a fp=0xc820b6b958 sp=0xc820b6b938
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8203f8820, 0x58c78b0, 0xc8200229c0, 0xc8205f60e0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/gorilla/mux/mux.go:86 +0x2a6 fp=0xc820b6b9f8 sp=0xc820b6b958
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x58c78b0, 0xc8200229c0, 0xc8205f60e0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:299 +0x32d fp=0xc820b6bb50 sp=0xc820b6b9f8
net/http.HandlerFunc.ServeHTTP(0xc82034b2e0, 0x58c78b0, 0xc8200229c0, 0xc8205f60e0)
	/usr/local/go/1.6.3/go/src/net/http/server.go:1618 +0x3a fp=0xc820b6bb70 sp=0xc820b6bb50
net/http.serverHandler.ServeHTTP(0xc820141580, 0x58c78b0, 0xc8200229c0, 0xc8205f60e0)
	/usr/local/go/1.6.3/go/src/net/http/server.go:2081 +0x19e fp=0xc820b6bbd0 sp=0xc820b6bb70
net/http.(*conn).serve(0xc820020700)
	/usr/local/go/1.6.3/go/src/net/http/server.go:1472 +0xf2e fp=0xc820b6bf98 sp=0xc820b6bbd0
runtime.goexit()
	/usr/local/go/1.6.3/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820b6bfa0 sp=0xc820b6bf98
created by net/http.(*Server).Serve
	/usr/local/go/1.6.3/go/src/net/http/server.go:2137 +0x44e
```

[full stack trace](https://gist.github.com/andreibaranouski/40ec515b06382f6e826cb0cbcffe4c73)

**Comment by andreibaranouski** [comment]
the same issue with [large-revisions-not-continue](https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-large-revisions-not-continuous.js)    http://uberjenkins.sc.couchbase.com:8080/job/centos7-mobile-sync-gateway-android-node-js-tests-cb/499/consoleFull

**Comment by adamcfraser** [comment]
This looks like a failure in go-couchbase when trying to access the server vbucket map.  My guess from an initial review of the code is that the go-couchbase request to:

http://[server]/pools/default/bucketsStreaming/[bucketname]

returned a bad response.  

https://github.com/couchbase/go-couchbase/blob/b84c6246776a69e681f6b0fb910aec36b506177b/streaming.go#L86

This doesn't sound like a Sync Gateway issue to me - either a regression in Couchbase Server, or something in go-couchbase that needs to be updated.

**Comment by sethrosetter** [comment]
@AndreiBaranouski I think this may be due to a go issue with sync gateway 1.3.1. On Friday, @borrrden updated the the mac build agent to OSX Sierra. The default sync gateway version (1.3.1-16) is built with a go version that is incompatible with Sierra. We produced a Sync Gateway version 1.3.1.1-1 to address this Mac only issue. 1.3.1.1-1 and 1.3.1-16 point to the same commit but are built with different go versions. I am unable to reproduce the issue now that I'm using 1.3.1.1-1. Can you try to reproduce in your env using 1.3.1.1-1 and update this? Thanks.

**Comment by andreibaranouski** [comment]
I run the tests with 1.3.1.1-1 and the issue not reproduced. so the issue was related to updated OSX Sierra and tests work fine with 1.3.1.1-1
