### ISSUE TITLE
SGW crashes when running CBL iOS Replication_Tests

### ISSUE THREAD

**Issue by pasin** [couchbase/sync_gateway#2266]
Sync Gateway failed while running CBL iOS Replication_Tests's `test18_PendingDocumentIDs_OnFirstPull`. The test just pulled 2 documents from SGW.

Note that: the same crash also happened on some other tests randomly.

SGW Version: 1.4-55 running on MacOS 10.12.2 (16C67).

Config: https://github.com/couchbase/couchbase-lite-ios/blob/master/Unit-Tests/Server/cbl_unit_tests_ssl.json (See Public database)

Crash Log:

```
2017-01-30T17:01:33.387-08:00 HTTP:  #075: PUT /public/_local/16627078e3f92e21f36527befdab12dbd535f4be
2017-01-30 17:01:33.389968 I | http: panic serving 10.17.1.122:63015: runtime error: invalid memory address or nil pointer dereference
goroutine 2344 [running]:
net/http.(*conn).serve.func1(0xc42227f900)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1491 +0x12a
panic(0x467d1c0, 0xc4200100b0)
	/usr/local/go/1.7.4/go/src/runtime/panic.go:458 +0x243
github.com/couchbaselabs/walrus.(*lolrus).SetVbAndSeq(0xc4200aa090, 0xc42188c960, 0xc425282640, 0x34, 0x4c281c0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:560 +0x55
github.com/couchbaselabs/walrus.(*lolrus).updateDoc(0xc4200aa090, 0xc425282640, 0x34, 0xc42188c960, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:496 +0x12d
github.com/couchbaselabs/walrus.(*lolrus).WriteUpdate(0xc4200aa090, 0xc425282640, 0x34, 0x0, 0xc425a58a60, 0x46ccfa0, 0xc425282601)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:453 +0x1ae
github.com/couchbaselabs/walrus.(*lolrus).Update(0xc4200aa090, 0xc425282640, 0x34, 0x0, 0xc42188c930, 0x473420d, 0x1)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:466 +0x8d
github.com/couchbase/sync_gateway/db.(*Database).putSpecial(0xc424646620, 0x4735b17, 0x5, 0xc421de59b3, 0x28, 0x0, 0x0, 0xc42188c900, 0xc420e11440, 0xc420e11440, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:74 +0x31d
github.com/couchbase/sync_gateway/db.(*Database).PutSpecial(0xc424646620, 0x4735b17, 0x5, 0xc421de59b3, 0x28, 0xc42188c900, 0x46e2560, 0x0, 0xc42820b928, 0x30)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:82 +0x133
github.com/couchbase/sync_gateway/rest.(*handler).handlePutLocalDoc(0xc4209cdc20, 0xc42188c8a0, 0x4736201)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/doc_api.go:343 +0x110
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc4209cdc20, 0x47ea578, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:215 +0x331
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x4ac3dc0, 0xc421bcc9c0, 0xc425bb3ef0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x80
net/http.HandlerFunc.ServeHTTP(0xc42037c4e0, 0x4ac3dc0, 0xc421bcc9c0, 0xc425bb3ef0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420316820, 0x4ac3dc0, 0xc421bcc9c0, 0xc425bb3ef0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/gorilla/mux/mux.go:86 +0x204
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x4ac3dc0, 0xc421bcc9c0, 0xc425bb3ef0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:295 +0x66f
net/http.HandlerFunc.ServeHTTP(0xc4203d1460, 0x4ac3dc0, 0xc421bcc9c0, 0xc425bb3ef0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4203a7a00, 0x4ac3dc0, 0xc421bcc9c0, 0xc425bb3ef0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42227f900, 0x4ac4900, 0xc425282040)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/1.7.4/go/src/net/http/server.go:2293 +0x44d
2017-01-30T17:01:37.617-08:00 HTTP:  #076: PUT /public/_local/16627078e3f92e21f36527befdab12dbd535f4be
2017-01-30 17:01:37.620923 I | http: panic serving 10.17.1.122:63016: runtime error: invalid memory address or nil pointer dereference
goroutine 2335 [running]:
net/http.(*conn).serve.func1(0xc420749880)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1491 +0x12a
panic(0x467d1c0, 0xc4200100b0)
	/usr/local/go/1.7.4/go/src/runtime/panic.go:458 +0x243
github.com/couchbaselabs/walrus.(*lolrus).SetVbAndSeq(0xc4200aa090, 0xc424f874d0, 0xc426695dc0, 0x34, 0x4c281c0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:560 +0x55
github.com/couchbaselabs/walrus.(*lolrus).updateDoc(0xc4200aa090, 0xc426695dc0, 0x34, 0xc424f874d0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:496 +0x12d
github.com/couchbaselabs/walrus.(*lolrus).WriteUpdate(0xc4200aa090, 0xc426695dc0, 0x34, 0x0, 0xc4267c4d20, 0x46ccfa0, 0xc426695d01)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:453 +0x1ae
github.com/couchbaselabs/walrus.(*lolrus).Update(0xc4200aa090, 0xc426695dc0, 0x34, 0x0, 0xc424f874a0, 0x473420d, 0x1)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:466 +0x8d
github.com/couchbase/sync_gateway/db.(*Database).putSpecial(0xc420751d20, 0x4735b17, 0x5, 0xc42525f553, 0x28, 0x0, 0x0, 0xc424f87470, 0xc4207ecb40, 0xc4207ecb40, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:74 +0x31d
github.com/couchbase/sync_gateway/db.(*Database).PutSpecial(0xc420751d20, 0x4735b17, 0x5, 0xc42525f553, 0x28, 0xc424f87470, 0x46e2560, 0x0, 0xc4249d5988, 0x30)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:82 +0x133
github.com/couchbase/sync_gateway/rest.(*handler).handlePutLocalDoc(0xc42676f950, 0xc424f87410, 0x4736201)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/doc_api.go:343 +0x110
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc42676f950, 0x47ea578, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:215 +0x331
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x4ac3dc0, 0xc420aca750, 0xc421909a40)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x80
net/http.HandlerFunc.ServeHTTP(0xc42037c4e0, 0x4ac3dc0, 0xc420aca750, 0xc421909a40)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420316820, 0x4ac3dc0, 0xc420aca750, 0xc421909a40)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/gorilla/mux/mux.go:86 +0x204
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x4ac3dc0, 0xc420aca750, 0xc421909a40)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:295 +0x66f
net/http.HandlerFunc.ServeHTTP(0xc4203d1460, 0x4ac3dc0, 0xc420aca750, 0xc421909a40)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4203a7a00, 0x4ac3dc0, 0xc420aca750, 0xc421909a40)
	/usr/local/go/1.7.4/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420749880, 0x4ac4900, 0xc426695c40)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/1.7.4/go/src/net/http/server.go:2293 +0x44d
2017-01-30T17:01:38.532-08:00 HTTP:  #077: PUT /public/_local/c501bfd938362cc734116738e2b8bb8c5a3778ca
2017-01-30 17:01:38.537107 I | http: panic serving 10.17.1.122:63017: runtime error: invalid memory address or nil pointer dereference
goroutine 2257 [running]:
net/http.(*conn).serve.func1(0xc421a18a80)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1491 +0x12a
panic(0x467d1c0, 0xc4200100b0)
	/usr/local/go/1.7.4/go/src/runtime/panic.go:458 +0x243
github.com/couchbaselabs/walrus.(*lolrus).SetVbAndSeq(0xc4200aa090, 0xc42188d620, 0xc425282f00, 0x34, 0x4c281c0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:560 +0x55
github.com/couchbaselabs/walrus.(*lolrus).updateDoc(0xc4200aa090, 0xc425282f00, 0x34, 0xc42188d620, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:496 +0x12d
github.com/couchbaselabs/walrus.(*lolrus).WriteUpdate(0xc4200aa090, 0xc425282f00, 0x34, 0x0, 0xc425a58f50, 0x46ccfa0, 0xc425282f01)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:453 +0x1ae
github.com/couchbaselabs/walrus.(*lolrus).Update(0xc4200aa090, 0xc425282f00, 0x34, 0x0, 0xc42188d5f0, 0x473420d, 0x1)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:466 +0x8d
github.com/couchbase/sync_gateway/db.(*Database).putSpecial(0xc4259b4d20, 0x4735b17, 0x5, 0xc421de5fa3, 0x28, 0x0, 0x0, 0xc42188d5c0, 0xc4218c07e0, 0xc4218c07e0, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:74 +0x31d
github.com/couchbase/sync_gateway/db.(*Database).PutSpecial(0xc4259b4d20, 0x4735b17, 0x5, 0xc421de5fa3, 0x28, 0xc42188d5c0, 0x46e2560, 0x0, 0xc4249d9988, 0x30)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:82 +0x133
github.com/couchbase/sync_gateway/rest.(*handler).handlePutLocalDoc(0xc4209cddd0, 0xc42188d560, 0x4736201)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/doc_api.go:343 +0x110
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc4209cddd0, 0x47ea578, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:215 +0x331
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x4ac3dc0, 0xc421bcd110, 0xc426022ff0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x80
net/http.HandlerFunc.ServeHTTP(0xc42037c4e0, 0x4ac3dc0, 0xc421bcd110, 0xc426022ff0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420316820, 0x4ac3dc0, 0xc421bcd110, 0xc426022ff0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/gorilla/mux/mux.go:86 +0x204
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x4ac3dc0, 0xc421bcd110, 0xc426022ff0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:295 +0x66f
net/http.HandlerFunc.ServeHTTP(0xc4203d1460, 0x4ac3dc0, 0xc421bcd110, 0xc426022ff0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4203a7a00, 0x4ac3dc0, 0xc421bcd110, 0xc426022ff0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc421a18a80, 0x4ac4900, 0xc425282d40)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/1.7.4/go/src/net/http/server.go:2293 +0x44d
2017-01-30T17:01:42.720-08:00 HTTP:  #078: PUT /public/_local/c501bfd938362cc734116738e2b8bb8c5a3778ca
2017-01-30 17:01:42.724801 I | http: panic serving 10.17.1.122:63018: runtime error: invalid memory address or nil pointer dereference
goroutine 2354 [running]:
net/http.(*conn).serve.func1(0xc421a19700)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1491 +0x12a
panic(0x467d1c0, 0xc4200100b0)
	/usr/local/go/1.7.4/go/src/runtime/panic.go:458 +0x243
github.com/couchbaselabs/walrus.(*lolrus).SetVbAndSeq(0xc4200aa090, 0xc42098c3c0, 0xc425283980, 0x34, 0x4c281c0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:560 +0x55
github.com/couchbaselabs/walrus.(*lolrus).updateDoc(0xc4200aa090, 0xc425283980, 0x34, 0xc42098c3c0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:496 +0x12d
github.com/couchbaselabs/walrus.(*lolrus).WriteUpdate(0xc4200aa090, 0xc425283980, 0x34, 0x0, 0xc426786510, 0x46ccfa0, 0xc425283901)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:453 +0x1ae
github.com/couchbaselabs/walrus.(*lolrus).Update(0xc4200aa090, 0xc425283980, 0x34, 0x0, 0xc42098c390, 0x473420d, 0x1)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:466 +0x8d
github.com/couchbase/sync_gateway/db.(*Database).putSpecial(0xc425095ea0, 0x4735b17, 0x5, 0xc4219d65b3, 0x28, 0x0, 0x0, 0xc42098c360, 0xc421749d40, 0xc421749d40, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:74 +0x31d
github.com/couchbase/sync_gateway/db.(*Database).PutSpecial(0xc425095ea0, 0x4735b17, 0x5, 0xc4219d65b3, 0x28, 0xc42098c360, 0x46e2560, 0x0, 0xc4249d9988, 0x30)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:82 +0x133
github.com/couchbase/sync_gateway/rest.(*handler).handlePutLocalDoc(0xc420cb8000, 0xc42098c300, 0x4736201)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/doc_api.go:343 +0x110
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc420cb8000, 0x47ea578, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:215 +0x331
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x4ac3dc0, 0xc421bcd860, 0xc4209880f0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x80
net/http.HandlerFunc.ServeHTTP(0xc42037c4e0, 0x4ac3dc0, 0xc421bcd860, 0xc4209880f0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420316820, 0x4ac3dc0, 0xc421bcd860, 0xc4209880f0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/gorilla/mux/mux.go:86 +0x204
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x4ac3dc0, 0xc421bcd860, 0xc4209880f0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:295 +0x66f
net/http.HandlerFunc.ServeHTTP(0xc4203d1460, 0x4ac3dc0, 0xc421bcd860, 0xc4209880f0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4203a7a00, 0x4ac3dc0, 0xc421bcd860, 0xc4209880f0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc421a19700, 0x4ac4900, 0xc4252837c0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/1.7.4/go/src/net/http/server.go:2293 +0x44d
2017-01-30T17:01:45.725-08:00 HTTP:  #079: PUT /public/_local/16627078e3f92e21f36527befdab12dbd535f4be
2017-01-30 17:01:45.728990 I | http: panic serving 10.17.1.122:63019: runtime error: invalid memory address or nil pointer dereference
goroutine 1255 [running]:
net/http.(*conn).serve.func1(0xc420138780)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1491 +0x12a
panic(0x467d1c0, 0xc4200100b0)
	/usr/local/go/1.7.4/go/src/runtime/panic.go:458 +0x243
github.com/couchbaselabs/walrus.(*lolrus).SetVbAndSeq(0xc4200aa090, 0xc42688efc0, 0xc4255cc480, 0x34, 0x4c281c0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:560 +0x55
github.com/couchbaselabs/walrus.(*lolrus).updateDoc(0xc4200aa090, 0xc4255cc480, 0x34, 0xc42688efc0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:496 +0x12d
github.com/couchbaselabs/walrus.(*lolrus).WriteUpdate(0xc4200aa090, 0xc4255cc480, 0x34, 0x0, 0xc427dcbd90, 0x46ccfa0, 0xc4255cc401)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:453 +0x1ae
github.com/couchbaselabs/walrus.(*lolrus).Update(0xc4200aa090, 0xc4255cc480, 0x34, 0x0, 0xc42688ef90, 0x473420d, 0x1)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbaselabs/walrus/crud.go:466 +0x8d
github.com/couchbase/sync_gateway/db.(*Database).putSpecial(0xc4247d41c0, 0x4735b17, 0x5, 0xc4248dd6e3, 0x28, 0x0, 0x0, 0xc42688ef60, 0xc42193db00, 0xc42193db00, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:74 +0x31d
github.com/couchbase/sync_gateway/db.(*Database).PutSpecial(0xc4247d41c0, 0x4735b17, 0x5, 0xc4248dd6e3, 0x28, 0xc42688ef60, 0x46e2560, 0x0, 0xc427d2b988, 0x30)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/db/special_docs.go:82 +0x133
github.com/couchbase/sync_gateway/rest.(*handler).handlePutLocalDoc(0xc424f4a1b0, 0xc42688ef00, 0x4736201)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/doc_api.go:343 +0x110
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc424f4a1b0, 0x47ea578, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:215 +0x331
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x4ac3dc0, 0xc42517e5b0, 0xc4265a5950)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x80
net/http.HandlerFunc.ServeHTTP(0xc42037c4e0, 0x4ac3dc0, 0xc42517e5b0, 0xc4265a5950)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420316820, 0x4ac3dc0, 0xc42517e5b0, 0xc4265a5950)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/gorilla/mux/mux.go:86 +0x204
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x4ac3dc0, 0xc42517e5b0, 0xc4265a5950)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:295 +0x66f
net/http.HandlerFunc.ServeHTTP(0xc4203d1460, 0x4ac3dc0, 0xc42517e5b0, 0xc4265a5950)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4203a7a00, 0x4ac3dc0, 0xc42517e5b0, 0xc4265a5950)
	/usr/local/go/1.7.4/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420138780, 0x4ac4900, 0xc4255cc280)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/1.7.4/go/src/net/http/server.go:2293 +0x44d
```

**Comment by pasin** [comment]
CC: @sethrosetter

**Comment by tleyden** [comment]
@sethrosetter do you run the functional tests against a walrus bucket?  It might be helpful to debug if this was reproducible in a functional test

**Comment by sethrosetter** [comment]
@tleyden We no longer run the functional tests against walrus. They are all backed by a Couchbase server

**Comment by tleyden** [comment]
Note to self: sg logs with extra output while reproducing locally

https://gist.github.com/tleyden/18cfab21ea9fe2788ce4b0cb40199af8

**Comment by tleyden** [comment]
It looks like this is not actually a sync gateway bug, but it is an artifact of using [stored walrus files](https://github.com/couchbase/couchbase-lite-ios/blob/master/Unit-Tests/Server/cbl_unit_tests_ssl.json#L9), which doesn't seem to be robust against [changes to the  walrus codebase](https://github.com/couchbaselabs/walrus/commit/1f4834e6697e75599ffe95d11ba7e92221f55cb6#diff-de8c2aa44adf9e0edb3e34092151159dR71).  

If I change the config to [remove all references to the stored walrus buckets](https://gist.github.com/tleyden/58b1ba31794a015fbf3984b766480904) then I'm no longer able to reproduce the issue by running the `test_06_Puller_Authenticate` test, which was failing every time for me.   Here are the [new SG logs after removing all usages of stored walrus database](https://gist.github.com/tleyden/04972c2c3698eebce784bd74ec9f00dd)

OTOH, I think it's possible to make some minor changes to the loading-a-bucket-from-a-file code which will make it more robust against loading existing stored walrus buckets, which will prevent this error.

**Comment by tleyden** [comment]
Walrus and SG Pr's are up:

https://github.com/couchbase/sync_gateway/pull/2281

Now the test is passing every time, even when using the persisted bucket data

New sg logs: https://gist.github.com/tleyden/9d06a0bf952e768ce279606d1d8dfed7
