### ISSUE TITLE
SGW crashed when running iOS continuous pull replicator

### ISSUE THREAD

**Issue by pasin** [couchbase/sync_gateway#2295]
The crash log is different from https://github.com/couchbase/sync_gateway/issues/2266. See below.

```
2017-02-08 17:36:59.944643 I | http: panic serving [::1]:64929: interface conversion: *rest.LoggingTeeResponseWriter is not http.Hijacker: missing method Hijack
goroutine 262 [running]:
```

### Sync Gateway version
Couchbase Sync Gateway/1.4(72;4f3edda)

### Operating system
MacOS 10.12.2 (16C67)

### Config file
https://github.com/couchbase/couchbase-lite-ios/blob/master/Unit-Tests/Server/cbl_unit_tests_ssl.json

### Log output

```
Pasins-MacBook-Pro:Server pasin$ ./sync_gateway cbl_unit_tests_ssl.json 
2017-02-08T17:36:44.384+07:00 Enabling logging: [HTTP+]
2017-02-08T17:36:44.384+07:00 ==== Couchbase Sync Gateway/1.4(72;4f3edda) ====
2017-02-08T17:36:44.384+07:00 Configured process to allow 5000 open file descriptors
2017-02-08T17:36:44.384+07:00 Opening db /beer as bucket "beer", pool "default", server <walrus:walrus_data>
2017-02-08T17:36:44.384+07:00 Opening Walrus database beer on <walrus:walrus_data>
2017-02-08T17:36:44.385+07:00     Reset guest user to config
2017-02-08T17:36:44.385+07:00 Opening db /public as bucket "public_ssl", pool "default", server <walrus:walrus_data>
2017-02-08T17:36:44.385+07:00 Opening Walrus database public_ssl on <walrus:walrus_data>
2017-02-08T17:36:44.386+07:00     Reset guest user to config
2017-02-08T17:36:44.386+07:00 Opening db /cbl_auth_test as bucket "cbl_auth_test_ssl", pool "default", server <walrus:walrus_data>
2017-02-08T17:36:44.386+07:00 Opening Walrus database cbl_auth_test_ssl on <walrus:walrus_data>
2017-02-08T17:36:44.387+07:00 Using default sync function 'channel(doc.channels)' for database "cbl_auth_test"
2017-02-08T17:36:44.387+07:00 Opening db /cbl_replicator_pushpull as bucket "cbl_replicator_pushpull", pool "default", server <walrus:>
2017-02-08T17:36:44.387+07:00 Opening Walrus database cbl_replicator_pushpull on <walrus:>
2017-02-08T17:36:44.387+07:00 Using default sync function 'channel(doc.channels)' for database "cbl_replicator_pushpull"
2017-02-08T17:36:44.387+07:00     Reset guest user to config
2017-02-08T17:36:44.387+07:00 Opening db /cbl_replicator_scratch as bucket "cbl_replicator_scratch", pool "default", server <walrus:>
2017-02-08T17:36:44.387+07:00 Opening Walrus database cbl_replicator_scratch on <walrus:>
2017-02-08T17:36:44.387+07:00 Using default sync function 'channel(doc.channels)' for database "cbl_replicator_scratch"
2017-02-08T17:36:44.387+07:00     Reset guest user to config
2017-02-08T17:36:44.387+07:00 Opening db /cbl_replicator_encoding as bucket "cbl_replicator_encoding", pool "default", server <walrus:>
2017-02-08T17:36:44.387+07:00 Opening Walrus database cbl_replicator_encoding on <walrus:>
2017-02-08T17:36:44.388+07:00 Using default sync function 'channel(doc.channels)' for database "cbl_replicator_encoding"
2017-02-08T17:36:44.388+07:00     Reset guest user to config
2017-02-08T17:36:44.388+07:00 Opening db /cbl_replicator_cookies as bucket "cbl_replicator_cookies", pool "default", server <walrus:>
2017-02-08T17:36:44.388+07:00 Opening Walrus database cbl_replicator_cookies on <walrus:>
2017-02-08T17:36:44.388+07:00 Using default sync function 'channel(doc.channels)' for database "cbl_replicator_cookies"
2017-02-08T17:36:44.388+07:00     Reset guest user to config
2017-02-08T17:36:44.388+07:00 Opening db /attach_test as bucket "attach_test", pool "default", server <walrus:walrus_data>
2017-02-08T17:36:44.388+07:00 Opening Walrus database attach_test on <walrus:walrus_data>
2017-02-08T17:36:44.431+07:00     Reset guest user to config
2017-02-08T17:36:44.431+07:00 Starting admin server on :4995
2017-02-08T17:36:44.434+07:00 Starting server on :4994 ...
2017-02-08T17:36:44.434+07:00 HTTP: Protocols enabled: [http/1.1] on :4995
2017-02-08T17:36:44.435+07:00 HTTP: Protocols enabled: [http/1.1] on :4994
2017-02-08T17:36:59.145+07:00 HTTP:  #001: POST /cbl_replicator_scratch/_flush  (ADMIN)
2017-02-08T17:36:59.145+07:00 Closing db /cbl_replicator_scratch (bucket "cbl_replicator_scratch")
2017-02-08T17:36:59.145+07:00 Opening db /cbl_replicator_scratch as bucket "cbl_replicator_scratch", pool "default", server <walrus:>
2017-02-08T17:36:59.145+07:00 Opening Walrus database cbl_replicator_scratch on <walrus:>
2017-02-08T17:36:59.146+07:00 Using default sync function 'channel(doc.channels)' for database "cbl_replicator_scratch"
2017-02-08T17:36:59.146+07:00     Reset guest user to config
2017-02-08T17:36:59.146+07:00 HTTP+: #001:     --> 200   (0.5 ms)
2017-02-08T17:36:59.285+07:00 HTTP:  #002: POST /cbl_replicator_scratch/_revs_diff
2017-02-08T17:36:59.285+07:00 HTTP:  #003: POST /cbl_replicator_scratch/_revs_diff
2017-02-08T17:36:59.286+07:00 HTTP+: #003:     --> 200   (41.7 ms)
2017-02-08T17:36:59.288+07:00 HTTP+: #002:     --> 200   (103.5 ms)
2017-02-08T17:36:59.290+07:00 HTTP:  #004: POST /cbl_replicator_scratch/_bulk_docs
2017-02-08T17:36:59.291+07:00 HTTP+: #004:     --> 201   (0.6 ms)
2017-02-08T17:36:59.301+07:00 HTTP:  #005: POST /cbl_replicator_scratch/_bulk_docs
2017-02-08T17:36:59.305+07:00 HTTP+: #005:     --> 201   (4.7 ms)
2017-02-08T17:36:59.308+07:00 HTTP:  #006: PUT /cbl_replicator_scratch/_local/6dece0b78e0cc22e056507dddbf3f5b4308bc88f
2017-02-08T17:36:59.308+07:00 HTTP+: #006:     --> 201   (0.2 ms)
2017-02-08T17:36:59.337+07:00 HTTP:  #007: POST /cbl_replicator_scratch/_changes?feed=normal&heartbeat=300000&style=all_docs
2017-02-08T17:36:59.338+07:00 HTTP+: #007:     --> 200 OK  (0.0 ms)
2017-02-08T17:36:59.410+07:00 HTTP:  #008: POST /cbl_replicator_scratch/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=103
2017-02-08T17:36:59.886+07:00 HTTP:  #009: PUT /cbl_replicator_scratch/_local/20c8358a50428800b54b6f5fd07df517905cdfae
2017-02-08T17:36:59.886+07:00 HTTP+: #009:     --> 201   (0.2 ms)
2017-02-08T17:36:59.919+07:00 HTTP:  #010: GET /cbl_replicator_scratch/_local/20c8358a50428800b54b6f5fd07df517905cdfae
2017-02-08T17:36:59.920+07:00 HTTP+: #010:     --> 200   (0.6 ms)
2017-02-08T17:36:59.944+07:00 HTTP:  #011: GET /cbl_replicator_scratch/_changes?feed=websocket
2017-02-08 17:36:59.944643 I | http: panic serving [::1]:64929: interface conversion: *rest.LoggingTeeResponseWriter is not http.Hijacker: missing method Hijack
goroutine 262 [running]:
net/http.(*conn).serve.func1(0xc420d8ff80)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1491 +0x12a
panic(0x4687f00, 0xc42467fa80)
	/usr/local/go/1.7.4/go/src/runtime/panic.go:458 +0x243
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x47f2530, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/golang.org/x/net/websocket/server.go:74 +0xd2
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x47f2530, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/golang.org/x/net/websocket/server.go:70 +0x75
github.com/couchbase/sync_gateway/rest.(*handler).sendContinuousChangesByWebSocket(0xc424a6ec60, 0xc424887020, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:751 +0x1f6
github.com/couchbase/sync_gateway/rest.(*handler).handleChanges(0xc424a6ec60, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:290 +0x93c
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc424a6ec60, 0x47f2300, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:215 +0x331
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x4acddc0, 0xc424c23380, 0xc42029b4a0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x80
net/http.HandlerFunc.ServeHTTP(0xc420358ac0, 0x4acddc0, 0xc424c23380, 0xc42029b4a0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42016a820, 0x4acddc0, 0xc424c23380, 0xc42029b4a0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/gorilla/mux/mux.go:86 +0x204
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x4acddc0, 0xc424c23380, 0xc42029b4a0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:295 +0x66f
net/http.HandlerFunc.ServeHTTP(0xc4244f9d80, 0x4acddc0, 0xc424c23380, 0xc42029b4a0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc42450ed80, 0x4acddc0, 0xc424c23380, 0xc42029b4a0)
	/usr/local/go/1.7.4/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420d8ff80, 0x4ace900, 0xc42467f940)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/1.7.4/go/src/net/http/server.go:2293 +0x44d
2017-02-08T17:37:02.018+07:00 HTTP:  #012: GET /cbl_replicator_scratch/_changes?feed=websocket
2017-02-08 17:37:02.018589 I | http: panic serving [::1]:64930: interface conversion: *rest.LoggingTeeResponseWriter is not http.Hijacker: missing method Hijack
goroutine 234 [running]:
net/http.(*conn).serve.func1(0xc42450e000)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1491 +0x12a
panic(0x4687f00, 0xc424668940)
	/usr/local/go/1.7.4/go/src/runtime/panic.go:458 +0x243
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x47f2530, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/golang.org/x/net/websocket/server.go:74 +0xd2
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x47f2530, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/golang.org/x/net/websocket/server.go:70 +0x75
github.com/couchbase/sync_gateway/rest.(*handler).sendContinuousChangesByWebSocket(0xc4246c01b0, 0xc424878f90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:751 +0x1f6
github.com/couchbase/sync_gateway/rest.(*handler).handleChanges(0xc4246c01b0, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:290 +0x93c
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc4246c01b0, 0x47f2300, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:215 +0x331
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x4acddc0, 0xc4203768f0, 0xc4200d4e10)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x80
net/http.HandlerFunc.ServeHTTP(0xc420358ac0, 0x4acddc0, 0xc4203768f0, 0xc4200d4e10)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42016a820, 0x4acddc0, 0xc4203768f0, 0xc4200d4e10)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/gorilla/mux/mux.go:86 +0x204
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x4acddc0, 0xc4203768f0, 0xc4200d4e10)
	/Users/jenkins/jenkins/workspace/sgw-unix-build@2/1.4/community/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:295 +0x66f
net/http.HandlerFunc.ServeHTTP(0xc4244f9d80, 0x4acddc0, 0xc4203768f0, 0xc4200d4e10)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc42450ed80, 0x4acddc0, 0xc4203768f0, 0xc4200d4e10)
	/usr/local/go/1.7.4/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42450e000, 0x4ace900, 0xc424668780)
	/usr/local/go/1.7.4/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/1.7.4/go/src/net/http/server.go:2293 +0x44d
```

### Expected behavior
SGW shouldn't crash.

### Actual behavior
SGW crashed.

### Steps to reproduce
Run iOS test_03_Puller_Continuous.

**Comment by tleyden** [comment]
@pasin looking into it

**Comment by tleyden** [comment]
I just pushed `feature/issue_2295_logtee` to github -- can you try rebuilding with that branch and let me know if it works around your problem?

Deeper fix still needed

**Comment by adamcfraser** [comment]
Reviewed w/ @tleyden.  For 1.4, going to make the req/response logging a dev-only feature (enable with a code flag) - both to avoid this type of issue, but also around concerns about keeping secure data out of the logs.
