### ISSUE TITLE
SG panics when admin port is used for BLIP replication

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2549]
### Sync Gateway version
1.4.2-364  

### Operating system
CentOS-7.2.

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "databases":{
        "db":{
            "server":"http://<CBS_IP>:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "unsupported": {"replicator_2": true}
        }
    }
}
```
### Expected behavior
Replication should work fine.

### Steps to reproduce
1. Started a continuous replication between SG and LiteCoreServ with `{"source": "blip://<SG_IP>:4985/db", "continuous": true, "target": "ls_db"}`
```
POST http://<LiteCoreServ_IP>:52000/_replicate 200
{u'ok': True, u'session_id': 1}
```
2. Wait for replication to go idle for id = 1
3. Poll active_tasks constantly to check for idle status

### Actual behavior
1. Upon using the admin port for replication, LiteCore gets a Go exception from SG.
-> Backtrace is given below.

### Log output
```
2017-05-10T20:47:48.812Z HTTP:  #105: GET /db/_blipsync  (ADMIN)
2017-05-10 20:47:48.812547 I | http: panic serving 10.17.0.22:58590: runtime error: invalid memory address or nil pointer dereference
goroutine 157 [running]:
net/http.(*conn).serve.func1(0xc42038e280)
        /usr/local/go/1.7.4/go/src/net/http/server.go:1491 +0x12a
panic(0xade200, 0xc420010060)
        /usr/local/go/1.7.4/go/src/runtime/panic.go:458 +0x243
github.com/couchbase/sync_gateway/rest.(*handler).handleBLIPSync(0xc4208a45a0, 0xc4203aea80, 0xc420114d48)
        /home/couchbase/jenkins/workspace/sgw-unix-build/1.4.2/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/blip_sync.go:61 +0x122
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc4208a45a0, 0xc5daf0, 0x0, 0x0)
        /home/couchbase/jenkins/workspace/sgw-unix-build/1.4.2/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:221 +0x2c1
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0xf63dc0, 0xc4203729c0, 0xc4205163c0)
        /home/couchbase/jenkins/workspace/sgw-unix-build/1.4.2/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:96 +0x80
net/http.HandlerFunc.ServeHTTP(0xc4203ae620, 0xf63dc0, 0xc4203729c0, 0xc4205163c0)
        /usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202fd680, 0xf63dc0, 0xc4203729c0, 0xc4205163c0)
        /home/couchbase/jenkins/workspace/sgw-unix-build/1.4.2/enterprise/godeps/src/github.com/gorilla/mux/mux.go:86 +0x204
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0xf63dc0, 0xc4203729c0, 0xc4205163c0)
        /home/couchbase/jenkins/workspace/sgw-unix-build/1.4.2/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:297 +0x66f
net/http.HandlerFunc.ServeHTTP(0xc420361360, 0xf63dc0, 0xc4203729c0, 0xc4205163c0)
        /usr/local/go/1.7.4/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc42048d500, 0xf63dc0, 0xc4203729c0, 0xc4205163c0)
        /usr/local/go/1.7.4/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42038e280, 0xf64980, 0xc420417e00)
        /usr/local/go/1.7.4/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/1.7.4/go/src/net/http/server.go:2293 +0x44d
```

**Comment by snej** [comment]
Null deref at rest/blip_sync.go:61 — my bad. I'll look into it.
