### ISSUE TITLE
Sporadically failing unit test: TestShadowerPattern

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2560]
In [cen7-sync-gateway-functional-tests-topology-specific-di/421](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-di/421/consoleFull) which is on the `feature/remove_gocb_hybrid` branch

```
FAIL: TestShadowerPattern (0.00s)\npanic: runtime error: invalid memory address or nil pointer dereference [recovered]\n\tpanic: runtime error: invalid memory address or nil pointer 
dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x51d22e]\n\ngoroutine 1871 [running]:\npanic(0x9294e0, 0xc420010090)\n\t/usr/local/go/src/runtime/panic.go:500
 +0x1a1\ntesting.tRunner.func1(0xc421b12900)\n\t/usr/local/go/src/testing/testing.go:579 +0x25d\npanic(0x9294e0, 0xc420010090)\n\t/usr/local/go/src/runtime/panic.go:458 +0x243\ngithub.com/couchbase/sync_gateway/db.TestShadowerPattern(0xc421b12900)\n\t/home/centos/godeps/src/github.com/couchbase/sync_gateway/db/shadower_test.go:241 
+0x6ee\ntesting.tRunner(0xc421b12900, 0xa639b8)\n\t/usr/local/go/src/testing/testing.go:610 +0x81\ncreated by testing.(*T).Run\n\t/usr/local/go/src/testing/testing.go:646 +0x2ec\nFAIL\tgithub.com/couchbase/sync_gateway/db\t16.691s
```

**Comment by tleyden** [comment]
Per sporadic failing, re-running above functional test passed in [cen7-sync-gateway-functional-tests-topology-specific-di/422](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-di/422/)

**Comment by tleyden** [comment]
I tried to repro this locally in a retry loop against an actual couchbase server, and it's passing 10/10 times.  Closing.
