### ISSUE TITLE
Ability to run unit tests against Couchbase Server bucket

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2561]
## Problem

- Even if we add XATTR support to Walrus, there are upstream bugs that won't get caught
- The functional tests are time consuming to run during normal development 

## Steps

- [x] Add environment variables to toggle between running against walrus vs a bucket
- [x] Create and flush the bucket after every test (slow -- but useful to have to isolate residue issues)
- [x] All SG tests passing against walrus
- [ ] All SG tests passing against cb bucket
- [ ] All SGA tests passing against walrus
- [ ] All SGA tests passing against cb bucket

## Phase 2

- [ ] Batch the the bucket creation and flushing into "suites" to things up considerably
- [ ] Add Jenkins Automation

**Comment by tleyden** [comment]
Current blocker:

```
go test -v -run "^(TestChannelCacheBufferingWithUserDoc|TestLowSequenceHandling)$" github.com/couchbase/sync_gateway/db
```

Fails with https://gist.github.com/tleyden/88006e230f1a5ced62f317afe5144a9b

**Comment by tleyden** [comment]
I filed a ticket against cbdatasource, since it shouldn't be panicking in that situation https://issues.couchbase.com/browse/MB-24500  (though I think there might be issues in the tests that's triggering it somehow)

**Comment by tleyden** [comment]
https://github.com/couchbase/sync_gateway/issues/2561#issuecomment-303209128 is fixed in 98778a50d5f5342d1c047157600cec4c325f97d3 by bumping to later versions of go-memcached and go-couchbase

**Comment by tleyden** [comment]
Current blocker:

```
SG_TEST_BACKING_STORE=Couchbase go test -v  github.com/couchbase/sync_gateway/db
```

Gets into an "infinite DCP rollback loop": https://gist.github.com/tleyden/41d1d49041f25ffe5b38302d121a2753

**Comment by tleyden** [comment]
In 9fca81031b50f980a120109d6c6b902564411476 addded the option to recreate the bucket between tests (as opposed to flushing -- in case that was causing https://github.com/couchbase/sync_gateway/issues/2561#issuecomment-303222195), and now I'm running into:

```
SG_TEST_BACKING_STORE=Couchbase go test -v  github.com/couchbase/sync_gateway/db
...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1277ad]

goroutine 418 [running]:
panic(0x52fe40, 0xc4200140f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbase/sync_gateway/db.NewDatabaseContext.func2(0x5c7994, 0x7, 0x86cd20, 0xc420382320)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/database.go:256 +0x3ed
github.com/couchbase/sync_gateway/base.(*DCPReceiver).OnError(0xc4203568d0, 0x86cd20, 0xc420382320)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/dcp_feed.go:126 +0xca
github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).worker.func5(0xc4201a48a0, 0xc420226000, 0xc4203d6600, 0xf, 0xc4204fbd80, 0x1d, 0xc4203f4e40, 0xc4203d6a28, 0xc4203f5b30, 0xc4201a47e0, ...)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1059 +0x1313
created by github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).worker
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1184 +0x563
exit status 2

```

If I run that failing test on it's own via:

```
SG_TEST_BACKING_STORE=Couchbase go test -v -run "^TestLowSequenceHandlingAcrossChannels$" github.com/couchbase/sync_gateway/db
```

it passes.  So it looks like it might be related to some previous test code that hasn't been gc'd and is still hanging around after the test finishes, and this callback kicks in and the causes the error.  It does look like that code should have a null-check however.

**Comment by tleyden** [comment]
I added a fix for https://github.com/couchbase/sync_gateway/issues/2561#issuecomment-303227021 in a13ceb864133c3b1b3f033714850d1676dbc43cb

Now when running:

```
SG_TEST_BACKING_STORE=Couchbase go test -v  github.com/couchbase/sync_gateway/db
```

I'm seeing:

```
WARNING: DCP Rollback request - rolling back DCP feed for: vbucketId: 52, rollbackSeq: 0 -- base.(*DCPReceiver).Rollback() at dcp_feed.go:204
GOCB 14:49:26.390984 memdclient.go:94: Failed to shut down client connection (close tcp [::1]:50715->[::1]:11210: use of closed network connection)
GOCB 14:49:26.391000 memdpipeline.go:266: Pipeline Client `0xc4210276a0` preparing for new client loop
2017-05-22T14:49:26.391-07:00 PANIC: Unimplemented method: Append() -- base.CouchbaseBucketGoCB.Append() at bucket_gocb.go:733
GOCB 14:49:26.391010 memdpipeline.go:273: Pipeline Client `0xc4210276a0` is on parent: 0xc421640730
GOCB 14:49:26.391015 agent.go:276: CCCP Looper starting.
--- FAIL: TestChannelIndexSimpleReadSingle (8.23s)
GOCB 14:49:26.391016 memdpipeline.go:279: Pipeline Client `0xc4210276a0` retrieving new client connection
2017-05-22T14:49:26.391-07:00 WARNING: DCP Rollback request - rolling back DCP feed for: vbucketId: 15, rollbackSeq: 0 -- base.(*DCPReceiver).Rollback() at dcp_feed.go:204
panic: Unimplemented method: Append() [recovered]
	panic: Unimplemented method: Append()

goroutine 8337 [running]:
panic(0x50bfa0, 0xc42015acb0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc421818000)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x50bfa0, 0xc42015acb0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/couchbase/sync_gateway/base.LogPanic(0x5d49b7, 0x1e, 0x0, 0x0, 0x0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/logging.go:449 +0x115
github.com/couchbase/sync_gateway/base.CouchbaseBucketGoCB.Append(0xc42153b7a0, 0x5cf37f, 0x15, 0x0, 0x0, 0x5c932a, 0xa, 0x0, 0x0, 0x86e960, ...)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/bucket_gocb.go:733 +0x51
github.com/couchbase/sync_gateway/base.(*CouchbaseBucketGoCB).Append(0xc42153b830, 0xc4210276e0, 0x1d, 0xc4207a0254, 0x8, 0x40, 0xc4210276c0, 0xc40872b44b)
	<autogenerated>:470 +0xce
github.com/couchbase/sync_gateway/db.(*channelIndexTest).writeToCache(0xc421640870, 0xb1, 0x8, 0xc420cfc000, 0xc421640870)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/channel_index_test.go:131 +0xd3
github.com/couchbase/sync_gateway/db.(*channelIndexTest).addToCache(0xc421640870, 0xb1, 0xb1, 0xc)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/channel_index_test.go:123 +0x70
github.com/couchbase/sync_gateway/db.TestChannelIndexSimpleReadSingle(0xc421818000)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/channel_index_test.go:478 +0xc8
testing.tRunner(0xc421818000, 0x66b718)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
```

The error is happening even when running that test individually:

```
SG_TEST_BACKING_STORE=Couchbase go test -v -run "^TestChannelIndexSimpleReadSingle$" github.com/couchbase/sync_gateway/db
```

**Comment by tleyden** [comment]
Worked around https://github.com/couchbase/sync_gateway/issues/2561#issuecomment-303230078 in 8e8ee7af6c0bb956943c17804fe79172306d3159 by skipping 3 tests

**Comment by tleyden** [comment]
New issue.  Running all the `github.com/couchbase/sync_gateway/db` tests is giving errors:

```
2017-05-22T15:07:11.963-07:00 WARNING: changeCache: Error unmarshaling doc "_index::channel_9::0::50pj": json: cannot unmarshal string into Go value of type db.documentRoot -- db.(*changeCache).DocChanged.func1() at change_cache.go:361
2017-05-22T15:07:11.963-07:00 WARNING: DCP Rollback request - rolling back DCP feed for: vbucketId: 32, rollbackSeq: 0 -- base.(*DCPReceiver).Rollback() at dcp_feed.go:204
2017-05-22T15:07:11.963-07:00 WARNING: changeCache: Error unmarshaling doc "_index::channel_9::0::50pj": json: cannot unmarshal string into Go value of type db.documentRoot -- db.(*changeCache).DocChanged.func1() at change_cache.go:361
2017-05-22T15:07:11.963-07:00 WARNING: changeCache: Error unmarshaling doc "_index::channel_9::0::cztk": json: cannot unmarshal string into Go value of type db.documentRoot -- db.(*changeCache).DocChanged.func1() at change_cache.go:361
2017-05-22T15:07:11.963-07:00 WARNING: changeCache: Error unmarshaling doc "_index::channel_9::0::fm1y": json: cannot unmarshal string into Go value of type db.documentRoot -- db.(*changeCache).DocChanged.func1() at change_cache.go:361
```

(running the TestChannelIndexBulkGet10 test on it's own works fine)

**Comment by tleyden** [comment]
@adamcfraser I'm noticing a failure and wondering if you have any insight:

```
$ SG_TEST_USE_XATTRS=true SG_TEST_BACKING_STORE=Couchbase SG_TEST_COUCHBASE_SERVER_URL=http://192.168.33.10:8091 go test -v -run  "^TestDeleteDocumentAndUpdateXATTR$" github.com/couchbase/sync_gateway/...
?   	github.com/couchbase/sync_gateway	[no test files]
PASS
ok  	github.com/couchbase/sync_gateway/auth	0.010s
=== RUN   TestDeleteDocumentAndUpdateXATTR
2017-05-31T14:54:12.376-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://192.168.33.10:8091> as user "test_data_bucket"
2017/05/31 14:54:12 MutateInEx error: invalid arguments

	bucket_gocb_test.go:1241
	assert.Equals(t, retrievedXattr["seq"], float64(123))

	expected: 123
	     got: <nil>
2017/05/31 14:54:12 value: map[], xattr: map[]
2017/05/31 14:54:12 MutateInEx cas: 0
--- FAIL: TestDeleteDocumentAndUpdateXATTR (3.95s)
```

I'm running Couchbase Server Enterprise Edition 5.0.0 build 2958, how can I find out if it contains the fix for https://issues.couchbase.com/browse/MB-24098?

**Comment by adamcfraser** [comment]
@tleyden We haven't done uptake of https://issues.couchbase.com/browse/MB-24098 yet, so that may be why this test is failing.

**Comment by tleyden** [comment]
Note to self .. this error might be worth looking into:

In http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/51/console:

```
2017-05-31T16:59:00.014-07:00 Cache:     #749 ==> channel "*"
2017-05-31T16:59:00.014-07:00 Cache: Received #750 after   0ms ("doc-750" / "1-a")
2017-05-31T16:59:00.014-07:00 Cache:     #750 ==> channel "ABC"
2017-05-31T16:59:00.014-07:00 Cache:     #750 ==> channel "*"
2017-05-31T16:59:00.114-07:00 waitForSequence(750) took 100 ms
2017-05-31T16:59:00.114-07:00 Cache: getCachedChanges("ABC", 0) --> 600 changes valid from #151
2017-05-31T16:59:00.114-07:00 Cache:   Querying 'channels' view for "ABC" (start=#1, end=#151, limit=0)
2017-05-31T16:59:00.670-07:00 Cache:     Got no rows from view for "ABC"
2017-05-31T16:59:00.670-07:00 Cache: GetChangesInChannel("ABC") --> 600 rows

	change_cache_test.go:905
	assert.Equals(t, len(changes), 750)	

	expected: 750
	     got: 600
--- FAIL: TestChannelCacheSize (3.13s)
```

Locally it passed against CBS 4.x:

```
SG_TEST_BACKING_STORE=Couchbase SG_TEST_COUCHBASE_SERVER_URL=http://localhost:8091 go test -v -run  "^TestChannelCacheSize$" github.com/couchbase/sync_gateway/...
2017-05-31T17:15:33.763-07:00 waitForSequence(750) took 100 ms
2017-05-31T17:15:33.763-07:00 Cache: getCachedChanges("ABC", 0) --> 600 changes valid from #151
2017-05-31T17:15:33.764-07:00 Cache:   Querying 'channels' view for "ABC" (start=#1, end=#151, limit=0)
2017-05-31T17:15:33.972-07:00 Cache:     Got 150 rows from view for "ABC": #1 ... #150
2017-05-31T17:15:33.972-07:00 changes_view: Query took 208.064421ms to return 150 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"ABC", 0x1}, "endkey":[]interface {}{"ABC", 0x97}}
2017-05-31T17:15:33.972-07:00 Cache: GetChangesInChannel("ABC") --> 750 rows
--- PASS: TestChannelCacheSize (5.58s)
```

**Comment by tleyden** [comment]
Same result locally with Couchbase Server 5.x

**Comment by tleyden** [comment]
I can't even repro it running on the jenkins slave:

```
[root@s61502-cnt7 build-sync-gateway]# SG_TEST_BACKING_STORE=Couchbase SG_TEST_COUCHBASE_SERVER_URL=http://s61903cnt72.sc.couchbase.com:8091 go test -v -run  "^TestChannelCacheSize$" github.com/couchbase/sync_gateway/...
017-05-31T17:53:00.492-07:00 Cache:     #750 ==> channel "ABC"
2017-05-31T17:53:00.492-07:00 Cache:     #750 ==> channel "*"
2017-05-31T17:53:00.590-07:00 waitForSequence(750) took 100 ms
2017-05-31T17:53:00.591-07:00 Cache: getCachedChanges("ABC", 0) --> 600 changes valid from #151
2017-05-31T17:53:00.591-07:00 Cache:   Querying 'channels' view for "ABC" (start=#1, end=#151, limit=0)
2017-05-31T17:53:01.171-07:00 Cache:     Got 150 rows from view for "ABC": #1 ... #150
2017-05-31T17:53:01.171-07:00 changes_view: Query took 580.660049ms to return 150 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"ABC", 0x1}, "endkey":[]interface {}{"ABC", 0x97}}
2017-05-31T17:53:01.171-07:00 Cache: GetChangesInChannel("ABC") --> 750 rows
--- PASS: TestChannelCacheSize (4.23s)
```

**Comment by tleyden** [comment]
I can repro locally if I enable `SG_TEST_USE_XATTRS`:

```
SG_TEST_USE_XATTRS=true SG_TEST_BACKING_STORE=Couchbase SG_TEST_COUCHBASE_SERVER_URL=http://192.168.33.10:8091 go test -v -run  "^TestChannelCacheSize$" github.com/couchbase/sync_gateway/...
2017-05-31T20:25:26.044-07:00 Cache: getCachedChanges("ABC", 0) --> 600 changes valid from #151
2017-05-31T20:25:26.044-07:00 Cache:   Querying 'channels' view for "ABC" (start=#1, end=#151, limit=0)
2017-05-31T20:25:26.481-07:00 Cache:     Got no rows from view for "ABC"
2017-05-31T20:25:26.481-07:00 Cache: GetChangesInChannel("ABC") --> 600 rows

	change_cache_test.go:905
	assert.Equals(t, len(changes), 750)

	expected: 750
	     got: 600
```
