### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by nbrys** [couchbase/sync_gateway#2590]
### Log output
```
May 19 08:41:51 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:41:51.908Z Enabling logging: [REST]
May 19 08:41:51 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:41:51.909Z ==== Couchbase Sync Gateway/1.5.0(381;6a1598b) ====
May 19 08:41:51 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:41:51.909Z requestedSoftFDLimit >= currentHardFdLimit (5000 >= 4096) capping at 4096
May 19 08:41:51 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:41:51.909Z Configured process to allow 4096 open file descriptors
May 19 08:41:51 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:41:51.909Z Opening db /company-name as bucket "company-name", pool "default", server <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091>
May 19 08:41:51 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:41:51.909Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:42:19 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:42:19.946Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:42:47 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:42:47.983Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:43:16 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:43:16.041Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:43:44 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:43:44.109Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:44:12 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:44:12.451Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:44:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:44:40.643Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:45:08 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:45:08.995Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:45:37 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:45:37.683Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:46:06 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:46:06.995Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:46:37 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:46:37.587Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:47:10 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:47:10.739Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:47:49 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:47:49.011Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:48:37 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:48:37.523Z GoCBGoCouchbaseHybrid Opening Couchbase database company-name on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "company-name"
May 19 08:49:05 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:49:05.555Z WARNING: RetryLoop for Attempt to connect to bucket : company-name giving up after 14 attempts -- base.RetryLoop() at util.go:295
May 19 08:49:05 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:49:05.555Z FATAL: Error opening database: 502  Unable to connect to Couchbase Server (connection refused). Please ensure it is running and reachable at the configured host and port.  Detailed error: failed to connect to any of the specified hosts -- rest.RunServer() at config.go:760
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:39.182Z Enabling logging: [REST]
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:39.183Z ==== Couchbase Sync Gateway/1.5.0(381;6a1598b) ====
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:39.183Z requestedSoftFDLimit >= currentHardFdLimit (5000 >= 4096) capping at 4096
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:39.183Z Configured process to allow 4096 open file descriptors
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:39.183Z Opening db /tst-customer as bucket "tst-customer", pool "default", server <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091>
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:39.183Z GoCBGoCouchbaseHybrid Opening Couchbase database tst-customer on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "tst-customer"
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:39.815+00:00 _level=INFO _msg= Trying with selected node 0 
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:39.816+00:00 _level=INFO _msg= Trying with http://10.0.30.37:8091/pools/default/bucketsStreaming/tst-customer 
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:39.846+00:00 _level=INFO _msg= Trying with selected node 1 
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:39.923+00:00 _level=INFO _msg=Using plain authentication for user tst-customer 
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:39.924+00:00 _level=INFO _msg=Using plain authentication for user tst-customer 
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:39.924+00:00 _level=INFO _msg=Using plain authentication for user tst-customer 
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:39.971Z Opening db /customer as bucket "customer", pool "default", server <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091>
May 19 08:57:39 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:39.972Z GoCBGoCouchbaseHybrid Opening Couchbase database customer on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "customer"
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.146+00:00 _level=INFO _msg=Got new configuration for bucket tst-customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.169+00:00 _level=INFO _msg= Trying with selected node 1 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.171+00:00 _level=INFO _msg= Trying with http://10.0.31.148:8091/pools/default/bucketsStreaming/customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.186+00:00 _level=INFO _msg=Using plain authentication for user tst-customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.186+00:00 _level=INFO _msg=Using plain authentication for user tst-customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.187+00:00 _level=INFO _msg=Using plain authentication for user tst-customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:40.226Z WARNING: changeCache: Error unmarshaling doc "_sync:user:joske": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:480
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:40.232Z WARNING: changeCache: Error unmarshaling doc "_sync:user:joske2": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:480
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.234+00:00 _level=INFO _msg=Got new configuration for bucket customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.241+00:00 _level=INFO _msg= Trying with selected node 1 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.280+00:00 _level=INFO _msg=Using plain authentication for user customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.280+00:00 _level=INFO _msg=Using plain authentication for user customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.281+00:00 _level=INFO _msg=Using plain authentication for user customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:40.350Z Opening db /customer2 as bucket "customer2", pool "default", server <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091>
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 2017-05-19T08:57:40.350Z GoCBGoCouchbaseHybrid Opening Couchbase database customer2 on <http://internal-mobile-staging-couchbase-01-764859514.eu-west-1.elb.amazonaws.com:8091> as user "customer2"
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.380+00:00 _level=INFO _msg=Using plain authentication for user customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.380+00:00 _level=INFO _msg=Using plain authentication for user customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: _time=2017-05-19T08:57:40.381+00:00 _level=INFO _msg=Using plain authentication for user customer 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: panic: runtime error: slice bounds out of range
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: 
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: goroutine 162 [running]:
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: panic(0xade200, 0xc420010100)
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: #011/usr/local/go/1.7.4/go/src/runtime/panic.go:500 +0x1a1
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).handleRecv(0xc420178f00, 0xc420318600, 0xc4203b4d50, 0xc42005ab40, 0x0, 0x0)
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: #011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.5.0/community/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1346 +0xbb6
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).worker.func5(0xc4203186c0, 0xc420178f00, 0xc420419a20, 0x11, 0xc4205a81a0, 0x1c, 0xc4203b4a80, 0xc42038f708, 0xc4203b4d50, 0xc420318600, ...)
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: #011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.5.0/community/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1162 +0xf11
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: created by github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).worker
May 19 08:57:40 ip-172-31-36-137.eu-west-1.compute.internal sync-gateway-stderr: #011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.5.0/community/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1184 +0x563
```
### Expected behavior
Sync gateaway starts normally

### Actual behavior
Sync gateway crashes. 

When we start a sync gateway 1.4.0 on the same instance with the same config, sync gateway starts

**Comment by nbrys** [comment]
Port 8091 is open to our DB and works for 1.4.0

**Comment by adamcfraser** [comment]
What build of Couchbase Server are you running?

**Comment by nbrys** [comment]
We are running 4.0.0 CE

**Comment by adamcfraser** [comment]
Looking into it.  In the meantime, can you see if setting "feed_type":"TAP" in your database config avoids the problem?

**Comment by nbrys** [comment]
Hi, It seems like the default feed_type is TAP. We don't  overwrite that in our config file.

**Comment by adamcfraser** [comment]
The default feed type is changed to DCP in Sync Gateway 1.5.

**Comment by tleyden** [comment]
@nbrys I ran into the same error here: https://github.com/couchbase/sync_gateway/issues/2561#issuecomment-303209128

We'll push a fix for that to the master branch soon
