### ISSUE TITLE
Remove test_integration.sh and allow running test.sh against Couchbase Server (fix interference issues)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2612]
After https://github.com/couchbase/sync_gateway/pull/2604 and https://github.com/couchbase/sync_gateway/issues/2561, it's now possible to run the Sync Gateway unit test suite against an actual Couchbase Server bucket (as opposed to Walrus), however there are known issues when trying to run the suite via `test.sh`.  

It seems that there is interference/residue from previous tests that can cause problem with currently running tests.  This may involve sync gateway callback functions running in memory that do not get removed after the test run completes.  Another possible problem mentioned in https://github.com/couchbase/sync_gateway/pull/2604#discussion_r119754986:

> Maybe worth noting regarding the test interference - I think that ServerContext.Close() includes some async shutdown processing (like the feed runner goroutine) that might be a problem.

The current workaround is `test_integration.sh`, which runs each test in a separate process, which eliminated most types of interference, at the cost of slowing things down.

Action items:

- [ ] Attempt to run full `test.sh` against Couchbase Server and identify failing tests
- [ ] Find root cause and fix failing tests until they all pass -- most likely there are a few common causes that cause many of the tests to fail 
- [ ] Update the [build-sync-gateway jenkins job](http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/) to run `test.sh` instead of `test_integration.sh`

**Comment by tleyden** [comment]
Revisiting this as part of https://github.com/couchbase/sync_gateway/pull/2880

Trying to run this, I noticed a failure in this Jenkins job run

http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage/4/console

```
2017-09-07 14:49:44.250869 I | Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
--- FAIL: TestChannelCacheBufferingWithUserDoc (4.05s)
panic: WriteDirectWithKey() cannot be used in tests that are xattr enabled [recovered]
	panic: WriteDirectWithKey() cannot be used in tests that are xattr enabled

goroutine 542 [running]:
panic(0xb34480, 0xc4218d3330)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420c3a180)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0xb34480, 0xc4218d3330)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/couchbase/sync_gateway/db.WriteDirectWithKey(0xc42029dce0, 0xc4218d3288, 0x5, 0xc421a5fea8, 0x1, 0x1, 0x2)
	/var/jenkins/workspace/build-sync-gateway-w-coverage/godeps/src/github.com/couchbase/sync_gateway/db/change_cache_test.go:217 +0x47c
github.com/couchbase/sync_gateway/db.WriteDirect(0xc42029dce0, 0xc421a5fea8, 0x1, 0x1, 0x2)
	/var/jenkins/workspace/build-sync-gateway-w-coverage/godeps/src/github.com/couchbase/sync_gateway/db/change_cache_test.go:206 +0xf9
github.com/couchbase/sync_gateway/db.TestChannelCacheBufferingWithUserDoc(0xc420c3a180)
	/var/jenkins/workspace/build-sync-gateway-w-coverage/godeps/src/github.com/couchbase/sync_gateway/db/change_cache_test.go:278 +0x191

```

Looks like TestChannelCacheBufferingWithUserDoc isn't normally run since it's not in the hardcoded list, and it needs to be skipped if XATTRS=true

**Comment by tleyden** [comment]
Another failure:

http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage/3/console

```
--- FAIL: TestResponseEncoding (1.38s)
panic: Error trying to empty bucket.  Spec: {Server:http://integration-cbs.sc.couchbase.com:8091 PoolName: BucketName:test_data_bucket FeedType: Auth:{Username:test_data_bucket Password:password BucketName:test_data_bucket} CouchbaseDriver:GoCBCustomSGTranscoder MaxNumRetries:0 InitialRetrySleepTimeMS:0 UseXattrs:false ViewQueryTimeoutSecs:<nil>}.  err: {"_":"Flush failed with unexpected error. Check server logs for details."} [recovered]
	panic: Error trying to empty bucket.  Spec: {Server:http://integration-cbs.sc.couchbase.com:8091 PoolName: BucketName:test_data_bucket FeedType: Auth:{Username:test_data_bucket Password:password BucketName:test_data_bucket} CouchbaseDriver:GoCBCustomSGTranscoder MaxNumRetries:0 InitialRetrySleepTimeMS:0 UseXattrs:false ViewQueryTimeoutSecs:<nil>}.  err: {"_":"Flush failed with unexpected error. Check server logs for details."}

goroutine 24622 [running]:
panic(0xb8a000, 0xc4252fbd30)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4242563c0)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0xb8a000, 0xc4252fbd30)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/couchbase/sync_gateway/base.GetBucketOrPanicCommon(0x0, 0xb, 0xffffffffffffffff)
	github.com/couchbase/sync_gateway/base/_obj/util_testing.go:127 +0x738
github.com/couchbase/sync_gateway/base.GetBucketOrPanic(0xc4267ca400, 0xf0)
	github.com/couchbase/sync_gateway/base/_obj/util_testing.go:40 +0x38
github.com/couchbase/sync_gateway/rest.(*RestTester).Bucket(0xc424be4000, 0x1, 0xc420ebb330)
	github.com/couchbase/sync_gateway/rest/_test/_obj_test/utilities_testing.go:33 +0x98
github.com/couchbase/sync_gateway/rest.(*RestTester).ServerContext(0xc424be4000, 0xc420ebb330)
	github.com/couchbase/sync_gateway/rest/_test/_obj_test/utilities_testing.go:130 +0x39
github.com/couchbase/sync_gateway/rest.(*RestTester).Send(0xc424be4000, 0xc4267ca4b0, 0xca855d)
	github.com/couchbase/sync_gateway/rest/_test/_obj_test/utilities_testing.go:222 +0x15b
github.com/couchbase/sync_gateway/rest.(*RestTester).SendRequest(0xc424be4000, 0xc9d533, 0x3, 0xca855d, 0xf, 0xc4201ba400, 0x180c, 0xc428915d47)
	github.com/couchbase/sync_gateway/rest/_test/_obj_test/utilities_testing.go:193 +0x87
github.com/couchbase/sync_gateway/rest.TestResponseEncoding(0xc4242563c0)
	/var/jenkins/workspace/build-sync-gateway-w-coverage/godeps/src/github.com/couchbase/sync_gateway/rest/api_test.go:1228 +0x1d0
```

Haven't looked into this one, just logging it

**Comment by tleyden** [comment]
In http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway-w-coverage/8/console, it failed with:

```
2017-09-07T16:16:33.844-07:00 Changes: simple changes cannot get Close Notifier from ResponseWriter
2017-09-07T16:16:33.844-07:00 Changes+: MultiChangesFeed: channels expand to "!:1,alpha:1" ...   (to user1)
2017-09-07T16:16:33.844-07:00 Changes+: Grant for channel [alpha] is after the current sequence - skipped for this iteration.  Grant:[1] Current:[0]   (to user1)
2017-09-07T16:16:33.844-07:00 Changes+: Grant for channel [!] is after the current sequence - skipped for this iteration.  Grant:[1] Current:[0]   (to user1)
2017-09-07T16:16:33.844-07:00 Changes+: Found sequence later than stable sequence: stable:[0] entry:[1] (_user/user1)
2017-09-07T16:16:33.844-07:00 Changes: MultiChangesFeed done   (to user1)
2017-09-07 16:16:33.844336 I | _changes looks like: {"results":[
],
"last_seq":"0"}

	api_test.go:1797
	assert.Equals(t, len(changes.Results), 50)	

	expected: 50
	     got: 0
--- FAIL: TestUserJoiningPopulatedChannel (5.68s)
	assert.go:31: 
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 26174 [running]:
panic(0xbcec40, 0xc4200160f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4287c7c80)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0xbcec40, 0xc4200160f0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/couchbase/sync_gateway/rest.TestUserJoiningPopulatedChannel(0xc4287c7c80)
```

**Comment by tleyden** [comment]
This should have been closed out with the PR's getting merged
