### ISSUE TITLE
Sync Gateway panics on certain configs

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2643]
### Sync Gateway version
This is an **older** version of SG: 1.3

### Operating system
Centos

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "databases":{
        "db":{
            {{ autoimport }}
            "unsupported": {
                {{ xattrs }}
            },
            "server":"{{ server_scheme }}://{{ couchbase_server_primary_node }}:{{ server_port }}",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password"
        }
    }
}
```

### Log output

```
017-06-12T21:52:42.827Z ==== Couchbase Sync Gateway/1.3.1(16;f18e833) ====
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e78ea]

goroutine 1 [running]:
github.com/couchbase/sync_gateway/rest.(*ServerContext)._getOrAddDatabaseFromConfig(0xc82013ad80, 0xc82000c460, 0xc82013ad00, 0x15acc20, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:473 +0x1f9a
github.com/couchbase/sync_gateway/rest.(*ServerContext).getOrAddDatabaseFromConfig(0xc82013ad80, 0xc82000c460, 0x406a00, 0x0, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:254 +0xa4
github.com/couchbase/sync_gateway/rest.(*ServerContext).AddDatabaseFromConfig(0xc82013ad80, 0xc82000c460, 0xc8200fde40, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:650 +0x3c
github.com/couchbase/sync_gateway/rest.RunServer(0xc8201386c0)
	/
```

### Expected behavior
Emitted a warning if it didn't recognize certain config sections

### Actual behavior
Panic

### Steps to reproduce
1.  See https://github.com/couchbaselabs/mobile-testkit/issues/1240

### Workaround

Update the config to:

```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "databases":{
        "db":{
            "server":"http://ec2-34-224-8-25.compute-1.amazonaws.com:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password"
        }
    }
}
```

to remove the problematic `unsupported` and/or `autoimport` section

**Comment by adamcfraser** [comment]
This is fixed on master as part of the refactoring of the unsupported handling in https://github.com/couchbase/sync_gateway/commit/61ed91ac1e48fcdae7fdf19b84023d37758e9e4e
