### ISSUE TITLE
TestChangesLoopingWhenLowSequence: Sequence 6 never showed up! (unit tests against couchbase bucket)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2666]
### Sync Gateway version
Sg commit: f37de25ce1b0cc8bc9646d6266bb965d6ca88190 (equivalent to master commit: https://github.com/couchbase/sync_gateway/commit/a1cc33c0e4f56875d36580d895e7939b04bc89bf)

### Log output
```
2017-06-22T11:57:15.395-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:}") count=2
2017-06-22T11:57:16.187-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:bernard}") count=3
2017-06-22T11:57:16.187-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{*}") count=4
2017-06-22T11:57:16.188-07:00 Debug: Waiting for sequence: 6
--- FAIL: TestChangesLoopingWhenLowSequence (8.92s)
panic: changeCache: Sequence 6 never showed up! [recovered]
	panic: changeCache: Sequence 6 never showed up!

goroutine 6 [running]:
panic(0xb13d60, 0xc420456a90)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42008a780)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0xb13d60, 0xc420456a90)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/couchbase/sync_gateway/db.(*changeCache).waitForSequenceWithMissing(0xc42020e5a0, 0x6)
	/var/jenkins/workspace/build-sync-gateway/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:316 +0x19e
github.com/couchbase/sync_gateway/db.(*DatabaseContext).WaitForSequenceWithMissing(0xc420098500, 0x6, 0x1, 0x1)
	/var/jenkins/workspace/build-sync-gateway/godeps/src/github.com/couchbase/sync_gateway/db/changes.go:727 +0xe8
github.com/couchbase/sync_gateway/rest.TestChangesLoopingWhenLowSequence(0xc42008a780)
	/var/jenkins/workspace/build-sync-gateway/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api_test.go:560 +0x470
```

### Steps to reproduce
1. Run this jenkins job: http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/103/parameters/

**Comment by tleyden** [comment]
I'm re-running to determine if it was a sporadic failure or not.

**Comment by tleyden** [comment]
I got the same result in http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/107/consoleFull, so it seems to happen consistently.

**Comment by tleyden** [comment]
I went back a commit on the master branch and retested https://github.com/couchbase/sync_gateway/commit/129ad6de0dc5779d51f6bcdb787402a3ea1c46e9, and it's still failing with the same error:

http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/114/console

So it's not related to the [Compact obsolete tombstones from accel's channel index ](https://github.com/couchbase/sync_gateway/commit/a1cc33c0e4f56875d36580d895e7939b04bc89bf) commit

**Comment by tleyden** [comment]
It looks like this is a regression introduced in 6f3a2a8777ebfec7ed6af6c623192bce46aecf51.  

When I switch to 6f3a2a8777ebfec7ed6af6c623192bce46aecf51, I'm able to repro via:

```
$ SG_TEST_BACKING_STORE=Couchbase SG_TEST_USE_XATTRS=true SG_TEST_COUCHBASE_SERVER_URL=http://s61903cnt72.sc.couchbase.com:8091  ./test.sh -run ^TestChangesLoopingWhenLowSequence$
```

Output:

https://gist.github.com/tleyden/df9287b2f31215fec94e68e61ba289fd

But if I switch to the previous commit on master, 0ac67a56c9976ae6dbdf87531e9f3d9ccb3a7564, the same test passes:

https://gist.github.com/tleyden/7952c04af6fe077a545ad2a9e9b1d373

**Comment by tleyden** [comment]
The change in https://github.com/couchbase/sync_gateway/commit/6f3a2a8777ebfec7ed6af6c623192bce46aecf51 changes timing in xattr

Before:

slower: 2 kv ops

Now:

faster: single kv op

Could be mismatch in test expectation in terms of timing

**Comment by tleyden** [comment]
After [debugging pretty deep into this](https://gist.github.com/tleyden/cb970ad4a3f8c39b7e4daf48acba6503), I just realized I'm testing against 5.0.0-2958, whereas the functional tests are currently running against 5.0.0-3158

As a first step I will try to repro against 5.0.0-3158 to see if it's still an issue there.

**Comment by tleyden** [comment]
I was able to repro on 5.0.0-3158 and 5.0.0-3193, so it's not related to the couchbase server version.

**Comment by tleyden** [comment]
I reverted back to commit 0ac67a56c9976ae6dbdf87531e9f3d9ccb3a7564 and applied the [debug output](https://gist.github.com/tleyden/cc5fe2d585c50e337901d51cfc480b7f)

**Comment by tleyden** [comment]
After digging into that, it looks like the only reason this test was passing before https://github.com/couchbase/sync_gateway/commit/6f3a2a8777ebfec7ed6af6c623192bce46aecf51 is that the tests weren't actually enabling xattrs, because the flag was not making it all the way down to the db config.  That was fixed here:

https://github.com/couchbase/sync_gateway/commit/6f3a2a8777ebfec7ed6af6c623192bce46aecf51#diff-6c1acdfa8f9a41007512af6d0c4fbf97

Which then surfaced the issue.

**Comment by tleyden** [comment]
I think I found the issue.  

Even though the test is configured with xattr=true, the test is [writing the docs with _sync metadata directly in the doc](https://github.com/couchbase/sync_gateway/blob/a1cc33c0e4f56875d36580d895e7939b04bc89bf/rest/changes_api_test.go#L1102-L1123) 

When I look at the doc in couchbase server, that's confirmed:

```
{
  "_sync": {
    "rev": "1-a",
    "sequence": 2,
    "channels": {
      "PBS": null
    },
    "time_saved": "2017-06-26T14:04:32.428437545-07:00"
  },
  "key": "doc-2"
}
```

## Short term fix

Disable all tests which write docs with non-xattr doc meta content when running with xattrs = true

## Long term fix

Update [changes_api_test.go](https://github.com/couchbase/sync_gateway/blob/a1cc33c0e4f56875d36580d895e7939b04bc89bf/rest/changes_api_test.go#L1102-L1123) to write docs in an xattr aware fashion.
