### ISSUE TITLE
Upgrade to Go 1.9

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2706]
There are currently runtime failures if you try to build Sync Gateway with 1.8.3, since the current version of golang/x/text we are using is only compatible with 1.7.  

To upgrade to Go 1.9, we will need to do the following:

- [x] Update to use a later version of golang/x/text (see #2433)
- [x] Add Go 1.9 as a supported Go version on the build slaves
- [x] Build system changes: 
    - https://issues.couchbase.com/browse/MB-26166
    - https://issues.couchbase.com/browse/CBD-2095
    - https://issues.couchbase.com/browse/CBD-2094
- [ ] [Find out how to bump jenkins builds](https://issues.couchbase.com/browse/MB-26437)
- [ ] Update drone.yml to use go 1.9

/cc @ceejatec

**Comment by tleyden** [comment]
Error message:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x13a47e6]

goroutine 24 [running]:
golang.org/x/text/collate.newCollator(0x0, 0x0, 0x0)
        /Couchbase/sync_gateway/godeps/src/golang.org/x/text/collate/option.go:32 +0x146
golang.org/x/text/collate.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x34d19b0)
        /Couchbase/sync_gateway/godeps/src/golang.org/x/text/collate/collate.go:50 +0x104
github.com/couchbase/sg-bucket.(*JSONCollator).compareStrings(0xc422dec8b8, 0xc424128797, 0x1, 0xc423b9d467, 0x1, 0x14d190c)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/collate.go:101 +0xc7
github.com/couchbase/sg-bucket.(*JSONCollator).Collate(0xc422dec8b8, 0x16f4f40, 0xc4240261c0, 0x16f4f40, 0xc424684d40, 0xc422db7800)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/collate.go:57 +0x217
github.com/couchbase/sg-bucket.(*JSONCollator).Collate(0xc422dec8b8, 0x16e7ba0, 0xc42221de80, 0x16e7ba0, 0xc4237291c0, 0xc4210a3b1f)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/collate.go:65 +0x325
github.com/couchbase/sg-bucket.(*ViewResult).Less(0xc422dec880, 0x0, 0x5f3, 0x102e05a)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/views.go:220 +0x7b
sort.medianOfThree(0x1bf0120, 0xc422dec880, 0x0, 0x5f3, 0xbe6)
        /usr/local/Cellar/go/1.8.1/libexec/src/sort/sort.go:78 +0x49
sort.doPivot(0x1bf0120, 0xc422dec880, 0x0, 0x2f9d, 0x1d72d20, 0xc4210a3bb8)
        /usr/local/Cellar/go/1.8.1/libexec/src/sort/sort.go:103 +0x614
sort.quickSort(0x1bf0120, 0xc422dec880, 0x0, 0x2f9d, 0x1c)
        /usr/local/Cellar/go/1.8.1/libexec/src/sort/sort.go:192 +0x80
sort.Sort(0x1bf0120, 0xc422dec880)
        /usr/local/Cellar/go/1.8.1/libexec/src/sort/sort.go:220 +0x79
github.com/couchbaselabs/walrus.(*WalrusBucket).updateView(0xc420aa54d0, 0xc420663a40, 0x5f76, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbaselabs/walrus/views.go:256 +0x7f2
github.com/couchbaselabs/walrus.(*WalrusBucket).View(0xc420aa54d0, 0x1811224, 0x15, 0x18056be, 0x8, 0xc42304e9c0, 0x0, 0x0, 0x0, 0x0, ...)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbaselabs/walrus/views.go:151 +0x30f
github.com/couchbaselabs/walrus.(*WalrusBucket).ViewCustom(0xc420aa54d0, 0x1811224, 0x15, 0x18056be, 0x8, 0xc42304e9c0, 0x16cf1a0, 0xc422dec840, 0xc4210a4701, 0xc422dec840)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbaselabs/walrus/views.go:265 +0x84
github.com/couchbase/sync_gateway/base.(*LeakyBucket).ViewCustom(0xc421e19b80, 0x1811224, 0x15, 0x18056be, 0x8, 0xc42304e9c0, 0x16cf1a0, 0xc422dec840, 0x16f51c0, 0x0)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/leaky_bucket.go:116 +0x8c
github.com/couchbase/sync_gateway/db.(*DatabaseContext).getChangesInChannelFromView(0xc421e26a00, 0xc420ae8af9, 0x1, 0x2f9f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/changes_view.go:40 +0x7c1
github.com/couchbase/sync_gateway/db.(*channelCache).GetChanges(0xc420588500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/channel_cache.go:200 +0x41d
github.com/couchbase/sync_gateway/db.(*changeCache).GetChanges(0xc42023c780, 0xc420ae8af9, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:716 +0x133
github.com/couchbase/sync_gateway/db.(*Database).changesFeed(0xc422dda280, 0xc420ae8af9, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/changes.go:154 +0x103
github.com/couchbase/sync_gateway/db.(*Database).SimpleMultiChangesFeed.func1(0x0, 0x0, 0xc423053bc0, 0xc422dda280, 0xc420588320, 0xc42304e450)
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/changes.go:476 +0x956
created by github.com/couchbase/sync_gateway/db.(*Database).SimpleMultiChangesFeed
        /Couchbase/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/changes.go:686 +0x237
$  go version                                                                                                            in /Couchbase/Gateway
go version go1.8.1 darwin/amd64
```

**Comment by ceejatec** [comment]
What version do you need? The ticket says "update to 1.8" but then says 1.8 isn't sufficient...

**Comment by tleyden** [comment]
@ceejatec I just updated the ticket description to try to make it clearer.

**Comment by ceejatec** [comment]
For x/text, Server is using the SHA 601048ad6acbab6cedd582db09b8c4839ff25b15 and at least some parts of the codebase are compiled using Go 1.8, so updating the manifest would hopefully solve part one.

For part two, I'd hate to solve this manually again since it involves updating a half-dozen VMs/containers by hand, and we already have a very usable solution to this problem on Server using CMake and cbdeps. I think it's time to take the next step in merging the build methodologies.

**Comment by ajres** [comment]
Setting up a meeting to discuss way forward for part 2.

**Comment by ajres** [comment]
Go 1.9 GA has been [officially released](https://golang.org/dl/), is there a requirement to specifically use Go 1.8 or can we go straight to 1.9?

**Comment by ajres** [comment]
Building SG locally on macOS from current dev branch with golang 1.9 completes successfully.

**Comment by ajres** [comment]
Running the unit test suite with Go 1.9 consistently fails with:

```
go version go1.9 darwin/amd64


--- FAIL: TestSkippedViewRetrieval (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1307a3e]

goroutine 339 [running]:
testing.tRunner.func1(0xc42027c0f0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x1592aa0, 0x1ad97b0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
golang.org/x/text/collate.newCollator(0x0, 0x0, 0x0)
	/Users/andy/Projects/sync_gateway/godeps/src/golang.org/x/text/collate/option.go:32 +0x13e
golang.org/x/text/collate.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x60)
	/Users/andy/Projects/sync_gateway/godeps/src/golang.org/x/text/collate/collate.go:50 +0x13f
github.com/couchbase/sg-bucket.(*JSONCollator).compareStrings(0xc420391578, 0xc4201e1ad8, 0x3, 0xc420692b77, 0x1, 0x1c20b20)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/collate.go:101 +0xc7
github.com/couchbase/sg-bucket.(*JSONCollator).Collate(0xc420391578, 0x156be00, 0xc420206f20, 0x156be00, 0xc420206e60, 0xc42059d680)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/collate.go:57 +0x1bf
github.com/couchbase/sg-bucket.(*JSONCollator).Collate(0xc420391578, 0x1563d80, 0xc42058ca00, 0x1563d80, 0xc42058c640, 0x1af9d00)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/collate.go:65 +0x2aa
github.com/couchbase/sg-bucket.(*ViewResult).Less(0xc420391540, 0x1, 0x0, 0x1040192)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/views.go:220 +0x7b
sort.insertionSort(0x196e640, 0xc420391540, 0x0, 0x6)
	/usr/local/go/src/sort/sort.go:29 +0x9c
sort.quickSort(0x196e640, 0xc420391540, 0x0, 0x6, 0x6)
	/usr/local/go/src/sort/sort.go:211 +0x207
sort.Sort(0x196e640, 0xc420391540)
	/usr/local/go/src/sort/sort.go:220 +0x79
github.com/couchbaselabs/walrus.(*WalrusBucket).updateView(0xc4203c10e0, 0xc420555e60, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbaselabs/walrus/views.go:256 +0xa26
github.com/couchbaselabs/walrus.(*WalrusBucket).View(0xc4203c10e0, 0x163e5d4, 0xc, 0x163c7e0, 0x8, 0xc420202e70, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbaselabs/walrus/views.go:151 +0x350
github.com/couchbaselabs/walrus.(*WalrusBucket).ViewCustom(0xc4203c10e0, 0x163e5d4, 0xc, 0x163c7e0, 0x8, 0xc420202e70, 0x1550480, 0xc420391500, 0x1414c1c, 0xc420034700)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbaselabs/walrus/views.go:265 +0xa2
github.com/couchbase/sync_gateway/base.(*LeakyBucket).ViewCustom(0xc420390d00, 0x163e5d4, 0xc, 0x163c7e0, 0x8, 0xc420202e70, 0x1550480, 0xc420391500, 0xc420214301, 0xc420391500)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/leaky_bucket.go:116 +0x8c
github.com/couchbase/sync_gateway/base.(*LeakyBucket).ViewCustom(0xc420391340, 0x163e5d4, 0xc, 0x163c7e0, 0x8, 0xc420202e70, 0x1550480, 0xc420391500, 0x156be00, 0x153f501)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/leaky_bucket.go:116 +0x8c
github.com/couchbase/sync_gateway/db.(*DatabaseContext).getChangesInChannelFromView(0xc420180a00, 0x1639951, 0x1, 0x3, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, ...)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/changes_view.go:46 +0xdf2
github.com/couchbase/sync_gateway/db.(*changeCache).CleanSkippedSequenceQueue.func1(0xc42027c3c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:214 +0x25d
github.com/couchbase/sync_gateway/db.(*changeCache).CleanSkippedSequenceQueue(0xc42027c3c0, 0xc4201f41a0)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:233 +0x40
github.com/couchbase/sync_gateway/db.TestSkippedViewRetrieval(0xc42027c0f0)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/change_cache_test.go:835 +0x5ea
testing.tRunner(0xc42027c0f0, 0x1670c50)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
FAIL	github.com/couchbase/sync_gateway/db	2.939s
=== RUN   TestUserAPI
2017-09-01 17:13:57.896903 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  || != |true|
2017-09-01T17:13:57.897+01:00 Opening Walrus database test_data_bucket-e160ed4e289b8bfaa256b34edef53f75 on <walrus:>
2017-09-01 17:13:57.897425 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  || != |true|
2017-09-01 17:13:57.897441 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  || != |true|
2017-09-01T17:13:57.897+01:00 Opening db /db as bucket "test_data_bucket-2ec7a9962f1c004d4f70d05dddd4a13d", pool "default", server <walrus:>
2017-09-01T17:13:57.897+01:00 Opening Walrus database test_data_bucket-2ec7a9962f1c004d4f70d05dddd4a13d on <walrus:>
2017-09-01T17:13:57.898+01:00 Using default sync function 'channel(doc.channels)' for database "db"
--- FAIL: TestUserAPI (0.10s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x13fa22e]

goroutine 18 [running]:
testing.tRunner.func1(0xc4201f60f0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x17aee00, 0x1e73920)
	/usr/local/go/src/runtime/panic.go:491 +0x283
golang.org/x/text/collate.newCollator(0x0, 0x0, 0x0)
	/Users/andy/Projects/sync_gateway/godeps/src/golang.org/x/text/collate/option.go:32 +0x13e
golang.org/x/text/collate.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/andy/Projects/sync_gateway/godeps/src/golang.org/x/text/collate/collate.go:50 +0x13f
github.com/couchbase/sg-bucket.(*JSONCollator).compareStrings(0xc4201b3c78, 0x0, 0x0, 0xc420468c3c, 0x4, 0x10f6f21)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/collate.go:101 +0xc7
github.com/couchbase/sg-bucket.(*JSONCollator).Collate(0xc4201b3c78, 0x176d900, 0x1ea6140, 0x176d900, 0xc42041a450, 0x1e92d00)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/collate.go:57 +0x1bf
github.com/couchbase/sg-bucket.(*ViewResult).Less(0xc4201b3c40, 0x1, 0x0, 0x1040382)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sg-bucket/views.go:220 +0x7b
sort.insertionSort(0x1d03840, 0xc4201b3c40, 0x0, 0x2)
	/usr/local/go/src/sort/sort.go:29 +0x9c
sort.quickSort(0x1d03840, 0xc4201b3c40, 0x0, 0x2, 0x4)
	/usr/local/go/src/sort/sort.go:211 +0x207
sort.Sort(0x1d03840, 0xc4201b3c40)
	/usr/local/go/src/sort/sort.go:220 +0x79
github.com/couchbaselabs/walrus.(*WalrusBucket).updateView(0xc42021a120, 0xc4201d6b40, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbaselabs/walrus/views.go:256 +0xa26
github.com/couchbaselabs/walrus.(*WalrusBucket).View(0xc42021a120, 0x188f78c, 0xc, 0x188dffe, 0xa, 0xc4202bb110, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbaselabs/walrus/views.go:151 +0x350
github.com/couchbase/sync_gateway/base.(*LeakyBucket).View(0xc4201b8640, 0x188f78c, 0xc, 0x188dffe, 0xa, 0xc4202bb110, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/leaky_bucket.go:113 +0xc8
github.com/couchbase/sync_gateway/db.(*DatabaseContext).AllPrincipalIDs(0xc4201e3400, 0xc4204a6000, 0x2010000, 0x0, 0x166449c, 0xc4201619f8, 0x102bb09, 0xc400000008, 0xc4201619f8)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/database.go:818 +0x14c
github.com/couchbase/sync_gateway/rest.(*handler).getUsers(0xc420539680, 0xc420349f20, 0xc4201e3630)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/admin_api.go:509 +0x39
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc420539680, 0x18c7f40, 0x0, 0x0)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:221 +0x2c4
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x1d03a80, 0xc4202b0480, 0xc4201ee400)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:96 +0x80
net/http.HandlerFunc.ServeHTTP(0xc4204c3f00, 0x1d03a80, 0xc4202b0480, 0xc4201ee400)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420087090, 0x1d03a80, 0xc4202b0480, 0xc4201ee400)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/gorilla/mux/mux.go:114 +0xdc
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x1d03a80, 0xc4202b0480, 0xc4200fe000)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:300 +0x64a
net/http.HandlerFunc.ServeHTTP(0xc420349ec0, 0x1d03a80, 0xc4202b0480, 0xc4200fe000)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/couchbase/sync_gateway/rest.(*RestTester).SendAdminRequest(0xc4201b8380, 0x1887b78, 0x3, 0x188d73e, 0xa, 0x0, 0x0, 0xc42036ce50)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:201 +0x2a2
github.com/couchbase/sync_gateway/rest.TestUserAPI(0xc4201f60f0)
	/Users/andy/Projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/admin_api_test.go:51 +0x6ae
testing.tRunner(0xc4201f60f0, 0x18c85b8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
FAIL	github.com/couchbase/sync_gateway/rest	0.116s

```

**Comment by adamcfraser** [comment]
@ajres Are you running the previous test with the updated golang/x/text commit?  That looks like the same error we've previously identified.

**Comment by adamcfraser** [comment]
Regarding the earlier comment from @ceejatec - we've already identified the minimum commit we need from golang/x/text [here](https://github.com/couchbase/sync_gateway/issues/2433#issuecomment-290152922), and it's later than the current tip of couchbasedeps.

**Comment by ajres** [comment]
@adamcfraser I was running with the same golang/x/text commit, it was just a sanity unit test run for Go 1.9

**Comment by ajres** [comment]
Updated to use a latest commit HASH version of golang/x/text (see #2873)
