### ISSUE TITLE
Startup panic when connnecting to Couchbase Server directly after restart

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2716]
I ran into this while testing https://github.com/couchbase/sync_gateway/issues/2681

### Sync Gateway version

d0fc22384e915f73d30d2aabb96defde5c4b8181 (feature/issue_2681_409_conflicts_deletes_rebased branch)

### Operating system
Centos7 / Docker

### Log output

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x69ff9b]

goroutine 119 [running]:
panic(0xae2140, 0xc42000e040)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/couchbase/gocbcore%2ev7.(*Agent).Stats.func2(0x0, 0xc4201f0000, 0xf58c20, 0x10e2220)
	/Users/tleyden/Development/sync_gateway/godeps/src/gopkg.in/couchbase/gocbcore.v7/agentops_crud.go:531 +0x23b
gopkg.in/couchbase/gocbcore%2ev7.(*memdQRequest).tryCallback(0xc4201f0000, 0x0, 0xf58c20, 0x10e2220, 0x1)
	/Users/tleyden/Development/sync_gateway/godeps/src/gopkg.in/couchbase/gocbcore.v7/memdqpackets.go:57 +0x85
gopkg.in/couchbase/gocbcore%2ev7.(*memdClient).run.func2.1(0xc4201f0000)
	/Users/tleyden/Development/sync_gateway/godeps/src/gopkg.in/couchbase/gocbcore.v7/memdclient.go:184 +0x4c
```

[More logs](https://gist.github.com/tleyden/b22afc6805f823a0533f6f39fcd93f7a)

### Steps to reproduce
1.  I'm running [this script](https://github.com/couchbaselabs/mobile-testkit/pull/1308) to restart couchbase server followed by sync gateway directly afterwards

**Comment by tleyden** [comment]
Filed https://issues.couchbase.com/browse/GOCBC-219 since the panic is coming from gocb.

**Comment by tleyden** [comment]
TODO:

- Bump gocb and gocbcore to latest

**Comment by tleyden** [comment]
Already uptook gocb changes:

* https://github.com/couchbase/gocb/commit/0cd63ba8b594091ea0005ec50ee21299e0b22d97
* https://github.com/couchbase/gocbcore/commit/6b3fcad8ac5e2212fad55e57d481cb056b99f3c0
