### ISSUE TITLE
Prevent panic in rollbackEntries and log debug info

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2777]
This ticket has been split out from #2605 to prevent the panic and log debug information.

**Comment by ajres** [comment]
Copied from #2605

@adamcfraser Means , Sync-gateway service is not starting. Could see below messages in error.log

panic: runtime error: slice bounds out of range

goroutine 167 [running]:
panic(0xb41960, 0xc420014150)
	/usr/local/go/1.7.4/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbase/sync_gateway/db.(*DenseBlock).rollbackEntries(0xc420353780, 0x322, 0xb, 0x14c7f75fc31c0000, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/kv_dense_block.go:348 +0x1e0
github.com/couchbase/sync_gateway/db.(*DenseBlock).RollbackTo(0xc420353780, 0x322, 0xb, 0x1213ee0, 0xc4203c0a00, 0xc420353700, 0xc420706480, 0xc420706480)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/kv_dense_block.go:274 +0x6e
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*DensePartitionStorage).RollbackTo(0xc42080db90, 0xc4204e0322, 0xb, 0xc420c25578, 0xc4203c0a00)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.1/enterprise/godeps/src/github.com/couchbaselabs/sync-gateway-accel/indexwriter/dense_channel_storage_writer.go:248 +0xc1
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*DenseStorageWriter).RollbackTo(0xc4204ed050, 0xc420ac0322, 0xb, 0x10, 0x1)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.1/enterprise/godeps/src/github.com/couchbaselabs/sync-gateway-accel/indexwriter/dense_channel_storage_writer.go:100 +0xa3
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*ChannelWriter).Rollback(0xc4206e01c0, 0xc4204e0322, 0xb, 0xc4206e01c0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.1/enterprise/godeps/src/github.com/couchbaselabs/sync-gateway-accel/indexwriter/channel_writer.go:85 +0x1ef
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*KvChangeIndexWriter).rollbackIndex(0xc4202608f0, 0xc420c25a48, 0xc418a85b70, 0x1497b00)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.1/enterprise/godeps/src/github.com/couchbaselabs/sync-gateway-accel/indexwriter/kv_change_index_writer.go:948 +0x1a8
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*KvChangeIndexWriter).indexEntries(0xc4202608f0, 0xc4210ac000, 0xc, 0x7d0, 0xc4200e3800, 0x400, 0x400, 0x120cd80, 0xc420223920, 0x0, ...)

**Comment by ajres** [comment]
copied from #2605

From the logs provided the panic is in kv_dens_block.go rollbackEntries, at the last line in the code below

```
func (d *DenseBlock) rollbackEntries(vbNo uint16, seq uint64) (numRemoved int, rollbackComplete bool) {

	// Work backwards through the block, removing entries greater than vbNo, seq
	indexPos := DB_HEADER_LEN + uint32(d.getEntryCount()-1)*INDEX_ENTRY_LEN
	entryPos := uint32(len(d.value))

	for {
		indexEntry := d.GetIndexEntry(int64(indexPos))
```
it looks like the "panic: runtime error: slice bounds out of range" error is probably coming from  d.GetIndexEntry

```
func (d *DenseBlock) GetIndexEntry(position int64) (indexEntry DenseBlockIndexEntry) {
	indexEntry = d.value[position : position+INDEX_ENTRY_LEN]
	return indexEntry
}
```

**Comment by ajres** [comment]
copied from #2605 @adamcfraser 
The panic itself could be avoided by using a wrapper like [SafeSlice](https://github.com/couchbaselabs/sync-gateway-accel/blob/7e4f6b042e7a829acc777edc07ffcb8efffcfb81/indexwriter/util.go#L23), but we also need to understand why it's failing in the first place and get the root cause fixed.  Using SafeSlice would be a good starting point - we'd at least be able to log additional diagnostics about the slice at the time of failure, but we definitely need to get a repro scenario for this issue.
