### ISSUE TITLE
Update to Go 1.8.3

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2817]
The cause of https://github.com/couchbase/sync_gateway/issues/2814 might be using Go 1.7.x rather than Go 1.8.x.  

Regardless it's probably a good idea to bump to a later version of Go to pick up all of the fixes.

**Comment by tleyden** [comment]
http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/218/console failed with:

```
--- FAIL: TestSkippedViewRetrieval (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x70cba6]

goroutine 249 [running]:
testing.tRunner.func1(0xc42007ab60)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x9aa9a0, 0xea5e30)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
golang.org/x/text/collate.newCollator(0x0, 0x0, 0x0)
	/var/jenkins/workspace/build-sync-gateway/godeps/src/golang.org/x/text/collate/option.go:32 +0x146
golang.org/x/text/collate.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4204f29ed)
	/var/jenkins/workspace/build-sync-gateway/godeps/src/golang.org/x/text/collate/collate.go:50 +0x104
```

Which I believe can be fixed by just bumping the version of our upstream dependency for `golang.org/x/text`

**Comment by tleyden** [comment]
After bumping the golang.org/x/text version to https://github.com/couchbasedeps/text/commit/601048ad6acbab6cedd582db09b8c4839ff25b15

I'm seeing this test failure:

```
--- FAIL: TestSkippedViewRetrieval (0.01s)
2017-08-16 21:33:58.687227 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  || != |true|
2017-08-16 21:33:58.687283 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  || != |true|
2017-08-16 21:33:58.687311 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  || != |true|
2017-08-16T21:33:58.687Z Cache:   Querying 'channels' view for "*" (start=#3, end=#3, limit=0)
2017-08-16T21:33:58.687Z Cache: Received #2 after   0ms ("doc-2" / "1-a")
2017-08-16T21:33:58.687Z Cache:   Deferring #2 (1 now waiting for #1...#1)
2017-08-16T21:33:58.689Z Cache: Received #1 after   1ms ("doc-1" / "1-a")
2017-08-16T21:33:58.689Z Cache: Initialized cache for channel "ABC" with options: &{ChannelCacheMinLength:50 ChannelCacheMaxLength:500 ChannelCacheAge:1m0s}
2017-08-16T21:33:58.689Z Cache:     #1 ==> channel "ABC"
2017-08-16T21:33:58.689Z Cache: Initialized cache for channel "*" with options: &{ChannelCacheMinLength:50 ChannelCacheMaxLength:500 ChannelCacheAge:1m0s}
2017-08-16T21:33:58.689Z Cache:     #1 ==> channel "*"
2017-08-16T21:33:58.689Z Cache:     #2 ==> channel "ABC"
2017-08-16T21:33:58.689Z Cache:     #2 ==> channel "*"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x717d2b]

goroutine 198 [running]:
testing.tRunner.func1(0xc42035d520)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x9b56a0, 0xeb0e00)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
golang.org/x/text/collate.newCollator(0x0, 0x0, 0x0)
	/drone/godeps/src/golang.org/x/text/collate/option.go:30 +0x6b
golang.org/x/text/collate.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42047e9ed)
	/drone/godeps/src/golang.org/x/text/collate/collate.go:60 +0xbc
github.com/couchbase/sg-bucket.(*JSONCollator).compareStrings(0xc4202bfeb8, 0xc4202f6810, 0x3, 0xc4203a35f7, 0x1, 0xc420119fbb)
	/drone/godeps/src/github.com/couchbase/sg-bucket/collate.go:101 +0xc7
github.com/couchbase/sg-bucket.(*JSONCollator).Collate(0xc4202bfeb8, 0x98e480, 0xc4202f6ae0, 0x98e480, 0xc4202f6a10, 0x2)
	/drone/godeps/src/github.com/couchbase/sg-bucket/collate.go:57 +0x217
github.com/couchbase/sg-bucket.(*JSONCollator).Collate(0xc4202bfeb8, 0x9866c0, 0xc4202844e0, 0x9866c0, 0xc420284100, 0xa)
	/drone/godeps/src/github.com/couchbase/sg-bucket/collate.go:65 +0x325
github.com/couchbase/sg-bucket.(*ViewResult).Less(0xc4202bfe80, 0x1, 0x0, 0xa5ef01)
	/drone/godeps/src/github.com/couchbase/sg-bucket/views.go:220 +0x7b
```

**Comment by tleyden** [comment]
https://github.com/couchbase/sync_gateway/issues/2814 wasn't caused by the version of Go, so there isn't an immediate need for this change.  Closing as a duplicate of https://github.com/couchbase/sync_gateway/issues/2706
