### ISSUE TITLE
sgcollect_info Fails on Self-signed SSL Certificates

### ISSUE THREAD

**Issue by malarky** [couchbase/sync_gateway#2848]
When connecting to the admin port to get the `_expvar` data, `sgcollect_info` fails if a Self-Signed SSL Certificate is being used:

This is from 1.3.1, but code is unchanged:

```
Traceback (most recent call last): 
File "<string>", line 599, in <module> 
File "<string>", line 570, in main 
File "<string>", line 409, in make_sg_tasks 
File "<string>", line 369, in get_paths_from_expvars 
File "json/__init__.py", line 291, in load 
File "json/__init__.py", line 339, in loads 
File "json/decoder.py", line 364, in decode 
File "json/decoder.py", line 382, in raw_decode 
ValueError: No JSON object could be decoded 
sgcollect_info returned -1
```

https://github.com/couchbase/sync_gateway/blob/9e69d006f9ab2591ad5ae861777e1698bef8dc88/tools/sgcollect_info#L421

The call to [urllib2.urlopen](https://docs.python.org/2/library/urllib2.html) can optionally take an [SSLContext](https://docs.python.org/2/library/ssl.html#ssl.SSLContext) object -
 setting `check_hostname=False` and `verify_mode=ssl.CERT_NONE` should fix it.

**Comment by malarky** [comment]
Apparently [since Python 2.7.9](https://docs.python.org/2/library/httplib.html#httplib.HTTPSConnection):

> This class now performs all the necessary certificate and hostname checks by default. To revert to the previous, unverified, behavior ssl._create_unverified_context() can be passed to the context parameter.
