### ISSUE TITLE
TestDesignDocs / TestAdminReduceViewQuery fails against Couchbase Server bucket

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2954]
I ran into this while investigating integration test failures as a part of https://github.com/couchbase/sync_gateway/issues/2938

Basically the test is expecting a 404 error when calling GET on a non-existent design doc, and is getting a 500 error instead.

### Steps to repro

```
$ SG_TEST_BACKING_STORE=Couchbase SG_TEST_COUCHBASE_SERVER_URL=http://localhost:8091 SG_TEST_USE_XATTRS=false ./test.sh -run TestDesignDocs
```

### Sync Gateway version
`feature/issue_2937_improve_code_coverage`

### Couchbase Server version
4.1

### Log output

```
$ SG_TEST_BACKING_STORE=Couchbase SG_TEST_COUCHBASE_SERVER_URL=http://localhost:8091 SG_TEST_USE_XATTRS=false ./test.sh -run TestDesignDocs
Testing code with 'go test' ...
Running Sync Gateway unit tests
?   	github.com/couchbase/sync_gateway	[no test files]
PASS
ok  	github.com/couchbase/sync_gateway/auth	0.014s
PASS
ok  	github.com/couchbase/sync_gateway/base	0.014s
PASS
ok  	github.com/couchbase/sync_gateway/channels	0.016s
PASS
ok  	github.com/couchbase/sync_gateway/db	0.012s
=== RUN   TestDesignDocs
2017-10-04 16:04:09.262483 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-10-04 16:04:09.267246 I | Flushing test bucket: test_data_bucket
2017-10-04T16:04:10.630-07:00 WARNING: TestBucketManager.EmptyBucket(): still 5 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:313
2017-10-04T16:04:11.135-07:00 WARNING: TestBucketManager.EmptyBucket(): still 5 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:313
2017-10-04T16:04:11.644-07:00 WARNING: TestBucketManager.EmptyBucket(): still 5 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:313
2017-10-04T16:04:12.152-07:00 WARNING: TestBucketManager.EmptyBucket(): still 5 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:313
2017-10-04 16:04:12.659129 I | workerReadOwnWrites completed without errors
2017-10-04T16:04:12.659-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://localhost:8091> as user "test_data_bucket"
2017-10-04 16:04:12.661947 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-10-04 16:04:12.661976 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-10-04T16:04:12.661-07:00 Opening db /db as bucket "test_data_bucket", pool "default", server <http://localhost:8091>
2017-10-04T16:04:12.662-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://localhost:8091> as user "test_data_bucket"
2017-10-04 16:04:12.771034 I | bucketDataSource.Start() called
2017-10-04T16:04:12.771-07:00 Using default sync function 'channel(doc.channels)' for database "db"
_time=2017-10-04T16:04:12.786-07:00 _level=INFO _msg=Using plain authentication for user test_data_bucket
2017-10-04T16:04:12.829-07:00 TEMP: GetDesignDoc "foo" -- rest.(*handler).handleGetDesignDoc() at view_api.go:18
2017-10-04T16:04:12.835-07:00 TEMP: GetDesignDoc "foo" -- rest.(*handler).handleGetDesignDoc() at view_api.go:18
goroutine 5 [running]:
runtime/debug.Stack(0xacbcc, 0xc42040be60, 0x206c34)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/couchbase/sync_gateway/rest.assertStatus(0xc4201e6180, 0xc42021e6b0, 0x194)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:295 +0x5f
github.com/couchbase/sync_gateway/rest.TestDesignDocs(0xc4201e6180)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/view_api_test.go:37 +0x234
testing.tRunner(0xc4201e6180, 0x94bda0)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
--- FAIL: TestDesignDocs (3.58s)
	utilities_testing.go:297: Response status 200 (expected 404) for GET <http://localhost/db/_design/foo> : {"views":{"bar":{"map":"function(doc,meta) {\n\t                    var sync = doc._sync;\n\t                    if (sync === undefined || meta.id.substring(0,6) == \"_sync:\")\n\t                      return;\n\t                    if ((sync.flags \u0026 1) || sync.deleted)\n\t                      return;\n\t                    delete doc._sync;\n\t                    meta.rev = sync.rev;\n\t\t\t\t\t\t(function(doc) {emit(doc.key, doc.value);}) (doc, meta);\n\t\t\t\t\t\tdoc._sync = sync;}"}}}
FAIL
2017-10-04 16:04:12.837921 I | bucketDataSource.Close() called
FAIL	github.com/couchbase/sync_gateway/rest	3.591s
```

### Walrus test passes

```
G_TEST_BACKING_STORE=Walrus SG_TEST_COUCHBASE_SERVER_URL=http://localhost:8091 SG_TEST_USE_XATTRS=false ./test.sh -run TestDesignDocs
Testing code with 'go test' ...
Running Sync Gateway unit tests
?   	github.com/couchbase/sync_gateway	[no test files]
PASS
ok  	github.com/couchbase/sync_gateway/auth	0.018s
PASS
ok  	github.com/couchbase/sync_gateway/base	0.012s
PASS
ok  	github.com/couchbase/sync_gateway/channels	0.015s
PASS
ok  	github.com/couchbase/sync_gateway/db	0.013s
=== RUN   TestDesignDocs
2017-10-04 16:04:39.802896 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-10-04T16:04:39.803-07:00 Opening Walrus database test_data_bucket-d8b30fbe5a7bb24ec04eae4fec6cd0db on <walrus:>
2017-10-04 16:04:39.803362 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-10-04 16:04:39.803386 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-10-04T16:04:39.803-07:00 Opening db /db as bucket "test_data_bucket-f80196c0133bef0d75320809efa143be", pool "default", server <walrus:>
2017-10-04T16:04:39.803-07:00 Opening Walrus database test_data_bucket-f80196c0133bef0d75320809efa143be on <walrus:>
2017-10-04T16:04:39.803-07:00 Using default sync function 'channel(doc.channels)' for database "db"
2017-10-04T16:04:39.808-07:00 TEMP: GetDesignDoc "foo" -- rest.(*handler).handleGetDesignDoc() at view_api.go:18
2017-10-04T16:04:39.813-07:00 TEMP: GetDesignDoc "foo" -- rest.(*handler).handleGetDesignDoc() at view_api.go:18
2017-10-04T16:04:39.818-07:00 TEMP: GetDesignDoc "foo" -- rest.(*handler).handleGetDesignDoc() at view_api.go:18
2017-10-04T16:04:39.820-07:00 TEMP: GetDesignDoc "foo" -- rest.(*handler).handleGetDesignDoc() at view_api.go:18
2017-10-04T16:04:39.822-07:00 TEMP: GetDesignDoc "foo" -- rest.(*handler).handleGetDesignDoc() at view_api.go:18
2017-10-04T16:04:39.829-07:00 TEMP: GetDesignDoc "sync_gateway" -- rest.(*handler).handleGetDesignDoc() at view_api.go:18
--- PASS: TestDesignDocs (0.03s)
```

For now I'm going to skip this test when running against a live couchbase server bucket.

**Comment by tleyden** [comment]
### TestAdminReduceViewQuery

This test also fails.  

```
$ SG_TEST_BACKING_STORE=Couchbase SG_TEST_COUCHBASE_SERVER_URL=http://localhost:8091 SG_TEST_USE_XATTRS=false ./test.sh -run ^TestAdminReduceViewQuery$
Testing code with 'go test' ...
Running Sync Gateway unit tests
?   	github.com/couchbase/sync_gateway	[no test files]
PASS
ok  	github.com/couchbase/sync_gateway/auth	0.014s
PASS
ok  	github.com/couchbase/sync_gateway/base	0.012s
PASS
ok  	github.com/couchbase/sync_gateway/channels	0.016s
PASS
ok  	github.com/couchbase/sync_gateway/db	0.014s
=== RUN   TestAdminReduceViewQuery
2017-10-04 17:23:04.030064 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-10-04 17:23:04.033301 I | Flushing test bucket: test_data_bucket
2017-10-04T17:23:05.445-07:00 WARNING: TestBucketManager.EmptyBucket(): still 6 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:313
2017-10-04T17:23:05.952-07:00 WARNING: TestBucketManager.EmptyBucket(): still 6 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:313
2017-10-04T17:23:06.458-07:00 WARNING: TestBucketManager.EmptyBucket(): still 6 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:313
2017-10-04T17:23:06.966-07:00 WARNING: TestBucketManager.EmptyBucket(): still 6 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:313
2017-10-04 17:23:07.475599 I | workerReadOwnWrites completed without errors
2017-10-04T17:23:07.475-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://localhost:8091> as user "test_data_bucket"
2017-10-04 17:23:07.478530 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-10-04 17:23:07.478566 I | NOT Using xattrs: strings.ToLower(useXattrs) != strings.ToLower(TestEnvSyncGatewayTrue).  |false| != |true|
2017-10-04T17:23:07.478-07:00 Opening db /db as bucket "test_data_bucket", pool "default", server <http://localhost:8091>
2017-10-04T17:23:07.478-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://localhost:8091> as user "test_data_bucket"
2017-10-04 17:23:07.590404 I | bucketDataSource.Start() called
_time=2017-10-04T17:23:07.600-07:00 _level=INFO _msg=Using plain authentication for user test_data_bucket
--- FAIL: TestAdminReduceViewQuery (3.66s)
	changes_api_test.go:1451: Unexpected error: Got response code: 500 from view call.  Expected 200.
FAIL
FAIL	github.com/couchbase/sync_gateway/rest	3.675s
```

**Comment by tleyden** [comment]
These tests also fail

## TestAdminReduceSumQuery

## TestAdminGroupReduceSumQuery

## TestAdminGroupLevelReduceSumQuery

**Comment by tleyden** [comment]
After upgrading couchbase server, I'm still seeing temporary failure errors in the [logs](https://gist.github.com/tleyden/2acd97d264ef18bc7f81d160ba4e2726):

```
e.(*DCPReceiver).RollbackEx() at dcp_feed.go:253
2017-10-05T11:48:53.291-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:role:ROLE_1}") count=2
2017-10-05T11:48:53.379-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:testUser}") count=3
2017-10-05T11:48:53.379-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:testUser}") count=4
2017-10-05T11:48:55.301-07:00 WARNING: RetryLoop for Get _sync:syncdata giving up after 11 attempts -- base.RetryLoop() at util.go:298
--- FAIL: TestDBOnlineWithDelayAndImmediate (17.17s)
panic: Error from AddDatabaseFromConfig: Error creating applySyncFunction: temporary failure occurred, try again later [recovered]
        panic: Error from AddDatabaseFromConfig: Error creating applySyncFunction: temporary failure occurred, try again later

```

**Comment by tleyden** [comment]
These tests are all enabled and passing.  I think this ticket should have been closed a while ago
