### ISSUE TITLE
Intermittent / sporadic unit test failures

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2978]
TODO: file out in separate tickets

- [ ] [TestPostChangesUserTiming](https://github.com/couchbase/sync_gateway/issues/2999)
- [ ] [TestChangesLoopingWhenLowSequence](https://github.com/couchbase/sync_gateway/issues/3000)
- [ ] [TestLowSequenceHandlingAcrossChannels](https://github.com/couchbase/sync_gateway/issues/3001)
- [ ] [TestDBOnlineConcurrent](https://github.com/couchbase/sync_gateway/issues/3002) 
- [ ] [TestDBOfflineSingleResync](https://github.com/couchbase/sync_gateway/issues/3003) 
- [ ] [TestRecentSequenceHistory](https://github.com/couchbase/sync_gateway/issues/3004) 
- [ ] [TestChangeIndexChanges](https://github.com/couchbase/sync_gateway/issues/3005) 
- [ ] [TestUserAccessRace](https://github.com/couchbase/sync_gateway/issues/3006)
- [ ] [TestBulkDocsUnusedSequencesMultiRevDoc](https://github.com/couchbase/sync_gateway/issues/3007)
- [ ] [TestChangeIndexAddSet](https://github.com/couchbase/sync_gateway/issues/3008)
- [ ] [TestPurgeWithSomeInvalidDocs](https://github.com/couchbase/sync_gateway/issues/3009)
- [ ] [TestBulkDocsUnusedSequencesMultiRevDoc](https://github.com/couchbase/sync_gateway/issues/2983) -- has it's own github issue

**Comment by tleyden** [comment]
## TestPostChangesUserTiming

See http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-unix-build/2555/consoleFull.  Originally reported in https://github.com/couchbase/sync_gateway/issues/2541

**Comment by tleyden** [comment]
## TestChangesLoopingWhenLowSequence

In http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration/19/console, failed with:

```
=== RUN   TestChangesLoopingWhenLowSequence
*** Test killed: ran too long (10m0s).
```

I also ran the test locally in a loop (in integration test mode), and was able to repro sporadic failures.

**Comment by tleyden** [comment]
## TestLowSequenceHandlingAcrossChannels

In [jenkins build sgw-unix-build/3109](http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-unix-build/3109/consoleFull):

```
02:15:27 2017-06-26T02:28:10.478-07:00 Changes+: No new changes to send to change listener.  Waiting for "test_data_bucket-86a3ecb3b97c33e0df1bcc05595985b6"'s count to pass 5
02:15:27 2017-06-26T02:28:10.479-07:00 Cache: Received #3 after   0ms ("doc-3" / "1-a")
02:15:27 2017-06-26T02:28:10.479-07:00 Cache:   Received previously skipped out-of-order change (seq 3, expecting 10) doc "doc-3" / "1-a" 
02:15:27 2017-06-26T02:28:10.479-07:00 Cache:     #3 ==> channel "PBS"
02:15:27 2017-06-26T02:28:10.479-07:00 Cache:     #3 ==> channel "*"
02:15:27 2017-06-26T02:28:10.480-07:00 Changes+: Notifying that "test_data_bucket-86a3ecb3b97c33e0df1bcc05595985b6" changed (keys="{*, PBS}") count=6
02:15:27 2017-06-26T02:28:10.571-07:00 waitForSequence(9) took 100 ms
02:15:27 2017-06-26 02:28:10.622699 I | Feed retrieving  0xc42041eae0 1
02:15:27 2017-06-26 02:28:10.622857 I | Changes entry: {Seq:2::9, ID:doc-9, Changes:[map[rev:1-a]]}
02:15:27 2017-06-26 02:28:10.622905 I | returned numEntries - returning
02:15:27 2017-06-26 02:28:10.622978 I | verifyChangesFullSequences: sequence mismatch at index 3, changes=2::9, sequences=3::9
02:15:27 
02:15:27 	change_cache_test.go:598
02:15:27 	assert.True(t, verifyChangesFullSequences(changes, []string{"1", "2", "2::6", "3::9"}))	
02:15:27 --- FAIL: TestLowSequenceHandlingAcrossChannels (3.64s)
``` 

On the same commit, the test passed on several other build slaves, so I'm assuming it's a sporadic test failure.

**Comment by tleyden** [comment]
## TestShadowerPattern

In [cen7-sync-gateway-functional-tests-topology-specific-di/421](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-di/421/consoleFull) which is on the `feature/remove_gocb_hybrid` branch

```
FAIL: TestShadowerPattern (0.00s)\npanic: runtime error: invalid memory address or nil pointer dereference [recovered]\n\tpanic: runtime error: invalid memory address or nil pointer 
dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x51d22e]\n\ngoroutine 1871 [running]:\npanic(0x9294e0, 0xc420010090)\n\t/usr/local/go/src/runtime/panic.go:500
 +0x1a1\ntesting.tRunner.func1(0xc421b12900)\n\t/usr/local/go/src/testing/testing.go:579 +0x25d\npanic(0x9294e0, 0xc420010090)\n\t/usr/local/go/src/runtime/panic.go:458 +0x243\ngithub.com/couchbase/sync_gateway/db.TestShadowerPattern(0xc421b12900)\n\t/home/centos/godeps/src/github.com/couchbase/sync_gateway/db/shadower_test.go:241 
+0x6ee\ntesting.tRunner(0xc421b12900, 0xa639b8)\n\t/usr/local/go/src/testing/testing.go:610 +0x81\ncreated by testing.(*T).Run\n\t/usr/local/go/src/testing/testing.go:646 +0x2ec\nFAIL\tgithub.com/couchbase/sync_gateway/db\t16.691s
```

**Comment by tleyden** [comment]
## TestBulkDocsUnusedSequencesMultiRevDoc

### Repro

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration/27/console

### Logs

```
=== RUN   TestBulkDocsUnusedSequencesMultiRevDoc
2017-10-19T12:42:52.636-07:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2017-10-19T12:42:52.637-07:00 WARNING: Error processing DCP stream - will attempt to restart/reconnect: pkt.Receive, err: read tcp 172.23.105.143:36454->172.23.109.96:11210: use of closed network connection. -- base.(*DCPReceiver).OnError() at dcp_feed.go:120
2017-10-19T12:42:54.224-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs.sc.couchbase.com:8091> as user "test_data_bucket"
2017-10-19T12:42:54.236-07:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2017-10-19T12:42:54.236-07:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2017-10-19T12:42:54.236-07:00 Opening db /db as bucket "test_data_bucket", pool "default", server <http://integration-cbs.sc.couchbase.com:8091>
2017-10-19T12:42:54.236-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs.sc.couchbase.com:8091> as user "test_data_bucket"
2017-10-19T12:42:54.575-07:00 Cache: Initializing changes cache with options {ChannelCacheOptions:{ChannelCacheMinLength:0 ChannelCacheMaxLength:0 ChannelCacheAge:0s} CachePendingSeqMaxWait:5s CachePendingSeqMaxNum:10000 CacheSkippedSeqMaxWait:1h0m0s}
2017-10-19T12:42:54.614-07:00 Using metadata purge interval of 3.00 days for tombstone compaction.
_time=2017-10-19T12:42:54.628-07:00 _level=INFO _msg=Using plain authentication for user test_data_bucket 
2017-10-19T12:42:54.703-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:}") count=2
2017-10-19T12:42:54.966-07:00 HTTP:  #247: POST http://localhost/db/_bulk_docs
2017-10-19T12:42:54.966-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{_sync:user:}") count=3
2017-10-19T12:42:54.970-07:00 WARNING: Sync fn exception: Rejecting invalid doc; doc = map[n:%!s(float64=2) type:invalid _rev:1-a69b6e0644577af07d30a6b5c3d00fd7 _id:bulk2] -- db.(*Database).getChannelsAndAccess() at crud.go:1199
2017-10-19T12:42:54.970-07:00 	BulkDocs: Doc "bulk2" --> 500 Exception in JS sync function (500 Exception in JS sync function)
2017-10-19T12:42:54.971-07:00 Cache: Received #1 after   1ms ("bulk1" / "1-50133ddd8e49efad34ad9ecae4cb9907")
2017-10-19T12:42:54.971-07:00 Cache: Initialized cache for channel "*" with options: &{ChannelCacheMinLength:50 ChannelCacheMaxLength:500 ChannelCacheAge:1m0s}
2017-10-19T12:42:54.971-07:00 Cache:     #1 ==> channel "*"
2017-10-19T12:42:54.971-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{*}") count=4
2017-10-19T12:42:54.972-07:00 Cache: Received #2 after   0ms ("bulk3" / "1-bfa09fe957e5e28b750cff0568b1cb05")
2017-10-19T12:42:54.972-07:00 Cache:     #2 ==> channel "*"
2017-10-19T12:42:54.972-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{*}") count=5
2017-10-19T12:42:54.973-07:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2017-10-19T12:42:54.973-07:00 Opening db /db as bucket "test_data_bucket", pool "default", server <http://integration-cbs.sc.couchbase.com:8091>
2017-10-19T12:42:54.973-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs.sc.couchbase.com:8091> as user "test_data_bucket"
2017-10-19T12:42:55.312-07:00 Cache: Initializing changes cache with options {ChannelCacheOptions:{ChannelCacheMinLength:0 ChannelCacheMaxLength:0 ChannelCacheAge:0s} CachePendingSeqMaxWait:5s CachePendingSeqMaxNum:10000 CacheSkippedSeqMaxWait:1h0m0s}
2017-10-19T12:42:55.333-07:00 **NOTE:** "db"'s sync function has changed. The new function may assign different channels to documents, or permissions to users. You may want to re-sync the database to update these.
2017-10-19T12:42:55.333-07:00 Using default sync function 'channel(doc.channels)' for database "db"
2017-10-19T12:42:55.340-07:00 HTTP:  #248: POST http://localhost/db/_bulk_docs
2017-10-19T12:42:55.344-07:00 Cache: Received #7 after   0ms ("bulk1" / "2-d2111723d973efbcc415aab0ade25a45")
2017-10-19T12:42:55.344-07:00 Cache:   Deferring #7 (1 now waiting for #3...#6)

	api_test.go:966
	assert.Equals(t, doc1Rev2.Sequence, uint64(7))	

	expected: 0x7
	     got: 0x0
2017-10-19T12:42:55.347-07:00 HTTP:  #249: POST http://localhost/db/_bulk_docs
2017-10-19T12:42:55.348-07:00 	BulkDocs: Doc "bulk1" --> 409 Document exists (409 Document exists)

	api_test.go:982
	assert.Equals(t, doc1Rev3.Sequence, uint64(8))	

	expected: 0x8
	     got: 0x7

	api_test.go:986
	assert.Equals(t, len(rs), 3)	

	expected: 3
	     got: 2
2017-10-19T12:42:55.350-07:00 Changes+: changeListener.Stop() called
2017-10-19T12:42:55.350-07:00 Changes+: changeListener.Stop() called
--- FAIL: TestBulkDocsUnusedSequencesMultiRevDoc (2.71s)
	assert.go:31: 
	assert.go:31: 
	assert.go:31: 
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 4040 [running]:
panic(0xbb28a0, 0xc4200120f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42109ea80)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0xbb28a0, 0xc4200120f0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/couchbase/sync_gateway/rest.TestBulkDocsUnusedSequencesMultiRevDoc(0xc42109ea80)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/rest/api_test.go:989 +0x144f
testing.tRunner(0xc42109ea80, 0xd5af58)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL	github.com/couchbase/sync_gateway/rest	158.907s
```

**Comment by tleyden** [comment]
## TestChangeIndexAddSet

### Repro

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration/31/console

### Logs

```
=== RUN   TestChangeIndexAddSet
panic: Accessing closed Walrus bucket "test_indexbucket-06cd015a7eb38b5da34454c01e419b81"

goroutine 5039 [running]:
panic(0xc18720, 0xc42166a320)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbaselabs/walrus.(*WalrusBucket).assertNotClosed(0xc42105c1b0)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbaselabs/walrus/crud.go:192 +0x104
github.com/couchbaselabs/walrus.(*WalrusBucket).missingError(0xc42105c1b0, 0xc42166a2f0, 0x10, 0x10, 0x1474ea0)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbaselabs/walrus/crud.go:197 +0x2f
github.com/couchbaselabs/walrus.(*WalrusBucket).getRaw(0xc42105c1b0, 0xc42166a2f0, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbaselabs/walrus/crud.go:219 +0x13b
github.com/couchbaselabs/walrus.(*WalrusBucket).GetRaw(0xc42105c1b0, 0xc42166a2f0, 0x10, 0xc0c7a0, 0xc4216a2300, 0x1, 0x0, 0x11ac360, 0xc42166a300)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbaselabs/walrus/crud.go:225 +0x5a
github.com/couchbase/sync_gateway/base.(*LeakyBucket).GetRaw(0xc4202e2640, 0xc42166a2f0, 0x10, 0x0, 0x0, 0x18, 0xc0c7a0, 0xc4216a2300, 0x1)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/base/leaky_bucket.go:45 +0x4e
github.com/couchbase/sync_gateway/base.WriteCasRaw(0x11be600, 0xc4202e2640, 0xc42166a2f0, 0x10, 0xc4216ac500, 0x416, 0x489, 0x18, 0x0, 0xc420763cf8, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/base/bucket.go:552 +0x77
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*ChannelWriter).writeClockCas(0xc42045efc0, 0xc4207ab600, 0x40, 0x40, 0x50a500, 0x59e90e3b, 0xe3a835)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/channel_writer.go:218 +0x34c
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*ChannelWriter).updateChannelClock(0xc42045efc0, 0xc4207ab600, 0x40, 0x40, 0xc4207ab600, 0x40, 0x40)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/channel_writer.go:113 +0x65
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*ChannelWriter).AddSet(0xc42045efc0, 0xc42050c000, 0x2, 0x7d0, 0x0, 0x0)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/channel_writer.go:61 +0x347
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*KvChangeIndexWriter).addSetToChannelIndex(0xc4216e00f0, 0xc42004a75b, 0x3, 0xc42050c000, 0x2, 0x7d0, 0x400, 0x400)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/kv_change_index_writer.go:971 +0x130
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*KvChangeIndexWriter).indexEntries.func2(0xc42166a150, 0xc4216e00f0, 0xc42004a75b, 0x3, 0xc42050c000, 0x2, 0x7d0, 0xc400000000)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/kv_change_index_writer.go:861 +0xd8
created by github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*KvChangeIndexWriter).indexEntries
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/kv_change_index_writer.go:868 +0x13e6
exit status 2
FAIL	github.com/couchbaselabs/sync-gateway-accel/indexwriter	21.010s
exit status 1
```

**Comment by tleyden** [comment]
## TestPurgeWithSomeInvalidDocs

### Repro

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration/30/console

### Logs

```
=== RUN   TestPurgeWithSomeInvalidDocs
2017-10-19T13:18:32.407-07:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
panic: runtime error: slice bounds out of range

goroutine 2213 [running]:
panic(0xbb28a0, 0xc420012100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbase/sync_gateway/db.parseXattrStreamData(0xc808dc, 0x5, 0xc42090e440, 0x0, 0x0, 0xc3f680, 0xc420748001, 0xc4207405d0, 0xc4206115f8, 0x40857b, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/db/document.go:194 +0x68b
github.com/couchbase/sync_gateway/db.UnmarshalDocumentSyncDataFromFeed(0xc42090e440, 0x0, 0x0, 0x5, 0xc4207405d0, 0x0, 0xc420611708, 0x58a30d, 0xc420182120, 0xc4206116e7, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/db/document.go:141 +0x153
github.com/couchbase/sync_gateway/db.(*changeCache).DocChangedSynchronous(0xc4200c21e0, 0x2, 0x0, 0xc42090e440, 0x0, 0x0, 0xc42090e440, 0x0, 0x0, 0x14ef121c2c7a0000, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:384 +0x1f1
github.com/couchbase/sync_gateway/db.(*changeCache).DocChanged(0xc4200c21e0, 0x2, 0x0, 0xc42090e440, 0x0, 0x0, 0xc42090e440, 0x0, 0x0, 0x14ef121c2c7a0000, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:340 +0x61
github.com/couchbase/sync_gateway/db.(ChangeIndex).DocChanged-fm(0x2, 0x0, 0xc42090e440, 0x0, 0x0, 0xc42090e440, 0x0, 0x0, 0x14ef121c2c7a0000, 0x50000, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/db/database.go:225 +0x4c
github.com/couchbase/sync_gateway/db.(*changeListener).ProcessFeedEvent(0xc420496ab0, 0x2, 0x0, 0xc42090e440, 0x0, 0x0, 0xc42090e440, 0x0, 0x0, 0x14ef121c2c7a0000, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/db/change_listener.go:118 +0x2b3
github.com/couchbase/sync_gateway/db.(*changeListener).ProcessFeedEvent-fm(0x2, 0x0, 0xc42090e440, 0x0, 0x0, 0xc42090e440, 0x0, 0x0, 0x14ef121c2c7a0000, 0x50000, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/db/change_listener.go:92 +0x4a
github.com/couchbase/sync_gateway/base.(*DCPReceiver).DataUpdate(0xc4205f4500, 0x8c, 0xc42090e440, 0x0, 0x0, 0x3, 0xc4205f4800, 0x0, 0x0)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/base/dcp_feed.go:142 +0x198
github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).worker.func5(0xc4205f9f20, 0xc4201e6500, 0xc420525aa0, 0x26, 0xc420018800, 0x3a, 0xc4206b7740, 0xc4202dace0, 0xc420740540, 0xc4205f9e60, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1168 +0x8bd
created by github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).worker
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1220 +0x564
exit status 2
FAIL	github.com/couchbase/sync_gateway/rest	91.043s
```

**Comment by tleyden** [comment]
## TestBulkDocsUnusedSequencesMultiRevDoc

### Repro 

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration/35/console

### Logs

```
2017-10-19T14:55:50.577-07:00 Opening db /db as bucket "test_data_bucket", pool "default", server <http://integration-cbs.sc.couchbase.com:8091>
2017-10-19T14:55:50.577-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs.sc.couchbase.com:8091> as user "test_data_bucket"
2017-10-19T14:55:50.912-07:00 Cache: Initializing changes cache with options {ChannelCacheOptions:{ChannelCacheMinLength:0 ChannelCacheMaxLength:0 ChannelCacheAge:0s} CachePendingSeqMaxWait:5s CachePendingSeqMaxNum:10000 CacheSkippedSeqMaxWait:1h0m0s}
2017-10-19T14:55:50.932-07:00 **NOTE:** "db"'s sync function has changed. The new function may assign different channels to documents, or permissions to users. You may want to re-sync the database to update these.
2017-10-19T14:55:50.932-07:00 Using default sync function 'channel(doc.channels)' for database "db"
2017-10-19T14:55:50.938-07:00 HTTP:  #248: POST http://localhost/db/_bulk_docs
2017-10-19T14:55:50.943-07:00 Cache: Received #7 after   0ms ("bulk1" / "2-d2111723d973efbcc415aab0ade25a45")
2017-10-19T14:55:50.943-07:00 Cache:   Deferring #7 (1 now waiting for #3...#6)

	api_test.go:966
	assert.Equals(t, doc1Rev2.Sequence, uint64(7))	

	expected: 0x7
	     got: 0x0
2017-10-19T14:55:50.945-07:00 HTTP:  #249: POST http://localhost/db/_bulk_docs
2017-10-19T14:55:50.946-07:00 	BulkDocs: Doc "bulk1" --> 409 Document exists (409 Document exists)

	api_test.go:982
	assert.Equals(t, doc1Rev3.Sequence, uint64(8))	

	expected: 0x8
	     got: 0x7

	api_test.go:986
	assert.Equals(t, len(rs), 3)	

	expected: 3
	     got: 2
2017-10-19T14:55:50.948-07:00 Changes+: changeListener.Stop() called
2017-10-19T14:55:50.948-07:00 Changes+: changeListener.Stop() called
--- FAIL: TestBulkDocsUnusedSequencesMultiRevDoc (7.83s)
```

**Comment by tleyden** [comment]
Closing this since the separate issues have been filed, and linked off the initial comment in this issue.
