### ISSUE TITLE
Sporadic test failure: TestUserAccessRace

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3006]
Originally filed in https://github.com/couchbase/sync_gateway/issues/1350

**Comment by tleyden** [comment]
- Reenable and run with -race in loop to try to repro

**Comment by tleyden** [comment]
- Not failing with race error, test fails
- Maybe due to running slower and changes feed timing issues

**Comment by tleyden** [comment]
- Poor test or bug in code?

**Comment by tleyden** [comment]
I'm able to reproduce a test failure by changing the `timeout` to 200 ms in this call:

```
		changesResponse := rt.Send(requestByUser("GET", "/db/_changes?feed=continuous&since=0&timeout=200", "", "bernard"))

```

Test fail:

```
2017-11-08T18:02:10.109-08:00 HTTP:  #002: PUT http://localhost/db/_user/bernard  (ADMIN)
_time=2017-11-08T18:02:10.220-08:00 _level=INFO _msg=Using plain authentication for user test_data_bucket
2017-11-08T18:02:10.431-08:00 HTTP:  #003: GET http://localhost/db/_user/bernard  (ADMIN)
2017-11-08T18:02:10.455-08:00 HTTP:  #004: POST http://localhost/db/_bulk_docs  (ADMIN)
2017-11-08T18:02:10.581-08:00 HTTP:  #005: POST http://localhost/db/_bulk_docs  (as bernard)
2017-11-08T18:02:10.582-08:00 HTTP:  #006: GET http://localhost/db/_changes?feed=continuous&since=0&timeout=200  (as bernard)
2017-11-08 18:02:11.188118 I | Got change ==> {1 _user/bernard false {} map[] [] <nil> false false 0 false}
2017-11-08 18:02:11.188161 I | Got change ==> {102 Want-bernard-l_1 false {} map[] [map[rev:1-218d249c9e9a61ecdb89bcf03def4e6b]] <nil> false false 0 false}
2017-11-08 18:02:11.188178 I | Got change ==> {102:2 l_1 false {} map[] [map[rev:1-80820e4fa8200aea429a97bf2344a448]] <nil> false false 0 false}
2017-11-08 18:02:11.188191 I | Got change ==> {103 Want-bernard-l_2 false {} map[] [map[rev:1-218d249c9e9a61ecdb89bcf03def4e6b]] <nil> false false 0 false}
2017-11-08 18:02:11.188204 I | Got change ==> {103:3 l_2 false {} map[] [map[rev:1-80820e4fa8200aea429a97bf2344a448]] <nil> false false 0 false}
2017-11-08 18:02:11.188215 I | Got change ==> {104:4 l_3 false {} map[] [map[rev:1-80820e4fa8200aea429a97bf2344a448]] <nil> false false 0 false}
2017-11-08 18:02:11.188238 I | Got change ==> {104 Want-bernard-l_3 false {} map[] [map[rev:1-218d249c9e9a61ecdb89bcf03def4e6b]] <nil> false false 0 false}
2017-11-08 18:02:11.188251 I | Got change ==> {105 Want-bernard-l_4 false {} map[] [map[rev:1-218d249c9e9a61ecdb89bcf03def4e6b]] <nil> false false 0 false}
2017-11-08 18:02:11.188266 I | Got change ==> {106 Want-bernard-l_5 false {} map[] [map[rev:1-218d249c9e9a61ecdb89bcf03def4e6b]] <nil> false false 0 false}
2017-11-08 18:02:11.188274 I | Got 9 change entries

	admin_api_test.go:309
	assert.Equals(t, len(changes), 201)

	expected: 201
	     got: 9
--- FAIL: TestUserAccessRace (18.08s)
```

**Comment by tleyden** [comment]
Re-opening again due to this failure:

```
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/241/consoleFull
```

Logs: https://gist.github.com/tleyden/3d264bcb3c619e07351487cf71eba10e#file-gistfile1-txt-L91-L339

SG_TEST_USE_XATTRS: false
TARGET_TEST: ALL

**Comment by bbrks** [comment]
Latest occurrence: http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/291/consoleText

`2018-01-12 13:36:46.878040 I | Only received 199 out of 201 expected changes.  Attempt 10 / 10.`
`--- FAIL: TestUserAccessRace (35.28s)
	admin_api_test.go:393: Giving up trying to receive 201 changes.  Only received 199`

**Comment by tleyden** [comment]
Might be related to https://github.com/couchbase/sync_gateway/issues/2068

**Comment by tleyden** [comment]
TODO: mark as walrus only, put a note on 2068 that should be re-enabled for couchbase server once 2068 is fixed.

**Comment by tleyden** [comment]
Just saw this again against Walrus in http://uberjenkins.sc.couchbase.com:8080/blue/organizations/jenkins/_sync-gateway_github_pipeline%2Fsync_gateway/detail/PR-3844/4/pipeline/:

```
2018-12-04 16:54:54.459652 I | Sending 2nd round of _bulk_docs

2018-12-04 16:54:54.498608 I | Invoking _changes?feed=continuous&since=&timeout=2000

--- FAIL: TestUserAccessRace (0.40s)

panic: runtime error: invalid memory address or nil pointer dereference [recovered]

	panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbabe0e]



goroutine 320 [running]:

testing.tRunner.func1(0xc00037dd00)

	/root/.gvm/gos/go1.11.2/src/testing/testing.go:792 +0x387

panic(0xcad5a0, 0x16f6030)

	/root/.gvm/gos/go1.11.2/src/runtime/panic.go:513 +0x1b9

github.com/couchbase/sync_gateway/rest.(*handler).checkAuth.func1(0xc0003d1cc0)

	/var/jenkins/workspace/ub_pipeline_sync_gateway_PR-3844/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:296 +0x3e

github.com/couchbase/sync_gateway/rest.(*handler).checkAuth(0xc0003d1cc0, 0xc000194900, 0x0, 0x0)

	/var/jenkins/workspace/ub_pipeline_sync_gateway_PR-3844/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:338 +0x3b3

github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc0003d1cc0, 0xdef9e0, 0x0, 0x0)

	/var/jenkins/workspace/ub_pipeline_sync_gateway_PR-3844/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:179 +0x37f

github.com/couchbase/sync_gateway/rest.makeHandler.func1(0xf5f8e0, 0xc0003a6580, 0xc00037c600)

	/var/jenkins/workspace/ub_pipeline_sync_gateway_PR-3844/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:88 +0x8a

net/http.HandlerFunc.ServeHTTP(0xc0005dad00, 0xf5f8e0, 0xc0003a6580, 0xc00037c600)

	/root/.gvm/gos/go1.11.2/src/net/http/server.go:1964 +0x44

github.com/gorilla/mux.(*Router).ServeHTTP(0xc00075f310, 0xf5f8e0, 0xc0003a6580, 0xc00037c600)

	/var/jenkins/workspace/ub_pipeline_sync_gateway_PR-3844/godeps/src/github.com/gorilla/mux/mux.go:114 +0xe0

github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0xf5f8e0, 0xc0003a6580, 0xc00037c300)

	/var/jenkins/workspace/ub_pipeline_sync_gateway_PR-3844/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:311 +0x6a8

net/http.HandlerFunc.ServeHTTP(0xc00049ff60, 0xf5f8e0, 0xc0003a6580, 0xc00037c300)

	/root/.gvm/gos/go1.11.2/src/net/http/server.go:1964 +0x44

github.com/couchbase/sync_gateway/rest.(*RestTester).Send(0xc0001e36c0, 0xc00037c300, 0xda840f)

	/var/jenkins/workspace/ub_pipeline_sync_gateway_PR-3844/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:295 +0x110

github.com/couchbase/sync_gateway/rest.TestUserAccessRace(0xc00037dd00)

	/var/jenkins/workspace/ub_pipeline_sync_gateway_PR-3844/godeps/src/github.com/couchbase/sync_gateway/rest/admin_api_test.go:427 +0x756

testing.tRunner(0xc00037dd00, 0xdf0288)

	/root/.gvm/gos/go1.11.2/src/testing/testing.go:827 +0xbf

created by testing.(*T).Run

	/root/.gvm/gos/go1.11.2/src/testing/testing.go:878 +0x353

FAIL	github.com/couchbase/sync_gateway/rest	2.189s

?   	github.com/couchbaselabs/sync-gateway-accel	[no test files]

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x905aa6]



goroutine 1 [running]:

expvar.(*Map).Set(0x0, 0xe10a4e, 0xe, 0xfc3ee0, 0x18f8780)

	/root/.gvm/gos/go1.11.2/src/expvar/expvar.go:158 +0x46

github.com/couchbaselabs/sync-gateway-accel/indexwriter.init.1()

	/var/jenkins/workspace/ub_pipeline_sync_gateway_PR-3844/godeps/src/github.com/couchbaselabs/sync-gateway-accel/indexwriter/kv_change_index_writer.go:87 +0xc6

FAIL	github.com/couchbaselabs/sync-gateway-accel/indexwriter	0.019s

?   	github.com/couchbaselabs/sync-gateway-accel/sg_accel	[no test files]

```

**Comment by adamcfraser** [comment]
Closing based on age.
