### ISSUE TITLE
Sporadic test failure: TestChangeIndexAddSet

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3008]
@## TestChangeIndexAddSet

### Repro

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration/31/console

### Logs

```
=== RUN   TestChangeIndexAddSet
panic: Accessing closed Walrus bucket "test_indexbucket-06cd015a7eb38b5da34454c01e419b81"

goroutine 5039 [running]:
panic(0xc18720, 0xc42166a320)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbaselabs/walrus.(*WalrusBucket).assertNotClosed(0xc42105c1b0)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbaselabs/walrus/crud.go:192 +0x104
github.com/couchbaselabs/walrus.(*WalrusBucket).missingError(0xc42105c1b0, 0xc42166a2f0, 0x10, 0x10, 0x1474ea0)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbaselabs/walrus/crud.go:197 +0x2f
github.com/couchbaselabs/walrus.(*WalrusBucket).getRaw(0xc42105c1b0, 0xc42166a2f0, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbaselabs/walrus/crud.go:219 +0x13b
github.com/couchbaselabs/walrus.(*WalrusBucket).GetRaw(0xc42105c1b0, 0xc42166a2f0, 0x10, 0xc0c7a0, 0xc4216a2300, 0x1, 0x0, 0x11ac360, 0xc42166a300)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbaselabs/walrus/crud.go:225 +0x5a
github.com/couchbase/sync_gateway/base.(*LeakyBucket).GetRaw(0xc4202e2640, 0xc42166a2f0, 0x10, 0x0, 0x0, 0x18, 0xc0c7a0, 0xc4216a2300, 0x1)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/base/leaky_bucket.go:45 +0x4e
github.com/couchbase/sync_gateway/base.WriteCasRaw(0x11be600, 0xc4202e2640, 0xc42166a2f0, 0x10, 0xc4216ac500, 0x416, 0x489, 0x18, 0x0, 0xc420763cf8, ...)
	/var/jenkins/workspace/sync-gateway-integration/godeps/src/github.com/couchbase/sync_gateway/base/bucket.go:552 +0x77
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*ChannelWriter).writeClockCas(0xc42045efc0, 0xc4207ab600, 0x40, 0x40, 0x50a500, 0x59e90e3b, 0xe3a835)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/channel_writer.go:218 +0x34c
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*ChannelWriter).updateChannelClock(0xc42045efc0, 0xc4207ab600, 0x40, 0x40, 0xc4207ab600, 0x40, 0x40)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/channel_writer.go:113 +0x65
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*ChannelWriter).AddSet(0xc42045efc0, 0xc42050c000, 0x2, 0x7d0, 0x0, 0x0)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/channel_writer.go:61 +0x347
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*KvChangeIndexWriter).addSetToChannelIndex(0xc4216e00f0, 0xc42004a75b, 0x3, 0xc42050c000, 0x2, 0x7d0, 0x400, 0x400)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/kv_change_index_writer.go:971 +0x130
github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*KvChangeIndexWriter).indexEntries.func2(0xc42166a150, 0xc4216e00f0, 0xc42004a75b, 0x3, 0xc42050c000, 0x2, 0x7d0, 0xc400000000)
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/kv_change_index_writer.go:861 +0xd8
created by github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*KvChangeIndexWriter).indexEntries
	github.com/couchbaselabs/sync-gateway-accel/indexwriter/_test/_obj_test/kv_change_index_writer.go:868 +0x13e6
exit status 2
FAIL	github.com/couchbaselabs/sync-gateway-accel/indexwriter	21.010s
exit status 1
```

**Comment by tleyden** [comment]
- What operation is happening -- from there figure out why this is happening after the index bucket is closed.
- Check the order of closing the bucket
- Number of async processes in sg accel

**Comment by adamcfraser** [comment]
Equivalent stack trace is reliably reproducible running this locally:
```
./test.sh -v -race -run=TestChangeIndexCompact
```
