### ISSUE TITLE
TestBulkDocsUnusedSequencesMultiRevDoc / TestBulkDocsUnusedSequencesMultiRevDoc2SG  fails with XATTRS=true

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3010]
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/64/console

```
may want to re-sync the database to update these.
2017-10-30T16:00:30.586-07:00 Using default sync function 'channel(doc.channels)' for database "db"
2017-10-30T16:00:30.588-07:00 HTTP:  #265: POST http://localhost/db/_bulk_docs

	api_test.go:966
	assert.Equals(t, doc1Rev2.Sequence, uint64(7))	

	expected: 0x7
	     got: 0x0
2017-10-30T16:00:30.601-07:00 HTTP:  #266: POST http://localhost/db/_bulk_docs
2017-10-30T16:00:30.602-07:00 Cache: Received #7 after   9ms ("bulk1" / "2-d2111723d973efbcc415aab0ade25a45")
2017-10-30T16:00:30.602-07:00 Cache:   Deferring #7 (1 now waiting for #3...#6)
2017-10-30T16:00:30.602-07:00 	BulkDocs: Doc "bulk1" --> 409 Document exists (409 Document exists)

	api_test.go:982
	assert.Equals(t, doc1Rev3.Sequence, uint64(8))	

	expected: 0x8
	     got: 0x7

	api_test.go:986
	assert.Equals(t, len(rs), 3)	

	expected: 3
	     got: 2
2017-10-30T16:00:30.602-07:00 Changes+: changeListener.Stop() called
2017-10-30T16:00:30.602-07:00 Changes+: changeListener.Stop() called
--- FAIL: TestBulkDocsUnusedSequencesMultiRevDoc (6.99s)
	assert.go:31: 
	assert.go:31: 
	assert.go:31: 
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 4118 [running]:
testing.tRunner.func1(0xc420b102d0)
	/root/.gvm/gos/go1.9.2/src/testing/testing.go:711 +0x2d2
panic(0xbc6800, 0x12a16b0)
	/root/.gvm/gos/go1.9.2/src/runtime/panic.go:491 +0x283
github.com/couchbase/sync_gateway/rest.TestBulkDocsUnusedSequencesMultiRevDoc(0xc420b102d0)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/api_test.go:989 +0x12d8
testing.tRunner(0xc420b102d0, 0xce3a98)
	/root/.gvm/gos/go1.9.2/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/root/.gvm/gos/go1.9.2/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/couchbase/sync_gateway/rest	214.303s
```

**Comment by tleyden** [comment]
## TestBulkDocsUnusedSequencesMultiRevDoc2SG

In http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/66/consoleFull:

```
a69b6e0644577af07d30a6b5c3d00fd7 _id:bulk2] -- db.(*Database).getChannelsAndAccess() at crud.go:1206
2017-10-30T17:25:00.440-07:00 	BulkDocs: Doc "bulk2" --> 500 Exception in JS sync function (500 Exception in JS sync function)
2017-10-30T17:25:00.440-07:00 Cache: Received #2 after   0ms ("bulk3" / "1-bfa09fe957e5e28b750cff0568b1cb05")
2017-10-30T17:25:00.440-07:00 Cache:     #2 ==> channel "*"
2017-10-30T17:25:00.440-07:00 Changes+: Notifying that "test_data_bucket" changed (keys="{*}") count=5
2017-10-30T17:25:00.442-07:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2017-10-30T17:25:00.442-07:00 Opening db /db as bucket "test_data_bucket", pool "default", server <http://integration-cbs.sc.couchbase.com:8091>
2017-10-30T17:25:00.442-07:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs.sc.couchbase.com:8091> as user "test_data_bucket"
2017-10-30T17:25:00.813-07:00 Cache: Initializing changes cache with options {ChannelCacheOptions:{ChannelCacheMinLength:0 ChannelCacheMaxLength:0 ChannelCacheAge:0s} CachePendingSeqMaxWait:5s CachePendingSeqMaxNum:10000 CacheSkippedSeqMaxWait:1h0m0s}
2017-10-30T17:25:00.833-07:00 **NOTE:** "db"'s sync function has changed. The new function may assign different channels to documents, or permissions to users. You may want to re-sync the database to update these.
2017-10-30T17:25:00.833-07:00 Using default sync function 'channel(doc.channels)' for database "db"
2017-10-30T17:25:00.834-07:00 HTTP:  #267: POST http://localhost/db/_bulk_docs

	api_test.go:1056
	assert.Equals(t, doc1Rev2.Sequence, uint64(7))	

	expected: 0x7
	     got: 0x0
2017-10-30T17:25:00.842-07:00 Changes+: changeListener.Stop() called
2017-10-30T17:25:00.842-07:00 Changes+: changeListener.Stop() called
--- FAIL: TestBulkDocsUnusedSequencesMultiRevDoc2SG (6.65s)
	assert.go:32: 
```
