### ISSUE TITLE
TestImport disabled integration test

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3031]
TestImport fails in integration mode

```
$ SG_TEST_BACKING_STORE=Couchbase SG_TEST_COUCHBASE_SERVER_URL=http://localhost:8091 SG_TEST_USE_XATTRS=true ./test.sh -run ^TestImport$
Testing code with 'go test' ...
Integration mode: forcing tests to run in serial across packages via -p 1 flag
Running Sync Gateway unit tests
?   	github.com/couchbase/sync_gateway	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/couchbase/sync_gateway/auth	0.018s
testing: warning: no tests to run
PASS
ok  	github.com/couchbase/sync_gateway/base	0.017s
testing: warning: no tests to run
PASS
ok  	github.com/couchbase/sync_gateway/channels	0.016s
=== RUN   TestImport
2017-11-06T16:39:57.033-08:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2017-11-06T16:39:57.034-08:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2017-11-06T16:39:57.034-08:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2017-11-06T16:40:04.122-08:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://localhost:8091> as user "test_data_bucket"
2017-11-06 16:40:04.683409 I | bucketDataSource.Start() called
2017-11-06T16:40:04.709-08:00 Using metadata purge interval of 3.00 days for tombstone compaction.

	database_test.go:1093
	assert.Equals(t, doc, (*document)(nil))

	expected: (*db.document)(nil)
	     got: &db.document{syncData:db.syncData{CurrentRev:"1-aaf42fd23fb6bf22fa340d113517c22b", NewestRev:"", Flags:0x0, Sequence:0x1, UnusedSequences:[]uint64(nil), RecentSequences:[]uint64{0x1}, History:db.RevTree{"1-aaf42fd23fb6bf22fa340d113517c22b":(*db.RevInfo)(0xc42006f020)}, Channels:channels.ChannelMap{}, Access:db.UserAccessMap(nil), RoleAccess:db.UserAccessMap(nil), Expiry:(*time.Time)(nil), Cas:"", TombstonedAt:0, UpstreamCAS:(*uint64)(nil), UpstreamRev:"", TimeSaved:time.Time{wall:0xbe785e192af05af8, ext:7690326123, loc:(*time.Location)(0x1b47c80)}, Deleted_OLD:false, addedRevisionBodies:[]string{}, removedRevisionBodyKeys:map[string]string{}}, _body:db.Body{"key1":1, "key2":"hi"}, rawBody:[]uint8(nil), ID:"alreadyHere1", Cas:0x14f4a6d945310000}
2017-11-06T16:40:04.721-08:00 WARNING: Error closing GoCB bucket: connection shut down. -- base.CouchbaseBucketGoCB.Close() at bucket_gocb.go:2065
--- FAIL: TestImport (7.69s)
	assert.go:31:
panic: interface conversion: error is nil, not *base.HTTPError [recovered]
	panic: interface conversion: error is nil, not *base.HTTPError

goroutine 5 [running]:
testing.tRunner.func1(0xc4201861e0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x15b27a0, 0xc42006a680)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/couchbase/sync_gateway/db.TestImport(0xc4201861e0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/database_test.go:1094 +0x6c8
testing.tRunner(0xc4201861e0, 0x16bbd78)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/couchbase/sync_gateway/db	7.713s
```

Original ticket: https://github.com/couchbase/sync_gateway/issues/2977

**Comment by adamcfraser** [comment]
This tests legacy import, so shouldn't be run in xattr mode.  Could be renamed to TestLegacyImport as well.
