### ISSUE TITLE
Panic when attempting to make invalid update to a conflicting document

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3048]
Steps to repro
1. Create a document
2. Update the document
3. Add a conflicting revision.  e.g. something like:
```
http --verbose PUT localhost:4985/default/conflictTest value=conflicted new_edits==false _revisions:='{"start":2, "ids":["conflicting_rev", "f6fa803508c40388de38c9f99729c835"]}'
```
4. Issue the same request again

Step 4 panics - it should just return a 409 conflict.

**Comment by adamcfraser** [comment]
Panic:
```
2017-11-08 13:37:36.970045 I | http: panic serving 127.0.0.1:61002: interface conversion: interface {} is nil, not string
goroutine 72 [running]:
net/http.(*conn).serve.func1(0xc420380320)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x1753800, 0xc420376480)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/couchbase/sync_gateway/rest.(*handler).handlePutDoc(0xc420380500, 0xc42000ca40, 0xc4203a4240)
	/Users/adam/Development/sgaccel_repo/godeps/src/github.com/couchbase/sync_gateway/rest/doc_api.go:282 +0x808
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc420380500, 0x185e370, 0x0, 0x0)
	/Users/adam/Development/sgaccel_repo/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:222 +0x2c4
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x1c7ddc0, 0xc4204a8380, 0xc420252100)
	/Users/adam/Development/sgaccel_repo/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:97 +0x80
net/http.HandlerFunc.ServeHTTP(0xc4204154a0, 0x1c7ddc0, 0xc4204a8380, 0xc420252100)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202a0550, 0x1c7ddc0, 0xc4204a8380, 0xc420252100)
	/Users/adam/Development/sgaccel_repo/godeps/src/github.com/gorilla/mux/mux.go:86 +0x1d3
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x1c7ddc0, 0xc4204a8380, 0xc420252100)
	/Users/adam/Development/sgaccel_repo/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:302 +0x64a
net/http.HandlerFunc.ServeHTTP(0xc42013f920, 0x1c7ddc0, 0xc4204a8380, 0xc420252100)
	/usr/local/go/src/net/http/server.go:1918 +0x44
net/http.serverHandler.ServeHTTP(0xc42008c000, 0x1c7ddc0, 0xc4204a8380, 0xc420252100)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420380320, 0x1c7e840, 0xc420091fc0)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by tleyden** [comment]
I have a repro test case, and now looking into a fix.

Should this return an error?  Something like this:

```
{"error":"Internal Server Error","reason":"Internal error: No revision was created"}
```

**Comment by adamcfraser** [comment]
It should just be a standard 409/conflict error, I think.

**Comment by tleyden** [comment]
@snej what would be the expected behavior if a conflicting revision were added twice by Couchbase Lite?

Eg, the equivalent of this request:

```
http --verbose PUT localhost:4985/default/conflictTest value=conflicted new_edits==false _revisions:='{"start":2, "ids":["conflicting_rev", "f6fa803508c40388de38c9f99729c835"]}'

```

repeated twice.

If Sync Gateway returned a 409 Conflict error, would this be a problem?  Or would the expected behavior be a "no-op" and just return the same value as the first response?

**Comment by tleyden** [comment]
@snej @adamcfraser I compared the behavior to CouchDB -- it's a "no-op" and it returns the exact same response on subsequent new_edits=false requests.

**Comment by tleyden** [comment]
@adamcfraser the early return looks like it was here:

https://github.com/couchbase/sync_gateway/blob/master/db/crud.go#L673-L676

I fixed this by setting the outgoing `_rev` to the incoming revId in that case.
