### ISSUE TITLE
Sporadic test failure: TestChannelAccessChanges (integration test mode)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3069]
In http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/107/console:

```
2017-11-14T11:40:53.357-08:00 Changes+: MultiChangesFeed sending {Seq:4, ID:gamma, Changes:[map[rev:1-4ceecff40b4726ca5e5ecddc2d988963]]}   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: Channel feed processing seq:5 in channel beta   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: Channel feed processing seq:6 in channel beta   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: Channel feed processing seq:7 in channel beta   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: MultiChangesFeed sending {Seq:5, ID:a1, Changes:[map[rev:1-f2c898cf01dd5f572ac9b28d58ba7d4b]]}   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: MultiChangesFeed sending {Seq:6, ID:b1, Changes:[map[rev:1-7dcf5f78478f92454f1d0b359f204cbc]]}   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: MultiChangesFeed sending {Seq:7, ID:d1, Changes:[map[rev:1-d1ece69976d8cb66ff2a77210094db7c]]}   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: Channel feed processing seq:8 in channel beta   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: Channel feed processing seq:9 in channel beta   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: Channel feed processing seq:10 in channel beta   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: MultiChangesFeed sending {Seq:8, ID:g1, Changes:[map[rev:1-97023f8d0f6031c1587c483ff7f5a2ac]]}   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: MultiChangesFeed sending {Seq:9, ID:alpha, Changes:[map[rev:2-c3bcc88e1ec141c7c74f9b73d8363007]]}   (to alice)
2017-11-14T11:40:53.357-08:00 Changes+: Found sequence later than stable sequence: stable:[9] entry:[10] (epsilon)
2017-11-14T11:40:53.357-08:00 Changes: MultiChangesFeed done   (to alice)
2017-11-14 11:40:53.357770 I | _changes looks like: {"results":[
{"seq":2,"id":"beta","changes":[{"rev":"1-ffe7f169bea54c435a7ca90bccf7ab95"}]}
,{"seq":3,"id":"delta","changes":[{"rev":"1-742d9f0eb1f4fa613be657819a5df5a2"}]}
,{"seq":4,"id":"gamma","changes":[{"rev":"1-4ceecff40b4726ca5e5ecddc2d988963"}]}
,{"seq":5,"id":"a1","changes":[{"rev":"1-f2c898cf01dd5f572ac9b28d58ba7d4b"}]}
,{"seq":6,"id":"b1","changes":[{"rev":"1-7dcf5f78478f92454f1d0b359f204cbc"}]}
,{"seq":7,"id":"d1","changes":[{"rev":"1-d1ece69976d8cb66ff2a77210094db7c"}]}
,{"seq":8,"id":"g1","changes":[{"rev":"1-97023f8d0f6031c1587c483ff7f5a2ac"}]}
,{"seq":9,"id":"alpha","changes":[{"rev":"2-c3bcc88e1ec141c7c74f9b73d8363007"}]}
],
"last_seq":"9"}

	api_test.go:1805
	assert.Equals(t, len(changes.Results), len(expectedIDs))	

	expected: 9
	     got: 8
2017-11-14T11:40:53.358-08:00 Changes+: changeListener.Stop() called
--- FAIL: TestChannelAccessChanges (9.88s)
	assert.go:31: 
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 9584 [running]:
testing.tRunner.func1(0xc4216ce3c0)
	/root/.gvm/gos/go1.9.2/src/testing/testing.go:711 +0x2d2
panic(0xbcbea0, 0x12aa6f0)
	/root/.gvm/gos/go1.9.2/src/runtime/panic.go:491 +0x283
github.com/couchbase/sync_gateway/rest.TestChannelAccessChanges(0xc4216ce3c0)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/api_test.go:1809 +0x2ad9
testing.tRunner(0xc4216ce3c0, 0xcea0f0)
	/root/.gvm/gos/go1.9.2/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/root/.gvm/gos/go1.9.2/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/couchbase/sync_gateway/rest	336.879s
```

**Comment by tleyden** [comment]
More failures:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/153/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/152/

**Comment by tleyden** [comment]
@adamcfraser can you shed some more light on this code in the test:


https://github.com/couchbase/sync_gateway/blob/master/rest/api_test.go#L1781-L1782

```
// Wait for change caching to complete before running resync below
time.Sleep(500 * time.Millisecond)
```

Since it's already checking the changes feed for the arrival of these entries, shouldn't it be safe to assume that it's already in the changes cache?   Or could it be that only some of the changes feed entries are checked on the changes feed, and this sleep is to wait for all entries?

**Comment by adamcfraser** [comment]
It's been a while, but I'm guessing that there was a data race between the cache processing this write:
https://github.com/couchbase/sync_gateway/blob/master/rest/api_test.go#L1779

...and the subsequent resync.

In real world usage this wouldn't be possible, since the DB has to be taken offline before a resync.  I don't think the same is possible in this test (see the ephemeral bucket comment), but you could try switching to changeCache.waitForSequence if you think there's a timing problem.
