### ISSUE TITLE
Sporadic integration test error: Could not open bucket: Unrecoverable GoCB error calling Stats(): operation has timed out

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3134]
In http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/240/console:

```
2017-12-11T10:32:53.686-08:00 Using xattrs: strings.ToLower(useXattrs) == strings.ToLower(TestEnvSyncGatewayTrue).  |true| == |true|
2017-12-11T10:32:55.709-08:00 WARNING: TestBucketManager.EmptyBucket(): still 20 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:328
2017-12-11T10:32:56.216-08:00 WARNING: TestBucketManager.EmptyBucket(): still 20 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:328
2017-12-11T10:32:56.724-08:00 WARNING: TestBucketManager.EmptyBucket(): still 20 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:328
2017-12-11T10:32:57.232-08:00 WARNING: TestBucketManager.EmptyBucket(): still 20 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:328
2017-12-11T10:32:57.743-08:00 WARNING: TestBucketManager.EmptyBucket(): still 20 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:328
2017-12-11T10:32:58.251-08:00 WARNING: TestBucketManager.EmptyBucket(): still 20 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:328
2017-12-11T10:32:58.758-08:00 WARNING: TestBucketManager.EmptyBucket(): still 20 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:328
2017-12-11T10:32:59.265-08:00 WARNING: TestBucketManager.EmptyBucket(): still 20 items in bucket after flush, waiting for no items.  Will retry. -- base.(*TestBucketManager).EmptyTestBucket() at util_testing.go:328
2017-12-11T10:32:59.771-08:00 GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs.sc.couchbase.com:8091> as user "test_data_bucket"
--- FAIL: TestNoPanicInvalidUpdate (8.61s)
panic: Could not open bucket: Unrecoverable GoCB error calling Stats(): operation has timed out [recovered]
	panic: Could not open bucket: Unrecoverable GoCB error calling Stats(): operation has timed out

goroutine 19 [running]:
testing.tRunner.func1(0xc4201ec0f0)
	/root/.gvm/gos/go1.9.2/src/testing/testing.go:711 +0x2d2
panic(0xb99f60, 0xc4202ce7d0)
	/root/.gvm/gos/go1.9.2/src/runtime/panic.go:491 +0x283
github.com/couchbase/sync_gateway/base.GetBucketOrPanicCommon(0x0, 0xc4201aa690, 0x7f163fd17758)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/base/util_testing.go:140 +0x4c5
github.com/couchbase/sync_gateway/base.GetTestBucketOrPanic(0xc4201b2560, 0x20)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/base/util_testing.go:48 +0x2a
github.com/couchbase/sync_gateway/rest.(*RestTester).Bucket(0xc4201cc420, 0x448377, 0xc42003ad48)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:44 +0x6e
github.com/couchbase/sync_gateway/rest.(*RestTester).ServerContext(0xc4201cc420, 0x1)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:132 +0x2b
github.com/couchbase/sync_gateway/rest.(*RestTester).TestAdminHandler(0xc4201cc420, 0xc4201ac490, 0xc4201aa6c0)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:234 +0x54
github.com/couchbase/sync_gateway/rest.(*RestTester).SendAdminRequest(0xc4201cc420, 0xcb7757, 0x3, 0xc4201b0400, 0x10, 0xcc5a75, 0x13, 0xededc8)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:307 +0x25c
github.com/couchbase/sync_gateway/rest.TestNoPanicInvalidUpdate(0xc4201ec0f0)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/admin_api_test.go:41 +0x165
testing.tRunner(0xc4201ec0f0, 0xcfd208)
	/root/.gvm/gos/go1.9.2/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/root/.gvm/gos/go1.9.2/src/testing/testing.go:789 +0x2de
FAIL	github.com/couchbase/sync_gateway/rest	8.616s
```

It looks like this code could be modified to do a retry loop and retry on temporary errors:

```
func (bucket CouchbaseBucketGoCB) CouchbaseServerVersion() (major uint64, minor uint64, micro string, err error) {

	if versionString == "" {
		stats, err := bucket.Bucket.Stats("")
		if err != nil {
			return 0, 0, "error", pkgerrors.Wrapf(err, "Unrecoverable GoCB error calling Stats()")
		}

		for _, serverMap := range stats {
			versionString = serverMap["version"]
			// We only check the version of the first server, hopefully same for whole cluster
			break
		}
	}

	return ParseCouchbaseServerVersion(versionString)

}
```

**Comment by adamcfraser** [comment]
It's particularly misleading that it reports "unrecoverable gocb error" without checking whether it's in recoverableGoCBErrors.

It might make sense to put the retry in a helper method for the Stats call (instead of having CouchbaseServerVersion do the retry).

**Comment by tleyden** [comment]
Closing this issue, as the `dev` branch has no known sporadic failures.

Recent clean runs:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/724/parameters/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/723/parameters/
