### ISSUE TITLE
Integration test timeout in TestContinuousChangesSubscription

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3268]
The integration tests timed out after 30 minutes when running `TestContinuousChangesSubscription`

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/366

**Comment by adamcfraser** [comment]
Looks like this test will potentially deadlock in a failure scenario (based on 	receviedChangesWg.Wait()).

**Comment by tleyden** [comment]
> Looks like this test will potentially deadlock in a failure scenario (based on receviedChangesWg.Wait()).

Good point.  Yeah, it will block until the test is killed due to timeouts.

I will change it to timeout after a few minutes.

One noteworthy thing from the [logs](https://gist.github.com/tleyden/e4868e1b804582d11fa3675e89faeb78#file-gistfile1-txt-L8965-L8966):

```
2018-02-02T07:54:32.275-08:00 HTTP: [2545bcd4] #3673:     --&gt; BLIP+WebSocket connection error: Bogus message number 733 in response.  Expected to be less than max pending response number (732)
2018-02-02T07:54:32.275-08:00 HTTP+: [2545bcd4] #3673:    --&gt; BLIP+WebSocket connection closed
```

So it looks like it might be related to https://github.com/couchbase/sync_gateway/issues/3221

**Comment by adamcfraser** [comment]
Per @tleyden, this looks like it's not just down to the waitGroup, but it's actually sendRev that's blocking when Sync Gateway hits the 'bogus message' error and closes the connection (#3221).

The go-blip client code (used by the test framework) needs to be enhanced to not block on server error/dropped connection.

**Comment by tleyden** [comment]
After the upcoming go-blip PR is merged, here is how the test should look when it fails due to the [Bogus message issue](https://github.com/couchbase/sync_gateway/issues/3221):

```
2018-02-06T16:19:53.784-08:00 Sync: [a3254d0] Sent 1 changes to client, from seq 50897.  User:GUEST
2018-02-06T16:19:53.784-08:00 Sync+: [a3254d0]     Sending 0 changes. User:GUEST
2018-02-06T16:19:53.784-08:00 Sync+: [a3254d0]     Sending 1 changes. User:GUEST
2018-02-06T16:19:53.784-08:00 Sync: [a3254d0] Sent 1 changes to client, from seq 50898.  User:GUEST
2018-02-06T16:19:53.784-08:00 Sync+: [a3254d0]     Sending 0 changes. User:GUEST
2018-02-06T16:19:53.784-08:00 Sync+: [a3254d0]     Sending 1 changes. User:GUEST
2018-02-06T16:19:53.785-08:00 Sync: [a3254d0] Sent 1 changes to client, from seq 50899.  User:GUEST
2018-02-06T16:19:53.785-08:00 Sync+: [a3254d0]     Sending 0 changes. User:GUEST
2018-02-06T16:19:53.785-08:00 Sync+: [a3254d0]     Sending 1 changes. User:GUEST
2018-02-06T16:19:53.785-08:00 Sync: [a3254d0] Sent 1 changes to client, from seq 50900.  User:GUEST
2018-02-06T16:19:53.785-08:00 Sync+: [a3254d0]     Sending 0 changes. User:GUEST
2018-02-06T16:19:53.786-08:00 Sync+: [a3254d0]     Sending 1 changes. User:GUEST
2018-02-06T16:19:53.786-08:00 HTTP: [a3254d0] #001:     --> BLIP+WebSocket connection error: Bogus message number 26628 in response.  Expected to be less than max pending response number (26627)
2018-02-06T16:19:53.786-08:00 HTTP+: [a3254d0] #001:    --> BLIP+WebSocket connection closed
--- FAIL: TestContinuousChangesSubscription (20.80s)
panic: Failed to send revRequest for doc: foo-50953 [recovered]
	panic: Failed to send revRequest for doc: foo-50953

goroutine 6 [running]:
testing.tRunner.func1(0xc4201821e0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x17c3ea0, 0xc420f5cad0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/couchbase/sync_gateway/rest.(*BlipTester).SendRev(0xc42013fdc0, 0xc422b09640, 0x9, 0x18e77c6, 0x5, 0xc422b09670, 0xe, 0x10, 0x1b14501, 0xc4207c7dd0, ...)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:675 +0x787
github.com/couchbase/sync_gateway/rest.TestContinuousChangesSubscription(0xc4201821e0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/blip_api_test.go:220 +0x648
testing.tRunner(0xc4201821e0, 0x192e518)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/couchbase/sync_gateway/rest	20.837s
```

**Comment by tleyden** [comment]
Integration tests:

* http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/384/ (single test, repeated)
* http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/385/ (full suite)
