### ISSUE TITLE
Tests should use same settings for 2nd buckets (TestBulkDocsUnusedSequencesMultipleSG)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3481]
`TestBulkDocsUnusedSequencesMultipleSG ` [failed](http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/519/console) w/ error:

```
2018-04-19T11:16:12.284-07:00 [INF] GoCBCustomSGTranscoder Opening Couchbase database test_data_bucket on <http://integration-cbs-55.sc.couchbase.com:8091> as user "test_data_bucket"
2018-04-19T11:16:12.296-07:00 Initializing indexes with numReplicas: 0
2018-04-19T11:20:58.058-07:00 [WRN] RetryLoop for GetIndexMeta for index sg_access_x1 giving up after 26 attempts -- base.RetryLoop() at util.go:342
--- FAIL: TestBulkDocsUnusedSequencesMultipleSG (287.91s)
panic: Error from AddDatabaseFromConfig: Unable to install index access: RetryLoop for GetIndexMeta for index sg_access_x1 giving up after 26 attempts [recovered]
	panic: Error from AddDatabaseFromConfig: Unable to install index access: RetryLoop for GetIndexMeta for index sg_access_x1 giving up after 26 attempts

goroutine 7 [running]:
testing.tRunner.func1(0xc4201a4820)
	/root/.gvm/gos/go1.8.5/src/testing/testing.go:622 +0x29d
panic(0xc61680, 0xc4202294b0)
	/root/.gvm/gos/go1.8.5/src/runtime/panic.go:489 +0x2cf
github.com/couchbase/sync_gateway/rest.(*RestTester).Bucket(0xc4201c3d50, 0xc420163e00, 0xc42004f360)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:110 +0x8f1
github.com/couchbase/sync_gateway/rest.(*RestTester).ServerContext(0xc4201c3d50, 0x1)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:158 +0x2b
github.com/couchbase/sync_gateway/rest.(*RestTester).TestPublicHandler(0xc4201c3d50, 0xc4201ce490, 0xc4201bc5d0)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:280 +0x54
github.com/couchbase/sync_gateway/rest.(*RestTester).Send(0xc4201c3d50, 0xc42017ee00, 0xd9af84)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:259 +0x12a
github.com/couchbase/sync_gateway/rest.(*RestTester).SendRequest(0xc4201c3d50, 0xd90d05, 0x4, 0xd9af84, 0xe, 0xdcd537, 0x6b, 0x0)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:237 +0x75
github.com/couchbase/sync_gateway/rest.TestBulkDocsUnusedSequencesMultipleSG(0xc4201a4820)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/api_test.go:840 +0x145
testing.tRunner(0xc4201a4820, 0xdda550)
	/root/.gvm/gos/go1.8.5/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/root/.gvm/gos/go1.8.5/src/testing/testing.go:697 +0x2ca
FAIL	github.com/couchbase/sync_gateway/rest	287.926s
``` 

It looks like it's failing because it's not creating the index w/ the correct number of replicas.  Originally noticed in https://github.com/couchbase/sync_gateway/pull/3333#issuecomment-382812646

**Comment by tleyden** [comment]
It looks like this was fixed in a one-off way in https://github.com/couchbase/sync_gateway/commit/4574325ab32998688d8145c994009e21b6e72ba3

Not sure if that was even supposed to make it into master, or just pushed by accident.  I can't find the PR associated with that change.

There are still other tests that create 2nd buckets, and which don't have the fix yet.  For example `TestBulkDocsUnusedSequencesMultiRevDoc`

I'm not able to repro a test failure by deleting the indexes on Couchbase Server and running `TestBulkDocsUnusedSequencesMultiRevDoc`, however I do see the following message in the logs:

```
2018-04-27T15:41:27.315-07:00 [INF] Initializing indexes with numReplicas: 0...
...
2018-04-27T15:41:36.504-07:00 [INF] Initializing indexes with numReplicas: 1...
```

where it's trying to initialize indexes with the wrong number of replicas, but most likely is a no-op since the index was already created with 0 replicas.

**Comment by tleyden** [comment]
Fixed in https://github.com/couchbase/sync_gateway/pull/3520
