### ISSUE TITLE
sgcollect_info fails when concatenated log files exceed 2GB

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3610]
When concatenating single or rotated log files, if the total size exceeds 2GB the final zip stage will fail. Need to either split into smaller files, or use an alternative zipping approach.

```
18:24 $ ls -l /tmp/sglog-20180529/
total 7979728
-rw-r--r--  1 benbrooks  wheel   770M 29 May 17:39 sg_debug-2018-05-29T13-09-21.823.log.gz
-rw-r--r--  1 benbrooks  wheel   770M 29 May 18:09 sg_debug-2018-05-29T13-10-21.823.log.gz
-rw-r--r--  1 benbrooks  wheel   770M 29 May 18:23 sg_debug-2018-05-29T13-11-21.823.log.gz
-rw-r--r--  1 benbrooks  wheel   770M 29 May 18:23 sg_debug-2018-05-29T13-12-21.823.log.gz
-rw-r--r--  1 benbrooks  wheel   770M 29 May 18:23 sg_debug-2018-05-29T13-13-21.823.log.gz
-rw-r--r--  1 benbrooks  wheel    49K 29 May 18:01 sg_debug.log
-rw-r--r--  1 benbrooks  wheel    65B 29 May 14:09 sg_error-2018-05-29T13-09-21.823.log.gz
-rw-r--r--  1 benbrooks  wheel    23B 29 May 14:10 sg_error-2018-05-29T13-10-57.915.log.gz
-rw-r--r--  1 benbrooks  wheel   123B 29 May 17:40 sg_error.log
-rw-r--r--  1 benbrooks  wheel   4.0K 29 May 14:09 sg_info-2018-05-29T13-09-21.822.log.gz
-rw-r--r--  1 benbrooks  wheel   769B 29 May 14:10 sg_info-2018-05-29T13-10-57.915.log.gz
-rw-r--r--  1 benbrooks  wheel    19K 29 May 18:01 sg_info.log
-rw-r--r--  1 benbrooks  wheel   252B 29 May 14:09 sg_warn-2018-05-29T13-09-21.822.log.gz
-rw-r--r--  1 benbrooks  wheel    23B 29 May 14:10 sg_warn-2018-05-29T13-10-57.915.log.gz
-rw-r--r--  1 benbrooks  wheel   673B 29 May 17:40 sg_warn.log




18:24 $ ./tools/sgcollect_info test-rotated3.zip
Using Sync Gateway URL: http://127.0.0.1:4985
uname (uname -a) - OK
time and TZ (date; date -u) - OK
ntp time (ntpdate -q pool.ntp.org || nc time.nist.gov 13 || netcat time.nist.gov 13) - OK
ntp peers (ntpq -p) - OK
raw /etc/sysconfig/clock (cat /etc/sysconfig/clock) - Exit code 1
raw /etc/timezone (cat /etc/timezone) - Exit code 1
sysctl settings (sysctl -a) - OK
Process list snapshot (top -l 1) - OK
Disk activity (iostat 1 10) - OK
Process list (ps -Aww -o user,pid,lwp,ppid,nlwp,pcpu,pri,nice,vsize,rss,tty,stat,wchan:12,start,bsdtime,command) - Exit code 1
Network configuration (ifconfig -a) - OK
Taking sample 2 after 10.000000 seconds - OK
Network status (netstat -anp || netstat -an) - OK
Network routing table (netstat -rn) - OK
Arp cache (arp -na) - OK
Raw /etc/hosts (cat /etc/hosts) - OK
Raw /etc/resolv.conf (cat /etc/resolv.conf) - OK
Raw /etc/nsswitch.conf (cat /etc/nsswitch.conf) - Exit code 1
Filesystem (df -ha) - OK
System activity reporter (sar 1 10) - Exit code 127
System paging activity (vmstat 1 10) - Exit code 127
System uptime (uptime) - OK
couchbase user definition (getent passwd couchbase) - Exit code 127
couchbase user limits (su couchbase -c "ulimit -a") - skipped (needs root privs)
couchbase user limits (su couchbase -c "ulimit -a") - skipped (needs root privs)
Interrupt status (intrstat 1 10) - Exit code 127
Processor status (mpstat 1 10) - Exit code 127
System log (cat /var/adm/messages) - Exit code 1
Kernel log buffer (dmesg -H || dmesg) - Exit code 1
Discovered from expvars: sg_binary_path=./sync_gateway sg_config_path=sg_config.json
Capturing rotated log file /tmp/sglog-20180529/sg_debug.log
Capturing compressed rotated log file /tmp/sglog-20180529/sg_debug-2018-05-29T13-12-21.823.log.gz
Capturing compressed rotated log file /tmp/sglog-20180529/sg_debug-2018-05-29T13-11-21.823.log.gz
Capturing compressed rotated log file /tmp/sglog-20180529/sg_debug-2018-05-29T13-10-21.823.log.gz
Capturing compressed rotated log file /tmp/sglog-20180529/sg_debug-2018-05-29T13-13-21.823.log.gz
Capturing compressed rotated log file /tmp/sglog-20180529/sg_debug-2018-05-29T13-09-21.823.log.gz
Capturing rotated log file /tmp/sglog-20180529/sg_warn.log
Capturing compressed rotated log file /tmp/sglog-20180529/sg_warn-2018-05-29T13-09-21.822.log.gz
Capturing compressed rotated log file /tmp/sglog-20180529/sg_warn-2018-05-29T13-10-57.915.log.gz
Capturing rotated log file /tmp/sglog-20180529/sg_error.log
Capturing compressed rotated log file /tmp/sglog-20180529/sg_error-2018-05-29T13-10-57.915.log.gz
Capturing compressed rotated log file /tmp/sglog-20180529/sg_error-2018-05-29T13-09-21.823.log.gz
Capturing rotated log file /tmp/sglog-20180529/sg_info.log
Capturing compressed rotated log file /tmp/sglog-20180529/sg_info-2018-05-29T13-10-57.915.log.gz
Capturing compressed rotated log file /tmp/sglog-20180529/sg_info-2018-05-29T13-09-21.822.log.gz
Contents of /home/sg_accel/logs/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sg_accel/logs/sync_gateway_access.log'
Exit code 1
Contents of /home/sync_gateway/logs/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sync_gateway/logs/sync_gateway_access.log'
Exit code 1
Contents of /var/log/sg_accel/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sg_accel/sync_gateway_access.log'
Exit code 1
Contents of /var/log/sync_gateway/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sync_gateway/sync_gateway_access.log'
Exit code 1
Contents of /Users/sync_gateway/logs/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sync_gateway/logs/sync_gateway_access.log'
Exit code 1
Contents of /Users/sg_accel/logs/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sg_accel/logs/sync_gateway_access.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs/sync_gateway_access.log'
Exit code 1
Contents of C:\Program Files\Couchbase\var\lib\couchbase\logs/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\var\\lib\\couchbase\\logs/sync_gateway_access.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway Accelerator\var\lib\couchbase\logs/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway Accelerator\\var\\lib\\couchbase\\logs/sync_gateway_access.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway\var\lib\couchbase\logs/sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway\\var\\lib\\couchbase\\logs/sync_gateway_access.log'
Exit code 1
Contents of /home/sg_accel/logs/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sg_accel/logs/sg_accel_error.log'
Exit code 1
Contents of /home/sync_gateway/logs/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sync_gateway/logs/sg_accel_error.log'
Exit code 1
Contents of /var/log/sg_accel/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sg_accel/sg_accel_error.log'
Exit code 1
Contents of /var/log/sync_gateway/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sync_gateway/sg_accel_error.log'
Exit code 1
Contents of /Users/sync_gateway/logs/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sync_gateway/logs/sg_accel_error.log'
Exit code 1
Contents of /Users/sg_accel/logs/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sg_accel/logs/sg_accel_error.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs/sg_accel_error.log'
Exit code 1
Contents of C:\Program Files\Couchbase\var\lib\couchbase\logs/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\var\\lib\\couchbase\\logs/sg_accel_error.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway Accelerator\var\lib\couchbase\logs/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway Accelerator\\var\\lib\\couchbase\\logs/sg_accel_error.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway\var\lib\couchbase\logs/sg_accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway\\var\\lib\\couchbase\\logs/sg_accel_error.log'
Exit code 1
Contents of /home/sg_accel/logs/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sg_accel/logs/sg_accel_access.log'
Exit code 1
Contents of /home/sync_gateway/logs/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sync_gateway/logs/sg_accel_access.log'
Exit code 1
Contents of /var/log/sg_accel/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sg_accel/sg_accel_access.log'
Exit code 1
Contents of /var/log/sync_gateway/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sync_gateway/sg_accel_access.log'
Exit code 1
Contents of /Users/sync_gateway/logs/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sync_gateway/logs/sg_accel_access.log'
Exit code 1
Contents of /Users/sg_accel/logs/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sg_accel/logs/sg_accel_access.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs/sg_accel_access.log'
Exit code 1
Contents of C:\Program Files\Couchbase\var\lib\couchbase\logs/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\var\\lib\\couchbase\\logs/sg_accel_access.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway Accelerator\var\lib\couchbase\logs/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway Accelerator\\var\\lib\\couchbase\\logs/sg_accel_access.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway\var\lib\couchbase\logs/sg_accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway\\var\\lib\\couchbase\\logs/sg_accel_access.log'
Exit code 1
Contents of /home/sg_accel/logs/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sg_accel/logs/sg_debug.log'
Exit code 1
Contents of /home/sync_gateway/logs/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sync_gateway/logs/sg_debug.log'
Exit code 1
Contents of /var/log/sg_accel/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sg_accel/sg_debug.log'
Exit code 1
Contents of /var/log/sync_gateway/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sync_gateway/sg_debug.log'
Exit code 1
Contents of /Users/sync_gateway/logs/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sync_gateway/logs/sg_debug.log'
Exit code 1
Contents of /Users/sg_accel/logs/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sg_accel/logs/sg_debug.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs/sg_debug.log'
Exit code 1
Contents of C:\Program Files\Couchbase\var\lib\couchbase\logs/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\var\\lib\\couchbase\\logs/sg_debug.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway Accelerator\var\lib\couchbase\logs/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway Accelerator\\var\\lib\\couchbase\\logs/sg_debug.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway\var\lib\couchbase\logs/sg_debug.log (pythontask) - log_file: sg_debug.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway\\var\\lib\\couchbase\\logs/sg_debug.log'
Exit code 1
Contents of /home/sg_accel/logs/sg_warn.log (pythontask) - log_file: sg_warn.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sg_accel/logs/sg_warn.log'
Exit code 1
Contents of /home/sync_gateway/logs/sg_warn.log (pythontask) - log_file: sg_warn.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sync_gateway/logs/sg_warn.log'
Exit code 1
Contents of /var/log/sg_accel/sg_warn.log (pythontask) - log_file: sg_warn.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sg_accel/sg_warn.log'
Exit code 1
Contents of /var/log/sync_gateway/sg_warn.log (pythontask) - log_file: sg_warn.log.
OK
Contents of /Users/sync_gateway/logs/sg_warn.log (pythontask) - log_file: sg_warn.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sync_gateway/logs/sg_warn.log'
Exit code 1
Contents of /Users/sg_accel/logs/sg_warn.log (pythontask) - log_file: sg_warn.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sg_accel/logs/sg_warn.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sg_warn.log (pythontask) - log_file: sg_warn.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs/sg_warn.log'
Exit code 1
Contents of C:\Program Files\Couchbase\var\lib\couchbase\logs/sg_warn.log (pythontask) - log_file: sg_warn.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\var\\lib\\couchbase\\logs/sg_warn.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway Accelerator\var\lib\couchbase\logs/sg_warn.log (pythontask) - log_file: sg_warn.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway Accelerator\\var\\lib\\couchbase\\logs/sg_warn.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway\var\lib\couchbase\logs/sg_warn.log (pythontask) - log_file: sg_warn.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway\\var\\lib\\couchbase\\logs/sg_warn.log'
Exit code 1
Contents of /home/sg_accel/logs/sg_error.log (pythontask) - log_file: sg_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sg_accel/logs/sg_error.log'
Exit code 1
Contents of /home/sync_gateway/logs/sg_error.log (pythontask) - log_file: sg_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sync_gateway/logs/sg_error.log'
Exit code 1
Contents of /var/log/sg_accel/sg_error.log (pythontask) - log_file: sg_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sg_accel/sg_error.log'
Exit code 1
Contents of /var/log/sync_gateway/sg_error.log (pythontask) - log_file: sg_error.log.
OK
Contents of /Users/sync_gateway/logs/sg_error.log (pythontask) - log_file: sg_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sync_gateway/logs/sg_error.log'
Exit code 1
Contents of /Users/sg_accel/logs/sg_error.log (pythontask) - log_file: sg_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sg_accel/logs/sg_error.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sg_error.log (pythontask) - log_file: sg_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs/sg_error.log'
Exit code 1
Contents of C:\Program Files\Couchbase\var\lib\couchbase\logs/sg_error.log (pythontask) - log_file: sg_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\var\\lib\\couchbase\\logs/sg_error.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway Accelerator\var\lib\couchbase\logs/sg_error.log (pythontask) - log_file: sg_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway Accelerator\\var\\lib\\couchbase\\logs/sg_error.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway\var\lib\couchbase\logs/sg_error.log (pythontask) - log_file: sg_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway\\var\\lib\\couchbase\\logs/sg_error.log'
Exit code 1
Contents of /home/sg_accel/logs/sg_info.log (pythontask) - log_file: sg_info.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sg_accel/logs/sg_info.log'
Exit code 1
Contents of /home/sync_gateway/logs/sg_info.log (pythontask) - log_file: sg_info.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sync_gateway/logs/sg_info.log'
Exit code 1
Contents of /var/log/sg_accel/sg_info.log (pythontask) - log_file: sg_info.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sg_accel/sg_info.log'
Exit code 1
Contents of /var/log/sync_gateway/sg_info.log (pythontask) - log_file: sg_info.log.
OK
Contents of /Users/sync_gateway/logs/sg_info.log (pythontask) - log_file: sg_info.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sync_gateway/logs/sg_info.log'
Exit code 1
Contents of /Users/sg_accel/logs/sg_info.log (pythontask) - log_file: sg_info.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sg_accel/logs/sg_info.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sg_info.log (pythontask) - log_file: sg_info.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs/sg_info.log'
Exit code 1
Contents of C:\Program Files\Couchbase\var\lib\couchbase\logs/sg_info.log (pythontask) - log_file: sg_info.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\var\\lib\\couchbase\\logs/sg_info.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway Accelerator\var\lib\couchbase\logs/sg_info.log (pythontask) - log_file: sg_info.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway Accelerator\\var\\lib\\couchbase\\logs/sg_info.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway\var\lib\couchbase\logs/sg_info.log (pythontask) - log_file: sg_info.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway\\var\\lib\\couchbase\\logs/sg_info.log'
Exit code 1
Contents of /home/sg_accel/logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sg_accel/logs/sync_gateway_error.log'
Exit code 1
Contents of /home/sync_gateway/logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/home/sync_gateway/logs/sync_gateway_error.log'
Exit code 1
Contents of /var/log/sg_accel/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sg_accel/sync_gateway_error.log'
Exit code 1
Contents of /var/log/sync_gateway/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/var/log/sync_gateway/sync_gateway_error.log'
Exit code 1
Contents of /Users/sync_gateway/logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sync_gateway/logs/sync_gateway_error.log'
Exit code 1
Contents of /Users/sg_accel/logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users/sg_accel/logs/sync_gateway_error.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs/sync_gateway_error.log'
Exit code 1
Contents of C:\Program Files\Couchbase\var\lib\couchbase\logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\var\\lib\\couchbase\\logs/sync_gateway_error.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway Accelerator\var\lib\couchbase\logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway Accelerator\\var\\lib\\couchbase\\logs/sync_gateway_error.log'
Exit code 1
Contents of C:\Program Files\Couchbase\Sync Gateway\var\lib\couchbase\logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Program Files\\Couchbase\\Sync Gateway\\var\\lib\\couchbase\\logs/sync_gateway_error.log'
Exit code 1
Contents of /tmp/sglog-20180529/sg_debug.log (pythontask) - log_file: sg_debug.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_debug-2018-05-29T13-12-21.823.log.gz (pythontask) - log_file: sg_debug.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_debug-2018-05-29T13-11-21.823.log.gz (pythontask) - log_file: sg_debug.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_debug-2018-05-29T13-10-21.823.log.gz (pythontask) - log_file: sg_debug.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_debug-2018-05-29T13-13-21.823.log.gz (pythontask) - log_file: sg_debug.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_debug-2018-05-29T13-09-21.823.log.gz (pythontask) - log_file: sg_debug.log.
OK
Contents of /tmp/sglog-20180529/sg_warn.log (pythontask) - log_file: sg_warn.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_warn-2018-05-29T13-09-21.822.log.gz (pythontask) - log_file: sg_warn.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_warn-2018-05-29T13-10-57.915.log.gz (pythontask) - log_file: sg_warn.log.
OK
Contents of /tmp/sglog-20180529/sg_error.log (pythontask) - log_file: sg_error.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_error-2018-05-29T13-10-57.915.log.gz (pythontask) - log_file: sg_error.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_error-2018-05-29T13-09-21.823.log.gz (pythontask) - log_file: sg_error.log.
OK
Contents of /tmp/sglog-20180529/sg_info.log (pythontask) - log_file: sg_info.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_info-2018-05-29T13-10-57.915.log.gz (pythontask) - log_file: sg_info.log.
OK
Extracted contents of /tmp/sglog-20180529/sg_info-2018-05-29T13-09-21.822.log.gz (pythontask) - log_file: sg_info.log.
OK
download_sg_expvars (pythontask) - log_file: expvars_json.log.
OK
Collect profile pprof via http client (pythontask) - log_file: pprof_http_profile.log.
OK
Collect heap pprof via http client (pythontask) - log_file: pprof_http_heap.log.
OK
Collect goroutine pprof via http client (pythontask) - log_file: pprof_http_goroutine.log.
OK
Running go tool pprof -- which can take several seconds: profile format: dot (go tool pprof -dot -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/profile) - OK
Running go tool pprof -- which can take several seconds: profile format: pdf (go tool pprof -pdf -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/profile) - OK
Running go tool pprof -- which can take several seconds: profile format: text (go tool pprof -text -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/profile) - OK
Running go tool pprof -- which can take several seconds: profile format: raw (go tool pprof -raw -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/profile) - OK
Running go tool pprof -- which can take several seconds: heap format: dot (go tool pprof -dot -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/heap) - OK
Running go tool pprof -- which can take several seconds: heap format: pdf (go tool pprof -pdf -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/heap) - OK
Running go tool pprof -- which can take several seconds: heap format: text (go tool pprof -text -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/heap) - OK
Running go tool pprof -- which can take several seconds: heap format: raw (go tool pprof -raw -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/heap) - OK
Running go tool pprof -- which can take several seconds: goroutine format: dot (go tool pprof -dot -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/goroutine) - OK
Running go tool pprof -- which can take several seconds: goroutine format: pdf (go tool pprof -pdf -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/goroutine) - OK
Running go tool pprof -- which can take several seconds: goroutine format: text (go tool pprof -text -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/goroutine) - OK
Running go tool pprof -- which can take several seconds: goroutine format: raw (go tool pprof -raw -seconds=5 "./sync_gateway" http://127.0.0.1:4985/_debug/pprof/goroutine) - OK
Contents of sg_config.json (pythontask) - log_file: sg_config.json.
OK
Collect server config (pythontask) - log_file: running_server_config.log.
OK
Collect db config for db: dbtwo (pythontask) - log_file: running_db_dbtwo_config.log.
OK
Collect server status (pythontask) - log_file: server_status.log.
OK
Collect db status for db: dbtwo (pythontask) - log_file: db_dbtwo_status.log.
OK
WARNING: unable to find Sync Gateway executable, omitting from result.  Go pprofs will not be accurate.
Echo sgcollect_info cmd line args (echo options: {'watch_stdin': False, 'just_upload_into': None, 'sync_gateway_config': None, 'redact_level': 'none', 'verbosity': 0, 'upload_host': None, 'sync_gateway_url': None, 'upload_customer': None, 'upload_ticket': None, 'salt_value': '1dbf0d96-8919-4538-9a92-f38ae09c353f', 'sync_gateway_executable': None, 'root': '/Users/benbrooks/dev/sync_gateway/master/godeps/src/github.com/couchbase/sync_gateway', 'product_only': False} args: ['test-rotated3.zip']) - OK
Exception during compression: [Errno 2] No such file or directory
IMPORTANT:
  Compression using gozip failed.
  Falling back to python implementation.
  Please let us know about this and provide console output.
Traceback (most recent call last):
  File "./tools/sgcollect_info", line 800, in <module>
    main()
  File "./tools/sgcollect_info", line 775, in main
    runner.zip(zip_filename, 'sgcollect_info', platform.node())
  File "/Users/benbrooks/dev/sync_gateway/master/godeps/src/github.com/couchbase/sync_gateway/tools/tasks.py", line 337, in zip
    self._zip_helper(prefix, filename, files)
  File "/Users/benbrooks/dev/sync_gateway/master/godeps/src/github.com/couchbase/sync_gateway/tools/tasks.py", line 368, in _zip_helper
    self._zip_fallback(filename, prefix, files)
  File "/Users/benbrooks/dev/sync_gateway/master/godeps/src/github.com/couchbase/sync_gateway/tools/tasks.py", line 376, in _zip_fallback
    "%s/%s" % (prefix, os.path.basename(name)))
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1148, in write
    self._writecheck(zinfo)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1114, in _writecheck
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Filesize would require ZIP64 extensions
```

**Comment by adamcfraser** [comment]
Build fix tracked as https://issues.couchbase.com/browse/MB-29889

**Comment by adamcfraser** [comment]
Fixed by https://issues.couchbase.com/browse/MB-29889, https://github.com/couchbase/sync_gateway/pull/3637
