### ISSUE TITLE
Deleting database via REST Admin API can cause panics

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3676]
Steps to repro:

1. Create a database with XATTRS enabled
1. Delete the database via Admin REST API 
1. Access the changes feed (or it's possible there must be a longpoll/blip changes feed already open)

Version:

* SG 2.0.0

Sync Gateway will panic with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x9af5db]

goroutine 28274 [running]:
github.com/couchbase/sync_gateway/db.(*DatabaseContext).GetDocWithXattr(0xc4202522c0, 0xc42ba83140, 0x16, 0x0, 0x73aeb9a284193100, 0x3, 0xc42001a050, 0xc42001a000)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:90 +0x4b
github.com/couchbase/sync_gateway/db.(*DatabaseContext).GetDocument(0xc4202522c0, 0xc42ba83140, 0x16, 0x0, 0x4, 0xc43dddc700, 0xc42013b0b0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:52 +0xce
github.com/couchbase/sync_gateway/db.(*DatabaseContext).revCacheLoader(0xc4202522c0, 0xc42ba83140, 0x16, 0xc486cf53b0, 0x22, 0x0, 0x10d3540, 0xc42015a388, 0xc45bfe8630, 0xc45bfe8628, ...)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:180 +0x48
github.com/couchbase/sync_gateway/db.(*DatabaseContext).(github.com/couchbase/sync_gateway/db.revCacheLoader)-fm(0xc42ba83140, 0x16, 0xc486cf53b0, 0x22, 0x0, 0xc42ba83140, 0x16, 0xc486cf53b0, 0x22, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/database.go:193 +0x55
github.com/couchbase/sync_gateway/db.(*revCacheValue).load(0xc479d8e840, 0xc42034d500, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/revision_cache.go:144 +0x1e5
github.com/couchbase/sync_gateway/db.(*RevisionCache).Get(0xc420355500, 0xc42ba83140, 0x16, 0xc486cf53b0, 0x22, 0xc485fa5f80, 0xc485fa5f50, 0x0, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/revision_cache.go:58 +0x9b
github.com/couchbase/sync_gateway/db.(*Database).GetRevWithHistory(0xc429ed9c40, 0xc42ba83140, 0x16, 0xc486cf53b0, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:249 +0x8a
github.com/couchbase/sync_gateway/db.(*Database).AddDocToChangeEntryUsingRevCache(0xc429ed9c40, 0xc45d49cc30, 0xc486cf53b0, 0x22, 0xc4748cf948, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/changes.go:132 +0xb8
github.com/couchbase/sync_gateway/db.(*Database).addDocToChangeEntry(0xc429ed9c40, 0xc45d49cc30, 0x0, 0x0, 0x0, 0x74408f, 0x0, 0x0, 0x0, 0x0, ...)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/changes.go:122 +0x121
github.com/couchbase/sync_gateway/db.(*Database).SimpleMultiChangesFeed.func1(0x0, 0x0, 0xc4dc58a780, 0xc429ed9c40, 0xc43aba43c0, 0xc439037fb0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/changes.go:605 +0x1b27
created by github.com/couchbase/sync_gateway/db.(*Database).SimpleMultiChangesFeed
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/db/changes.go:700 +0x237
```

## Possible cause

This code in `database.go` sets the database context bucket to nil

```
func (context *DatabaseContext) Close() {
	context.BucketLock.Lock()
	defer context.BucketLock.Unlock()

	context.mutationListener.Stop()
	context.changeCache.Stop()
	context.Shadower.Stop()
	context.Bucket.Close()
	context.Bucket = nil
}
```

but this code in `crud.go` does not check that the db context might be holding a nil reference to the bucket:

```
func (db *DatabaseContext) GetDocWithXattr(key string, unmarshalLevel DocumentUnmarshalLevel) (doc *document, rawBucketDoc *sgbucket.BucketDocument, err error) {
	rawBucketDoc = &sgbucket.BucketDocument{}
	var getErr error
	rawBucketDoc.Cas, getErr = db.Bucket.GetWithXattr(key, KSyncXattrName, &rawBucketDoc.Body, &rawBucketDoc.Xattr)
```

**Comment by adamcfraser** [comment]
If it's the latter, having an in-flight request panic because the database is closed underneath it may not be ideal, but it's not unreasonable.

**Comment by tleyden** [comment]
Agreed about not having nil checks sprinkled everywhere.  Why does the call have to be concurrent with a `db.Close()`?  Are you saying that after the `db.Close()` completes, it would be in state that any incoming requests would be rejected?

Maybe it's a changes worker/listener that was running before the `db.Close()` but isn't being closed down properly?  I forgot to mention that his is SG version 2.0.0.

**Comment by tleyden** [comment]
This can only happen w/ concurrent in-flight requests, and therefore is not higher priority enough to fix right now.
