### ISSUE TITLE
Sporadic failures in integration tests

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3853]
* [TestNoPanicInvalidUpdate](https://github.com/couchbase/sync_gateway/issues/3853#issuecomment-444739501)
* [TestN1qlQuery](https://github.com/couchbase/sync_gateway/issues/3853#issuecomment-444739878)
* [TestN1qlFilterExpression](https://github.com/couchbase/sync_gateway/issues/3853#issuecomment-444740895)

**Comment by tleyden** [comment]
### TestNoPanicInvalidUpdate / [5000]  Indexer In Warmup State. Please retry the request later

Can be seen in:
- http://uberjenkins.sc.couchbase.com:8080/view/Build/job/sync-gateway-integration-master/917/consoleFull


<details>
  <summary>Click to view full race stack trace

```
--- FAIL: TestNoPanicInvalidUpdate (2.16s)
panic: Error from AddDatabaseFromConfig: [5000]  Indexer In Warmup State. Please retry the request later. from [127.0.0.1:9101] - cause:  Indexer In Warmup State. Please retry the request later. from [127.0.0.1:9101] [recovered]
	panic: Error from AddDatabaseFromConfig: [5000]  Indexer In Warmup State. Please retry the request later. from [127.0.0.1:9101] - cause:  Indexer In Warmup State. Please retry the request later. from [127.0.0.1:9101]

goroutine 20 [running]:
```
</summary>

```
--- FAIL: TestNoPanicInvalidUpdate (2.16s)
panic: Error from AddDatabaseFromConfig: [5000]  Indexer In Warmup State. Please retry the request later. from [127.0.0.1:9101] - cause:  Indexer In Warmup State. Please retry the request later. from [127.0.0.1:9101] [recovered]
	panic: Error from AddDatabaseFromConfig: [5000]  Indexer In Warmup State. Please retry the request later. from [127.0.0.1:9101] - cause:  Indexer In Warmup State. Please retry the request later. from [127.0.0.1:9101]

goroutine 20 [running]:
testing.tRunner.func1(0xc000226300)
	/root/.gvm/gos/go1.11.1/src/testing/testing.go:792 +0x387
panic(0xc35320, 0xc0001b3c70)
	/root/.gvm/gos/go1.11.1/src/runtime/panic.go:513 +0x1b9
github.com/couchbase/sync_gateway/rest.(*RestTester).Bucket(0xc000221ea0, 0xd33480, 0xc000054d60)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:130 +0xcaf
github.com/couchbase/sync_gateway/rest.(*RestTester).ServerContext(0xc000221ea0, 0xd33401)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:192 +0x2b
github.com/couchbase/sync_gateway/rest.(*RestTester).TestAdminHandler(0xc000221ea0, 0xc0001b2710, 0xc0001b82a0)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:307 +0x52
github.com/couchbase/sync_gateway/rest.(*RestTester).SendAdminRequest(0xc000221ea0, 0xd71ff6, 0x3, 0xc0001b6510, 0x10, 0xd81ae1, 0x13, 0x2e)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/utilities_testing.go:381 +0x203
github.com/couchbase/sync_gateway/rest.TestNoPanicInvalidUpdate(0xc000226300)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/rest/admin_api_test.go:42 +0x158
testing.tRunner(0xc000226300, 0xdc20d0)
	/root/.gvm/gos/go1.11.1/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/root/.gvm/gos/go1.11.1/src/testing/testing.go:878 +0x353
FAIL	github.com/couchbase/sync_gateway/rest	2.166s
```
</details>

**Comment by tleyden** [comment]
### TestN1qlQuery / Error: [5000] GSI CreateIndex()

Can be seen in:
- http://uberjenkins.sc.couchbase.com:8080/view/Build/job/sync-gateway-integration-master/917/consoleFull


<details>
  <summary>Click to view full race stack trace

```
--- FAIL: TestN1qlQuery (302.27s)
    bucket_n1ql_test.go:46: Error creating index: Error creating index with statement: CREATE INDEX `testIndex_value` ON `test_data_bucket`(val) with {}.  Error: [5000] GSI CreateIndex() - cause: Create index cannot proceed due to rebalance in progress, another concurrent create index request, network partition, node failover, or indexer failure.
    bucket_n1ql_test.go:53: Error waiting for index to come online: Error creating index with statement: CREATE INDEX `testIndex_value` ON `test_data_bucket`(val) with {}.  Error: [5000] GSI CreateIndex() - cause: Create index cannot proceed due to rebalance in progress, another concurrent create index request, network partition, node failover, or indexer failure.
    bucket_n1ql_test.go:59: 
```
</summary>

```
--- FAIL: TestN1qlQuery (302.27s)
    bucket_n1ql_test.go:46: Error creating index: Error creating index with statement: CREATE INDEX `testIndex_value` ON `test_data_bucket`(val) with {}.  Error: [5000] GSI CreateIndex() - cause: Create index cannot proceed due to rebalance in progress, another concurrent create index request, network partition, node failover, or indexer failure.
    bucket_n1ql_test.go:53: Error waiting for index to come online: Error creating index with statement: CREATE INDEX `testIndex_value` ON `test_data_bucket`(val) with {}.  Error: [5000] GSI CreateIndex() - cause: Create index cannot proceed due to rebalance in progress, another concurrent create index request, network partition, node failover, or indexer failure.
    bucket_n1ql_test.go:59: 
        	Error Trace:	bucket_n1ql_test.go:59
        	Error:      	Should be true
        	Test:       	TestN1qlQuery
        	Messages:   	No state returned for index
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x940406]

goroutine 893 [running]:
testing.tRunner.func1(0xc000398300)
	/root/.gvm/gos/go1.11.1/src/testing/testing.go:792 +0x387
panic(0xa1d1e0, 0x11654a0)
	/root/.gvm/gos/go1.11.1/src/runtime/panic.go:513 +0x1b9
github.com/couchbase/sync_gateway/base.TestN1qlQuery(0xc000398300)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/base/bucket_n1ql_test.go:60 +0x5d6
testing.tRunner(0xc000398300, 0xaf5830)
	/root/.gvm/gos/go1.11.1/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/root/.gvm/gos/go1.11.1/src/testing/testing.go:878 +0x353
FAIL	github.com/couchbase/sync_gateway/base	380.997s
```
</details>

**Comment by tleyden** [comment]
### TestN1qlFilterExpression / Error creating index

Can be seen in:
- http://uberjenkins.sc.couchbase.com:8080/view/Build/job/sync-gateway-integration-master/913/consoleFull


<details>
  <summary>Click to view full race stack trace

```
--- FAIL: TestN1qlFilterExpression (391.41s)
    bucket_n1ql_test.go:153: Error creating index: Error creating index with statement: CREATE INDEX `testIndex_filtered_value` ON `test_data_bucket`(val) WHERE val < 3 with {}.  Error: Post http://integration-cbs-55.sc.couchbase.com:8093/query/service: net/http: request canceled
```
</summary>

```
--- FAIL: TestN1qlFilterExpression (391.41s)
    bucket_n1ql_test.go:153: Error creating index: Error creating index with statement: CREATE INDEX `testIndex_filtered_value` ON `test_data_bucket`(val) WHERE val < 3 with {}.  Error: Post http://integration-cbs-55.sc.couchbase.com:8093/query/service: net/http: request canceled
    bucket_n1ql_test.go:158: 
        	Error Trace:	bucket_n1ql_test.go:158
        	Error:      	Received unexpected error:
        	            	RetryLoop for GetIndexMeta for index testIndex_filtered_value giving up after 26 attempts
        	Test:       	TestN1qlFilterExpression
        	Messages:   	Error validating index online
    bucket_n1ql_test.go:172: 
        	Error Trace:	bucket_n1ql_test.go:172
        	Error:      	Received unexpected error:
        	            	[4000] No index available on keyspace test_data_bucket that matches your query. Use CREATE INDEX or CREATE PRIMARY INDEX to create an index, or check that your expected index is online.
        	            	github.com/couchbase/sync_gateway/base.(*CouchbaseBucketGoCB).Query
        	            		/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/base/bucket_n1ql.go:64
        	            	github.com/couchbase/sync_gateway/base.TestN1qlFilterExpression
        	            		/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/base/bucket_n1ql_test.go:171
        	            	testing.tRunner
        	            		/root/.gvm/gos/go1.11.1/src/testing/testing.go:827
        	            	runtime.goexit
        	            		/root/.gvm/gos/go1.11.1/src/runtime/asm_amd64.s:1333
        	Test:       	TestN1qlFilterExpression
        	Messages:   	Error executing n1ql query
    bucket_n1ql_test.go:165: Error dropping index: [5000] GSI Drop() - cause: Fail to drop index on some indexer nodes.  Error=Terminate Request due to server termination
        .  If cluster or indexer is currently unavailable, the operation will automaticaly retry after cluster is back to normal.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x940be1]

goroutine 922 [running]:
testing.tRunner.func1(0xc000260400)
	/root/.gvm/gos/go1.11.1/src/testing/testing.go:792 +0x387
panic(0xa1c1e0, 0x11634a0)
	/root/.gvm/gos/go1.11.1/src/runtime/panic.go:513 +0x1b9
github.com/couchbase/sync_gateway/base.TestN1qlFilterExpression(0xc000260400)
	/var/jenkins/workspace/sync-gateway-integration-master/godeps/src/github.com/couchbase/sync_gateway/base/bucket_n1ql_test.go:184 +0x7e1
testing.tRunner(0xc000260400, 0xaf4540)
	/root/.gvm/gos/go1.11.1/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/root/.gvm/gos/go1.11.1/src/testing/testing.go:878 +0x353
FAIL	github.com/couchbase/sync_gateway/base	491.689s
```
</details>

**Comment by bbrks** [comment]
Tests are stable now.
