### ISSUE TITLE
_bulk_get with incorrect data produces panic in SG + Empty reply from server

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#739]
```
curl -v -H 'Content-Type: application/json' -d '{"keys":["d58bb33c0a21ccf3de580108f9e3f5d5"]}' -X POST http://127.0.0.1:4985/sync_gateway/_bulk_get
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4985 (#0)
> POST /sync_gateway/_bulk_get HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:4985
> Accept: */*
> Content-Type: application/json
> Content-Length: 45
> 
* upload completely sent off: 45 out of 45 bytes
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

logs from SG(commit 5d231):

```
2015/03/14 23:29:23 http: panic serving 127.0.0.1:48696: interface conversion: interface is nil, not []interface {}
goroutine 51 [running]:
net/http.func·011()
    /usr/local/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x9fdb60, 0xc2080e0480)
    /usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/couchbase/sync_gateway/rest.func·005(0xc208159110, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/bulk_api.go:307 +0xeb
github.com/couchbase/sync_gateway/rest.(*handler).writeMultipart(0xc208270090, 0xabcac0, 0x5, 0x7f2656eae8c0, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:450 +0x338
github.com/couchbase/sync_gateway/rest.(*handler).handleBulkGet(0xc208270090, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/bulk_api.go:360 +0x1b5
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc208270090, 0xd25be0, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x430
github.com/couchbase/sync_gateway/rest.func·015(0x7f265703db68, 0xc208208000, 0xc2080280d0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7c
net/http.HandlerFunc.ServeHTTP(0xc208129a20, 0x7f265703db68, 0xc208208000, 0xc2080280d0)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208019630, 0x7f265703db68, 0xc208208000, 0xc2080280d0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x288
github.com/couchbase/sync_gateway/rest.func·017(0x7f265703db68, 0xc208208000, 0xc2080280d0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:226 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc2081d4560, 0x7f265703db68, 0xc208208000, 0xc2080280d0)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
net/http.serverHandler.ServeHTTP(0xc2080a9e60, 0x7f265703db68, 0xc208208000, 0xc2080280d0)
    /usr/local/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc2080ac180)
    /usr/local/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
    /usr/local/go/src/pkg/net/http/server.go:1721 +0x313
```

ps: correct request looks like

```
curl -v -H 'Content-Type: application/json' -d '{"docs":[{"id":"d58bb33c0a21ccf3de580108f9e3f5d5"}]}' -X POST http://127.0.0.1:4985/sync_gateway/_bulk_get
```

it's better to handle such invalid data and provide corresponding response

**Comment by adamcfraser** [comment]
This has been fixed - the curl specified now returns a 400 bad request (missing docs property), and no panic in the SG logs.
