### ISSUE TITLE
SG expvars don’t get posted as artifacts

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#765]
See [perf run 858](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/858/)

The perf runner fails trying to write non-existent gateload expvars at the end of the run, which ends up meaning the SG expvars don’t get posted as artifacts

**Comment by tleyden** [comment]
Relevant logs:

```
[30/Mar/2015 15:48:03] INFO - Checking pass or fail
[30/Mar/2015 15:48:03] ERROR - Test failed because at least one of the latencies does not meet KPI
[30/Mar/2015 15:48:03] INFO - Running cbcollect_info
[30/Mar/2015 15:48:03] INFO - Running cbcollect_info
[30/Mar/2015 15:49:26] INFO - Getting web logs from 172.23.96.64:8091
[30/Mar/2015 15:49:26] INFO - Collecting diagnostic information from sync gateway_1 172.23.96.67
[30/Mar/2015 15:49:26] INFO - Collecting diagnostic information from sync gateway_0 172.23.96.66
[30/Mar/2015 15:49:26] INFO - Collecting diagnostic information from sync gateway_2 172.23.96.62

Fatal error: get() encountered an exception while downloading '/root/gateload_expvar_3.json'

Underlying exception:
    No such file

Aborting.
[30/Mar/2015 15:49:27] WARNING - Exception calling get(gateload_expvar_3.json, gateload_expvar_3.json).  Ignoring.
[30/Mar/2015 15:49:29] INFO - Collecting diagnostic information from gateload_1 172.23.96.68
[30/Mar/2015 15:49:29] INFO - Collecting diagnostic information from gateload_0 172.23.96.63
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/jenkins/workspace/cen006-p0-cbsgw-real-perf/perfrunner/__main__.py", line 55, in <module>
    main()
  File "/root/jenkins/workspace/cen006-p0-cbsgw-real-perf/perfrunner/__main__.py", line 52, in main
    test.run()
  File "perfrunner/tests/__init__.py", line 85, in __exit__
    self.debug()
  File "perfrunner/tests/__init__.py", line 178, in debug
    self.reporter.check_sgw_logs()
  File "perfrunner/helpers/reporter.py", line 266, in check_sgw_logs
    with open('sgw_check_logs_{}.out'.format(item)) as infile:
IOError: [Errno 2] No such file or directory: 'sgw_check_logs_gateload_2.out'
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```

**Comment by tleyden** [comment]
Notes to self:
- remote.py calls start_test_info for @all_gateways, which kicks off sgw_test_info.sh 
- sgw_test_info.sh will end up saving two files: gateload_expvar_{1..2}.json on each sync gw machine
- remote.py calls collect_info_gateway for @all_gateways, which tries to grab gateload_expvar_{1..3}.json (but gateload_expvar_3.json doesn't exist, so it fails)

**Comment by tleyden** [comment]
This can get closed after this gerrit request is merged: http://review.couchbase.org/#/c/49066/
