### ISSUE TITLE
tests with large revs: http: panic serving [::1]:59607: can't find rev:

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#807]
SG commit c3599690e5462efdba94
couchbase-lite-ios commit feb7ff5eda1e80bd00e5eb19
test https://gist.github.com/andreibaranouski/c0a8967b8f8fd423981a

automation steps:
1. git clone https://github.com/couchbaselabs/sync-gateway-tests.git
2. cd sync-gateway-tests 
3. npm install
4. `export CONF_FILE=local`  (so that it uses walrus -- probably not needed since it defaults to walrus)
5. set env variables for sync_gateway & LiteServ like
   export SYNCGATE_PATH=~/couchbase_src/sync_gateway/bin/sync_gateway
   export LITESERV_PATH=/Users/andrei/couchbase_src/couchbase-lite-ios/build/Products/Debug/LiteServ
6. node tests/a-cb-presetup.js
   (this will be a no-op with walrus)
7. replace tests/cbl-large-revisions-compact-revs-limit.js content with https://gist.github.com/andreibaranouski/c0a8967b8f8fd423981a
   (gist file suspends test on this issue)
8. run test via `node tests/cbl-large-revisions-compact-revs-limit.js`

logs at the end of the suite

```
2015-04-28T10:16:22.848+03:00 HTTP:  #1721: POST /db/_revs_diff
2015-04-28T10:16:22.848+03:00 HTTP:  #1721: POST /db/_revs_diff

2015-04-28T10:16:22.859+03:00 HTTP:  #1722: POST /db/_bulk_docs
2015-04-28T10:16:22.859+03:00 HTTP:  #1722: POST /db/_bulk_docs

2015/04/28 10:16:22 http: panic serving [::1]:59607: can't find rev: 82-44aba4a0863941333c319d3342ddecc7
goroutine 59 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/couchbase/sync_gateway/db.RevTree.getInfo(0xc209b73aa0, 0xc209b739b0, 0x23, 0xc20a963b30)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/revtree.go:122 +0xd8
github.com/couchbase/sync_gateway/db.RevTree.getHistory(0xc209b73aa0, 0xc209b739b0, 0x23, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/revtree.go:138 +0x184
github.com/couchbase/sync_gateway/db.(*Database).updateDoc(0xc20923ea80, 0xc20923eae0, 0x1b, 0x100, 0xc2098737c0, 0x0, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:667 +0x8c0
github.com/couchbase/sync_gateway/db.(*Database).PutExistingRev(0xc20923ea80, 0xc20923eae0, 0x1b, 0xc209b73140, 0xc20923f520, 0x2, 0x2, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:447 +0x447
github.com/couchbase/sync_gateway/rest.(*handler).handleBulkDocs(0xc209432990, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/bulk_api.go:397 +0xd45
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc209432990, 0x9821c0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x4b8
github.com/couchbase/sync_gateway/rest.func·015(0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7d
net/http.HandlerFunc.ServeHTTP(0xc2080fb120, 0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080438b0, 0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x29e
github.com/couchbase/sync_gateway/rest.func·017(0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:236 +0x32f
net/http.HandlerFunc.ServeHTTP(0xc20821bd00, 0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2081cfec0, 0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208eb6140)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e
2015/04/28 10:16:22 http: panic serving [::1]:59607: can't find rev: 82-44aba4a0863941333c319d3342ddecc7
goroutine 59 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/couchbase/sync_gateway/db.RevTree.getInfo(0xc209b73aa0, 0xc209b739b0, 0x23, 0xc20a963b30)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/revtree.go:122 +0xd8
github.com/couchbase/sync_gateway/db.RevTree.getHistory(0xc209b73aa0, 0xc209b739b0, 0x23, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/revtree.go:138 +0x184
github.com/couchbase/sync_gateway/db.(*Database).updateDoc(0xc20923ea80, 0xc20923eae0, 0x1b, 0x100, 0xc2098737c0, 0x0, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:667 +0x8c0
github.com/couchbase/sync_gateway/db.(*Database).PutExistingRev(0xc20923ea80, 0xc20923eae0, 0x1b, 0xc209b73140, 0xc20923f520, 0x2, 0x2, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:447 +0x447
github.com/couchbase/sync_gateway/rest.(*handler).handleBulkDocs(0xc209432990, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/bulk_api.go:397 +0xd45
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc209432990, 0x9821c0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x4b8
github.com/couchbase/sync_gateway/rest.func·015(0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7d
net/http.HandlerFunc.ServeHTTP(0xc2080fb120, 0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080438b0, 0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x29e
github.com/couchbase/sync_gateway/rest.func·017(0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:236 +0x32f
net/http.HandlerFunc.ServeHTTP(0xc20821bd00, 0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2081cfec0, 0xf1e460, 0xc209c4fea0, 0xc20a1b3860)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208eb6140)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e

2015-04-28 10:16:22.864 LiteServ[71752:970921] CBLRemoteJSONRequest[POST http://localhost:9888/db/_bulk_docs]: Got error Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo=0x7ff8b942a4a0 {NSUnderlyingError=0x7ff8b9525bb0 "The network connection was lost.", NSErrorFailingURLStringKey=http://localhost:9888/db/_bulk_docs, NSErrorFailingURLKey=http://localhost:9888/db/_bulk_docs, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}

2015-04-28T10:16:26.869+03:00 HTTP:  #1723: POST /db/_bulk_docs
2015-04-28T10:16:26.869+03:00 HTTP:  #1723: POST /db/_bulk_docs

2015/04/28 10:16:26 http: panic serving [::1]:63083: rev id "82-d7d138239fc5cdbb2343f35406fd508f" not found
goroutine 4204 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/couchbase/sync_gateway/db.RevTree.setRevisionBody(0xc209c715c0, 0xc209c71680, 0x23, 0xc209ad22c0, 0x62, 0xa3)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/revtree.go:253 +0x204
github.com/couchbase/sync_gateway/db.func·019(0xc2099e28c0, 0x1ac, 0x1ac, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:501 +0x22ac
github.com/couchbaselabs/walrus.(*lolrus).WriteUpdate(0xc208082500, 0xc209ac03e0, 0x1b, 0x0, 0xc208584690, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbaselabs/walrus/crud.go:363 +0x150
github.com/couchbase/sync_gateway/db.(*Database).updateDoc(0xc209ac0380, 0xc209ac03e0, 0x1b, 0x100, 0xc209438a80, 0x0, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:652 +0x5b1
github.com/couchbase/sync_gateway/db.(*Database).PutExistingRev(0xc209ac0380, 0xc209ac03e0, 0x1b, 0xc209c70bd0, 0xc209ac0b40, 0x2, 0x2, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:447 +0x447
github.com/couchbase/sync_gateway/rest.(*handler).handleBulkDocs(0xc208cac510, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/bulk_api.go:397 +0xd45
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc208cac510, 0x9821c0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x4b8
github.com/couchbase/sync_gateway/rest.func·015(0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7d
net/http.HandlerFunc.ServeHTTP(0xc2080fb120, 0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080438b0, 0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x29e
github.com/couchbase/sync_gateway/rest.func·017(0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:236 +0x32f
net/http.HandlerFunc.ServeHTTP(0xc20821bd00, 0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2081cfec0, 0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20a309360)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e
2015/04/28 10:16:26 http: panic serving [::1]:63083: rev id "82-d7d138239fc5cdbb2343f35406fd508f" not found
goroutine 4204 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/couchbase/sync_gateway/db.RevTree.setRevisionBody(0xc209c715c0, 0xc209c71680, 0x23, 0xc209ad22c0, 0x62, 0xa3)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/revtree.go:253 +0x204
github.com/couchbase/sync_gateway/db.func·019(0xc2099e28c0, 0x1ac, 0x1ac, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:501 +0x22ac
github.com/couchbaselabs/walrus.(*lolrus).WriteUpdate(0xc208082500, 0xc209ac03e0, 0x1b, 0x0, 0xc208584690, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbaselabs/walrus/crud.go:363 +0x150
github.com/couchbase/sync_gateway/db.(*Database).updateDoc(0xc209ac0380, 0xc209ac03e0, 0x1b, 0x100, 0xc209438a80, 0x0, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:652 +0x5b1
github.com/couchbase/sync_gateway/db.(*Database).PutExistingRev(0xc209ac0380, 0xc209ac03e0, 0x1b, 0xc209c70bd0, 0xc209ac0b40, 0x2, 0x2, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:447 +0x447
github.com/couchbase/sync_gateway/rest.(*handler).handleBulkDocs(0xc208cac510, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/bulk_api.go:397 +0xd45
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc208cac510, 0x9821c0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x4b8
github.com/couchbase/sync_gateway/rest.func·015(0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7d
net/http.HandlerFunc.ServeHTTP(0xc2080fb120, 0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080438b0, 0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x29e
github.com/couchbase/sync_gateway/rest.func·017(0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:236 +0x32f
net/http.HandlerFunc.ServeHTTP(0xc20821bd00, 0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2081cfec0, 0xf1e460, 0xc20a309400, 0xc2091c05b0)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20a309360)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e

2015-04-28 10:16:26.872 LiteServ[71752:970921] CBLRemoteJSONRequest[POST http://localhost:9888/db/_bulk_docs]: Got error Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo=0x7ff8bb90b470 {NSUnderlyingError=0x7ff8b9518010 "The network connection was lost.", NSErrorFailingURLStringKey=http://localhost:9888/db/_bulk_docs, NSErrorFailingURLKey=http://localhost:9888/db/_bulk_docs, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}

2015-04-28T10:16:27.267+03:00 HTTP:  #1724: PUT /db/_local/eb57a6fca2e24f9cdd7a0737b57b41d69a041507
2015-04-28T10:16:27.267+03:00 HTTP:  #1724: PUT /db/_local/eb57a6fca2e24f9cdd7a0737b57b41d69a041507

2015-04-28T10:16:27.270+03:00 HTTP:  #1725: PUT /db/_local/62a6008cf6c75d374cfb09864cabfe5faf5deac1
2015-04-28T10:16:27.270+03:00 HTTP:  #1725: PUT /db/_local/62a6008cf6c75d374cfb09864cabfe5faf5deac1

2015-04-28T10:16:34.874+03:00 HTTP:  #1726: POST /db/_bulk_docs
2015-04-28T10:16:34.874+03:00 HTTP:  #1726: POST /db/_bulk_docs

2015/04/28 10:16:34 http: panic serving [::1]:63084: rev id "82-d7d138239fc5cdbb2343f35406fd508f" not found
goroutine 4205 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/couchbase/sync_gateway/db.RevTree.setRevisionBody(0xc2095643f0, 0xc2095644b0, 0x23, 0xc20a380bb0, 0x62, 0xa3)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/revtree.go:253 +0x204
github.com/couchbase/sync_gateway/db.func·019(0xc20a994e00, 0x1ac, 0x1ac, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:501 +0x22ac
github.com/couchbaselabs/walrus.(*lolrus).WriteUpdate(0xc208082500, 0xc208684680, 0x1b, 0x0, 0xc209b0a2a0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbaselabs/walrus/crud.go:363 +0x150
github.com/couchbase/sync_gateway/db.(*Database).updateDoc(0xc208684600, 0xc208684680, 0x1b, 0x100, 0xc209066800, 0x0, 0x0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:652 +0x5b1
github.com/couchbase/sync_gateway/db.(*Database).PutExistingRev(0xc208684600, 0xc208684680, 0x1b, 0xc20897d140, 0xc208685920, 0x2, 0x2, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:447 +0x447
github.com/couchbase/sync_gateway/rest.(*handler).handleBulkDocs(0xc209432bd0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/bulk_api.go:397 +0xd45
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc209432bd0, 0x9821c0, 0x0, 0x0)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x4b8
github.com/couchbase/sync_gateway/rest.func·015(0xf1e460, 0xc209a02140, 0xc2091c0f70)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7d
net/http.HandlerFunc.ServeHTTP(0xc2080fb120, 0xf1e460, 0xc209a02140, 0xc2091c0f70)
    /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080438b0, 0xf1e460, 0xc209a02140, 0xc2091c0f70)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x29e
github.com/couchbase/sync_gateway/rest.func·017(0xf1e460, 0xc209a02140, 0xc2091c0f70)
    /Users/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:236 +0x32f
net/http.HandlerFunc.ServeHTTP(0xc20821bd00, 0xf1e460, 0xc209a02140, 0xc2091c0f70)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2081cfec0, 0xf1e460, 0xc209a02140, 0xc2091c0f70)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20a309a40)
```

**Comment by tleyden** [comment]
@andreibaranouski 

creating the bucket doesn’t seem to be working for me:

```
 node tests/a-cb-presetup.js
TAP version 13
# delete bucket
# create bucket

1..0
# tests 0

# ok
```

(but there’s no bucket)

**Comment by tleyden** [comment]
it appears that due to this line:

```
conf_file = process.env.CONF_FILE || 'local',
```

it's choosing the `../config/local.js` file which has:

```
DbUrl             : "walrus:",
```

I set CONF_FILE environment variable to `local_cb` and that fixed it.  Updating steps to repro above.

**Comment by tleyden** [comment]
I was having issues with my couchbase server setup, so I switched to walrus and was able to reproduce.  (btw, this is on the sg release/1.1.0 branch)

Full logs:

https://gist.github.com/tleyden/c3874509e0d98102403e

I was **not** able to reproduce with the `feature/distributed_cache_stale_ok` branch, so it looks like it was caused by one of the changes since that branch was created.

**Comment by tleyden** [comment]
I added some more verbose logging leading up to the panic:

```
2015-04-30T16:13:22.890-07:00 HTTP:  #1747: POST /db/_bulk_docs

2015-04-30T16:13:22.890-07:00 getInfo called for 82-d699eea0f497c4dd85667532873a1c06
2015-04-30T16:13:22.890-07:00 getInfo called for 82-d699eea0f497c4dd85667532873a1c06

2015-04-30T16:13:22.890-07:00 getInfo called for 82-d699eea0f497c4dd85667532873a1c06
2015-04-30T16:13:22.890-07:00 getInfo called for 81-dede8578a8c5779432ae3fe6df8731f2
2015-04-30T16:13:22.890-07:00 getInfo called for 80-f5549c5fc221b95d08b4d0b5aa5fcbba
2015-04-30T16:13:22.890-07:00 getInfo called for 79-593b2c9e09818380c28f01dced8b4b1e
2015-04-30T16:13:22.891-07:00 getInfo called for 78-4deb0e09a98120e1082a7601bdbb31cf
2015-04-30T16:13:22.890-07:00 getInfo called for 82-d699eea0f497c4dd85667532873a1c06
2015-04-30T16:13:22.890-07:00 getInfo called for 81-dede8578a8c5779432ae3fe6df8731f2
2015-04-30T16:13:22.890-07:00 getInfo called for 80-f5549c5fc221b95d08b4d0b5aa5fcbba
2015-04-30T16:13:22.890-07:00 getInfo called for 79-593b2c9e09818380c28f01dced8b4b1e
2015-04-30T16:13:22.891-07:00 getInfo called for 78-4deb0e09a98120e1082a7601bdbb31cf

2015-04-30T16:13:22.891-07:00 getInfo called for 77-2ba9da5707ebe64f82b31e1e7655518b
2015-04-30T16:13:22.891-07:00 getInfo called for 76-5fcc8ad401df2090b294aff8c83a3c53
2015-04-30T16:13:22.891-07:00 getInfo called for 75-59f5f281ed2428da889305d8824abc70
2015-04-30T16:13:22.891-07:00 getInfo called for 74-25f6919b5fa4831a5dfac9c088df5a4f
2015-04-30T16:13:22.891-07:00 getInfo called for 73-13b04d9a46cd43cbc16471dfc6ffc401
2015-04-30T16:13:22.891-07:00 getInfo called for 72-657af01ef8b72efce4693dc89b6ddb61
2015-04-30T16:13:22.891-07:00 pruneRevisions() on doc: large-revisions-revslimit_2
2015-04-30T16:13:22.891-07:00 pruned: 76-5fcc8ad401df2090b294aff8c83a3c53
2015-04-30T16:13:22.891-07:00 pruned: 78-4deb0e09a98120e1082a7601bdbb31cf
2015-04-30T16:13:22.891-07:00 pruned: 79-593b2c9e09818380c28f01dced8b4b1e
2015-04-30T16:13:22.891-07:00 pruned: 80-f5549c5fc221b95d08b4d0b5aa5fcbba
2015-04-30T16:13:22.891-07:00 pruned: 82-d699eea0f497c4dd85667532873a1c06
2015-04-30T16:13:22.891-07:00 pruned: 72-657af01ef8b72efce4693dc89b6ddb61
2015-04-30T16:13:22.891-07:00 pruned: 74-25f6919b5fa4831a5dfac9c088df5a4f
2015-04-30T16:13:22.891-07:00 getInfo called for 77-2ba9da5707ebe64f82b31e1e7655518b
2015-04-30T16:13:22.891-07:00 getInfo called for 76-5fcc8ad401df2090b294aff8c83a3c53
2015-04-30T16:13:22.891-07:00 getInfo called for 75-59f5f281ed2428da889305d8824abc70
2015-04-30T16:13:22.891-07:00 getInfo called for 74-25f6919b5fa4831a5dfac9c088df5a4f
2015-04-30T16:13:22.891-07:00 getInfo called for 73-13b04d9a46cd43cbc16471dfc6ffc401
2015-04-30T16:13:22.891-07:00 getInfo called for 72-657af01ef8b72efce4693dc89b6ddb61
2015-04-30T16:13:22.891-07:00 pruneRevisions() on doc: large-revisions-revslimit_2
2015-04-30T16:13:22.891-07:00 pruned: 76-5fcc8ad401df2090b294aff8c83a3c53
2015-04-30T16:13:22.891-07:00 pruned: 78-4deb0e09a98120e1082a7601bdbb31cf
2015-04-30T16:13:22.891-07:00 pruned: 79-593b2c9e09818380c28f01dced8b4b1e
2015-04-30T16:13:22.891-07:00 pruned: 80-f5549c5fc221b95d08b4d0b5aa5fcbba
2015-04-30T16:13:22.891-07:00 pruned: 82-d699eea0f497c4dd85667532873a1c06
2015-04-30T16:13:22.891-07:00 pruned: 72-657af01ef8b72efce4693dc89b6ddb61
2015-04-30T16:13:22.891-07:00 pruned: 74-25f6919b5fa4831a5dfac9c088df5a4f

2015-04-30T16:13:22.891-07:00 pruned: 77-2ba9da5707ebe64f82b31e1e7655518b
2015-04-30T16:13:22.891-07:00 pruned: 81-dede8578a8c5779432ae3fe6df8731f2
2015-04-30T16:13:22.891-07:00 pruned: 73-13b04d9a46cd43cbc16471dfc6ffc401
2015-04-30T16:13:22.891-07:00 pruned: 75-59f5f281ed2428da889305d8824abc70
2015-04-30T16:13:22.891-07:00 updateDoc("large-revisions-revslimit_2"): Pruned 11 old revisions
2015-04-30T16:13:22.891-07:00 getting doc history for doc: large-revisions-revslimit_2 rev: 82-d699eea0f497c4dd85667532873a1c06
2015-04-30T16:13:22.891-07:00 getInfo called for 82-d699eea0f497c4dd85667532873a1c06
2015-04-30T16:13:22.891-07:00 Looping over revtree
2015-04-30T16:13:22.891-07:00 /Looping over revtree
2015/04/30 16:13:22 http: panic serving [::1]:61079: can't find rev: 82-d699eea0f497c4dd85667532873a1c06
```

So it appears that the revision that the client is asking for in the _bulk_docs request has been pruned.  

@snej any thoughts on this?  anything I can collect that would shed more light on the issue?

**Comment by tleyden** [comment]
Reproducible on commit b0e5ea555a9105444b26dcbff202ef657847ca24 and later but not on commit df9980fef721, so was introduced in b0e5ea555a9105444b26dcbff202ef657847ca24.

**Comment by snej** [comment]
Looks like a client `_bulk_docs` call is trying to _put_ a new revision (not get an existing one) and ~~the RevTree can't find the existing ancestor so it panics. This shouldn't be a panic — it should just insert the new rev and its history into the RevTree as an isolated chain.~~

**Comment by snej** [comment]
I was wrong above; was looking at the wrong branch so line numbers had shifted. What's really going on is that doc.History (the rev tree) doesn't contain an entry for doc.CurrentRev, so it panics trying to store a body into it. It's screwy that this would happen — it must be a situation where the current rev is a low enough generation that it got pruned, meaning that there's some deleted branch with a much longer history...

**Comment by tleyden** [comment]
I've uploaded the raw ngrep logs from a successful test with https://github.com/couchbase/sync_gateway/commit/df9980fef7217f26f0ca8cbbbd6270e94b874787 vs a failed test with https://github.com/couchbase/sync_gateway/commit/b0e5ea555a9105444b26dcbff202ef657847ca24 here:

http://cl.ly/3X3H3Q0Y362c/download/issue_807_ngrep_traces.tar.gz

**Comment by tleyden** [comment]
I enabled full sync gateway logs and captured them in gists:

[failure case](https://gist.github.com/tleyden/4cf5c531e372fc41984e)
[passing case](https://gist.github.com/tleyden/831acd25eb377995086a)

**Comment by snej** [comment]
The problem, I'm pretty sure, is that the document was deleted. Then there were zero undeleted leaf revisions, and the algorithm ended up pruning _everything_. Oops.
I fixed the algorithm to handle that case, and updated the unit tests to check.

**Comment by tleyden** [comment]
@andreibaranouski can you add some docs to the top of the test which explain what it does in a step-by-step fashion.  For example:
- Fires up a LiteServIOS and a Sync Gateway instance 
- Creates a push replication from LiteServ -> Sync Gateway
- Loads a lot of docs into LiteServ  (not 100% sure)
- Kicks off a concurrent task to update docs on Sync Gw
- Kicks off a concurrent task to update docs on Liteserv (presumably creating conflicts, since updating potentially the same docs)

**Comment by tleyden** [comment]
@snej I verified the fix and will cherry pick to release/1.1.0. 

[Success sync gw logs](https://gist.github.com/tleyden/23eadbaf2f453897cdc8)

**Comment by andreibaranouski** [comment]
@tleyden will add description steps to the top of the tests
the issue is not produced anymore on the master branch

**Comment by tleyden** [comment]
@zgramana / @adamcfraser -- any thoughts about putting this in 1.1.1?
