### ISSUE TITLE
Couchbase-lite replication error

### ISSUE THREAD

**Issue by ZeeshanNiazi** [couchbase/sync_gateway#918]
Hi,
i am working with pure java and couchbase-lite.
running following code:

Manager manager = new Manager(new JavaContext("data"), Manager.DEFAULT_OPTIONS);
Manager.enableLogging("Sync", Log.VERBOSE);
final Database db = manager.getDatabase("sync_gateway");

URL url = new URL("http://localhost:4984/sync_gateway/");
Replication push = db.createPushReplication(url);
Replication pull = db.createPullReplication(url);
pull.setContinuous(true);
push.setContinuous(true);
com.couchbase.lite.auth.Authenticator auth = AuthenticatorFactory.createBasicAuthenticator("GUEST", "");
push.setAuthenticator(auth);
push.setAuthenticator(auth);
pull.setAuthenticator(auth);
push.start();
pull.start();

on line push.start()
it through exception:
Jun 11, 2015 8:46:23 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Sync: RemoteRequest.run() exception: %s
java.lang.ArrayIndexOutOfBoundsException: 1
    at com.couchbase.lite.support.RemoteRequest.preemptivelySetAuthCredentials(RemoteRequest.java:281)
    at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:96)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Jun 11, 2015 8:48:02 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Sync: RemoteRequest.run() exception: %s
java.lang.ArrayIndexOutOfBoundsException: 1
    at com.couchbase.lite.support.RemoteRequest.preemptivelySetAuthCredentials(RemoteRequest.java:281)
    at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:96)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Jun 11, 2015 8:48:11 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Sync: RemoteRequest.run() exception: %s
java.lang.ArrayIndexOutOfBoundsException: 1
at com.couchbase.lite.support.RemoteRequest.preemptivelySetAuthCredentials(RemoteRequest.java:281)
    at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:96)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

I started my sync_gateway, and I want to sync my couchbase lite to couchbase full node.
I started sync_gateway with ip of couchbase full node. now as I know, I only need to run this couchbase lite replication code and my data of couchbase lite will be copied to couchbase full node.
kindly help.

**Comment by adamcfraser** [comment]
The forum (where you'd already posted this - https://forums.couchbase.com/t/couchbase-lite-replication-error/4096) is the right place for this kind of question.
