### ISSUE TITLE
Panic serving _changes on admin port

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#941]
There's a new log call on the changes feed that dereferences the user's name without checking for nil, so it causes a panic if the request is on the admin port. (This log appears both in `sendSimpleChanges` and `generateContinuousChanges`.)

To trigger it all you have to do is start SG with no arguments (i.e. with an empty Walrus db) and send it

```
GET 127.0.0.1:4985/sync_gateway/_changes?feed=longpoll&heartbeat=5000&since=1
```

Result:

```
2015-06-22T15:00:13.346-07:00 HTTP:  #002: GET /sync_gateway/_changes?feed=longpoll&heartbeat=5000&since=1  (ADMIN)
2015/06/22 15:00:38 http: panic serving 127.0.0.1:62388: runtime error: invalid memory address or nil pointer dereference
goroutine 50 [running]:
net/http.func·011()
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
github.com/couchbase/sync_gateway/rest.(*handler).sendSimpleChanges(0xc20823c240, 0xc208195740, 0x0, 0x0, 0x1, 0x0, 0x10000, 0xc208202120, 0x61a8, 0x493e0, ...)
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/rest/changes_api.go:203 +0x945
github.com/couchbase/sync_gateway/rest.(*handler).handleChanges(0xc20823c240, 0x0, 0x0)
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/rest/changes_api.go:140 +0xb7e
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc20823c240, 0x9bb7d0, 0x0, 0x0)
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x4b8
github.com/couchbase/sync_gateway/rest.func·026(0xe61428, 0xc2081e2be0, 0xc208033790)
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7d
net/http.HandlerFunc.ServeHTTP(0xc20815f1a0, 0xe61428, 0xc2081e2be0, 0xc208033790)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208040960, 0xe61428, 0xc2081e2be0, 0xc208033790)
    /Couchbase/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x29e
github.com/couchbase/sync_gateway/rest.func·028(0xe61428, 0xc2081e2be0, 0xc208033790)
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:238 +0x32f
net/http.HandlerFunc.ServeHTTP(0xc2081dbc80, 0xe61428, 0xc2081e2be0, 0xc208033790)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208202000, 0xe61428, 0xc2081e2be0, 0xc208033790)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2081e2960)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
...
```

**Comment by adamcfraser** [comment]
Andy had caught this last week - just merged his PR for it (https://github.com/couchbase/sync_gateway/pull/931).
